Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-02, with the labels that each got.

#265 Removing usage of ScrollBar2
  dev/Generated/MetadataSummary.cs
  dev/Generated/ScrollBar2.properties.cpp
  dev/Generated/ScrollBar2.properties.h
  dev/Generated/ScrollViewer.properties.cpp
  dev/Generated/ScrollViewer.properties.h
  dev/Generated/Scroller.properties.cpp
  dev/Generated/Scroller.properties.h
  dev/ScrollBar2/APITests/ScrollBar2Tests.cs
  dev/ScrollBar2/InteractionTests/ScrollBar2TestsWithInputHelper.cs
  dev/ScrollBar2/ScrollBar2.cpp
  dev/ScrollBar2/ScrollBar2.h
  dev/ScrollBar2/ScrollBar2.idl
  dev/ScrollBar2/TestUI/ScrollBar2DynamicPage.xaml
  dev/ScrollBar2/TestUI/ScrollBar2DynamicPage.xaml.cs
  dev/ScrollViewer/APITests/ScrollViewerTests.cs
  dev/ScrollViewer/ScrollBarController.cpp
  dev/ScrollViewer/ScrollBarController.h
  dev/ScrollViewer/ScrollViewer.cpp
  dev/ScrollViewer/ScrollViewer.h
  dev/ScrollViewer/ScrollViewer.idl
  dev/ScrollViewer/ScrollViewer.vcxitems
  dev/ScrollViewer/ScrollViewer.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerWithScrollControllersPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewersWithSimpleContentsPage.xaml.cs
  dev/Scroller/APITests/ScrollControllerTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/ScrollerPrimitives.idl
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerWithSimpleScrollControllersPage.xaml.cs
  test/MUXControlsTestApp/Utilities/BiDirectionalScrollController.cs
  test/MUXControlsTestApp/Utilities/CompositionScrollController.cs
Labels: area-Scrolling

#283 TeachingTip test pattern update.
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/InteractionTests/TeachingTip_InteractionTests.projitems
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: area-TeachingTip

#287 Adding Scroller/ScrollViewer ViewportWidth/Height and ScrollableWidth/Height read-only properties.
  dev/ScrollViewer/APITests/ScrollViewerTests.cs
  dev/ScrollViewer/ScrollViewer.cpp
  dev/ScrollViewer/ScrollViewer.h
  dev/ScrollViewer/ScrollViewer.idl
  dev/Scroller/APITests/ScrollerTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/ScrollerAutomationPeer.cpp
  dev/Scroller/ScrollerPrimitives.idl
Labels: area-Scrolling

#296 Removing unused ScrollBar2 control.
  MUXControls.sln
  README.md
  build/Helix/RunTestsInHelix.proj
  build/NuSpecs/Intellisense/Microsoft.UI.Xaml.xml
  dev/Generated/MetadataSummary.cs
  dev/Generated/ScrollBar2.properties.cpp
  dev/Generated/ScrollBar2.properties.h
  dev/ScrollBar2/APITests/ScrollBar2Tests.cs
  dev/ScrollBar2/APITests/ScrollBar2_APITests.projitems
  dev/ScrollBar2/APITests/ScrollBar2_APITests.shproj
  dev/ScrollBar2/InteractionTests/ScrollBar2TestsWithInputHelper.cs
  dev/ScrollBar2/InteractionTests/ScrollBar2_InteractionTests.projitems
  dev/ScrollBar2/InteractionTests/ScrollBar2_InteractionTests.shproj
  dev/ScrollBar2/ScrollBar2.cpp
  dev/ScrollBar2/ScrollBar2.h
  dev/ScrollBar2/ScrollBar2.idl
  dev/ScrollBar2/ScrollBar2.vcxitems
  dev/ScrollBar2/ScrollBar2Trace.h
  dev/ScrollBar2/TestUI/ScrollBar2DynamicPage.xaml
  dev/ScrollBar2/TestUI/ScrollBar2DynamicPage.xaml.cs
  dev/ScrollBar2/TestUI/ScrollBar2LeakDetectionPage.xaml
  dev/ScrollBar2/TestUI/ScrollBar2LeakDetectionPage.xaml.cs
  dev/ScrollBar2/TestUI/ScrollBar2Page.xaml
  dev/ScrollBar2/TestUI/ScrollBar2Page.xaml.cs
  dev/ScrollBar2/TestUI/ScrollBar2_TestUI.projitems
  dev/ScrollBar2/TestUI/ScrollBar2_TestUI.shproj
  dev/ScrollViewer/InteractionTests/ScrollViewerTestsWithInputHelper.cs
  dev/ScrollViewer/ScrollBarController.h
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerPage.xaml.cs
  dev/Telemetry/TraceLogging.h
  dev/TestHooks/MUXControlsTestHooks.cpp
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/XamlMetadataProviderGenerated.tt
  idl/Microsoft.UI.Xaml.idl
  test/MUXControls.Test/MUXControls.Test.Shared.targets
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
  test/MUXControlsTestApp/TestInventory.cs
  test/MUXControlsTestAppWPFPackage/Package.appxmanifest
Labels: area-Scrolling

#299 Removing Scroller/ScrollViewer's IsAnchoredAtHorizontalExtent and IsAnchoredAtVerticalExtent boolean properties
  dev/Generated/MetadataSummary.cs
  dev/Generated/ScrollViewer.properties.cpp
  dev/Generated/ScrollViewer.properties.h
  dev/Generated/Scroller.properties.cpp
  dev/Generated/Scroller.properties.h
  dev/ScrollViewer/APITests/ScrollViewerTests.cs
  dev/ScrollViewer/ScrollViewer.cpp
  dev/ScrollViewer/ScrollViewer.idl
  dev/ScrollViewer/ScrollViewer.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerWithScrollControllersPage.xaml
  dev/Scroller/APITests/ScrollerAnchoringTests.cs
  dev/Scroller/APITests/ScrollerTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/ScrollerAnchoring.cpp
  dev/Scroller/ScrollerPrimitives.idl
  dev/Scroller/TestUI/ScrollerRepeaterAnchoringPage.xaml
  dev/Scroller/TestUI/ScrollerRepeaterAnchoringPage.xaml.cs
  dev/Scroller/TestUI/ScrollerStackPanelAnchoringPage.xaml
  dev/Scroller/TestUI/ScrollerStackPanelAnchoringPage.xaml.cs
Labels: area-Scrolling

#301 Scroller/ScrollViewer InputKind property replaced with IgnoredInputKind
  dev/Generated/MetadataSummary.cs
  dev/Generated/ScrollViewer.properties.cpp
  dev/Generated/ScrollViewer.properties.h
  dev/Generated/Scroller.properties.cpp
  dev/Generated/Scroller.properties.h
  dev/ScrollViewer/APITests/ScrollViewerTests.cs
  dev/ScrollViewer/InteractionTests/ScrollViewerTestsWithInputHelper.cs
  dev/ScrollViewer/ScrollViewer.cpp
  dev/ScrollViewer/ScrollViewer.h
  dev/ScrollViewer/ScrollViewer.idl
  dev/ScrollViewer/ScrollViewer.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerWithScrollControllersPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewersWithSimpleContentsPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewersWithSimpleContentsPage.xaml.cs
  dev/Scroller/APITests/ScrollerTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/Scroller.idl
  dev/Scroller/ScrollerPrimitives.idl
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
  dev/Telemetry/TypeLogging.cpp
Labels: area-Scrolling

#302 Adding ScrollViewer anchor registering/unregistering public methods
  dev/ScrollViewer/APITests/ScrollViewerTests.cs
  dev/ScrollViewer/ScrollViewer.cpp
  dev/ScrollViewer/ScrollViewer.h
  dev/ScrollViewer/ScrollViewer.idl
  dev/inc/ErrorHandling.h
Labels: area-Scrolling

#270 Updating FireEvent to be callable from process detach
  dev/dll/dllmain.cpp
Labels: auto merge

#335 Porting Reveal Fallback Change from WUXC
  dev/Materials/Reveal/RevealBrush.cpp
Labels: auto merge

#336 Add a test for TreeViewNode content
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TestUI/TreeViewNodeInMarkupTestPage.xaml
  dev/TreeView/TestUI/TreeViewNodeInMarkupTestPage.xaml.cs
  dev/TreeView/TestUI/TreeViewPage.xaml
  dev/TreeView/TestUI/TreeViewPage.xaml.cs
  dev/TreeView/TestUI/TreeView_TestUI.projitems
Labels: area-TreeView, auto merge

#327 Teaching tip second popup for light dismiss
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
Labels: area-TeachingTip

#367 Update VerifyNavigationViewItemIsSelectedWorks
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
Labels: auto merge
