Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-10, with the labels that each got.

#1387 Fix bug with TreeView not updating nodes correctly when collection triggers reset event
  dev/TreeView/APITests/TreeViewTests.cs
  dev/TreeView/TreeViewNode.cpp
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
  test/MUXControlsTestApp/Utilities/ExtendedObservableCollection.cs
  test/TestAppCX/MainPage.xaml
  test/TestAppCX/MainPage.xaml.cpp
  test/TestAppCX/MainPage.xaml.h
  test/TestAppCX/TestAppCX.vcxproj
  test/TestAppCX/TestAppCX.vcxproj.filters
  test/TestAppCX/TreeViewTestPage.xaml
  test/TestAppCX/TreeViewTestPage.xaml.cpp
  test/TestAppCX/TreeViewTestPage.xaml.h
Labels: area-TreeView

#1393 TabView: Fixed ctrl-click to deselect and tab min/max width.
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TabViewItem.cpp
  dev/TabView/TestUI/TabViewPage.xaml
  dev/TabView/TestUI/TabViewPage.xaml.cs
Labels: auto merge

#1405 Fix ContentDialog CornerRadius
  MUXControls.sln
  dev/ContentDialog/ContentDialog_themeresources.xaml
  dev/ContentDialog/TestUI/ContentDialogPage.xaml.cs
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControlsTestApp/master/ContentDialog-5.xml
  test/MUXControlsTestApp/master/ContentDialog-6.xml
  test/MUXControlsTestApp/master/ContentDialog-7.xml
  test/MUXControlsTestApp/master/ContentDialog.xml
Labels: area-Styling, needs-cherrypicktorelease, release note

#1415 Fix ToggleSwitch colors
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
Labels: area-Styling

#1449 Fix a TreeViewItemAutomationPeer crash
  dev/TreeView/TreeViewItemAutomationPeer.cpp
Labels: area-TreeView, auto merge

#1450 Removing some Scroller dead code
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
Labels: area-Scrolling

#1456 Disabling failing test
  dev/CommonStyles/APITests/CommonStylesTests.cs
Labels: auto merge

#1327 Fix bug where removal of TeachingTip would leave the Popup open
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: release note

#1472 New Scroller test code for mouse-based panning and mouse-based constant-velocity-panning
  dev/Scroller/TestUI/ScrollerMousePanningPage.xaml
  dev/Scroller/TestUI/ScrollerMousePanningPage.xaml.cs
  dev/Scroller/TestUI/ScrollerPage.xaml
  dev/Scroller/TestUI/ScrollerPage.xaml.cs
  dev/Scroller/TestUI/Scroller_TestUI.projitems
Labels: area-Scrolling

#1485 Fix ScrollBar rounded corners
  dev/Common/CornerRadiusFilterConverter.cpp
  dev/Common/CornerRadiusFilterConverters.idl
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/Generated/CornerRadiusFilterConverter.properties.cpp
  dev/Generated/CornerRadiusFilterConverter.properties.h
  dev/ScrollBar/ScrollBar_themeresources.xaml
Labels: area-Styling
