Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-11, with the labels that each got.

#1560 Revert "Fixing repeated entries in Microsoft.UI.Xaml.vcxproj.filters"
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
Labels: auto merge

#1548 Fix bug with focused items not being recycled upon ItemsSource reassignment
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/InteractionTests/RepeaterTests.cs
  dev/Repeater/ItemsRepeater.cpp
  dev/Repeater/TestUI/RepeaterTestUIPage.xaml
  dev/Repeater/TestUI/Samples/CollectionChangeDemo.xaml
  dev/Repeater/TestUI/Samples/CollectionChangeDemo.xaml.cs
  test/MUXControls.Test/MUXControls.Test.Shared.targets
Labels: auto merge

#1561 Reveal cleanups
  dev/Materials/Reveal/RevealBrush_rs2_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_rs4_themeresources.xaml
  dev/MenuFlyout/MenuFlyout.vcxitems
  dev/MenuFlyout/MenuFlyout_19h1_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_rs1_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_rs2_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_rs4_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_rs5_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_themeresources.xaml
  test/MUXControlsAdhocApp/App.xaml
Labels: auto merge

#1574 conditional Arm64 min version to rs3 for FrameworkPackagePRI project
  dev/Microsoft.UI.Xaml.FrameworkPackagePRI/Microsoft.UI.Xaml.FrameworkPackagePRI.csproj
Labels: auto merge

#1617 Update MUX-CI pipeline to not publish the nuget package if run manually
  build/AzurePipelinesTemplates/MUX-CreateNugetPackage-Job.yml
Labels: auto merge

#1636 Fixing broken link feature proposal template
  docs/feature_proposal_process.md
Labels: auto merge

#1564 Refine ProgressBar Animation
  dev/Generated/ProgressBarTemplateSettings.properties.cpp
  dev/Generated/ProgressBarTemplateSettings.properties.h
  dev/ProgressBar/ProgressBar.cpp
  dev/ProgressBar/ProgressBar.h
  dev/ProgressBar/ProgressBar.idl
  dev/ProgressBar/ProgressBar.xaml
Labels: release note

#1623 Move radio buttons onto repeater
  .gitignore
  MUXControlsInnerLoop.sln
  dev/CommonStyles/CommonStyles.vcxitems
  dev/Generated/ColumnMajorUniformToLargestGridLayout.properties.cpp
  dev/Generated/ColumnMajorUniformToLargestGridLayout.properties.h
  dev/Generated/RadioButtons.properties.cpp
  dev/Generated/RadioButtons.properties.h
  dev/Generated/RadioButtonsElementFactory.properties.cpp
  dev/Generated/RadioButtonsElementFactory.properties.h
  dev/Generated/RadioButtonsTestHooks.properties.cpp
  dev/Generated/RadioButtonsTestHooks.properties.h
  dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.cpp
  dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.h
  dev/RadioButtons/InteractionTests/RadioButtonsTestPageElements.cs
  dev/RadioButtons/InteractionTests/RadioButtonsTests.cs
  dev/RadioButtons/InteractionTests/RadioButtons_InteractionTests.projitems
  dev/RadioButtons/RadioButtons.cpp
  dev/RadioButtons/RadioButtons.h
  dev/RadioButtons/RadioButtons.idl
  dev/RadioButtons/RadioButtons.vcxitems
  dev/RadioButtons/RadioButtons.vcxitems.filters
  dev/RadioButtons/RadioButtons.xaml
  dev/RadioButtons/RadioButtonsAutomationPeer.idl
  dev/RadioButtons/RadioButtonsElementFactory.cpp
  dev/RadioButtons/RadioButtonsElementFactory.h
  dev/RadioButtons/RadioButtonsListView.cpp
  dev/RadioButtons/RadioButtonsListView.h
  dev/RadioButtons/RadioButtonsListViewItem.cpp
  dev/RadioButtons/RadioButtonsListViewItem.h
  dev/RadioButtons/RadioButtonsListViewItemAutomationPeer.cpp
  dev/RadioButtons/RadioButtonsListViewItemAutomationPeer.h
  dev/RadioButtons/RadioButtonsPrimitives.idl
  dev/RadioButtons/RadioButtonsTestHooks.cpp
  dev/RadioButtons/RadioButtonsTestHooks.h
  dev/RadioButtons/RadioButtonsTestHooks.idl
  dev/RadioButtons/RadioButtons_themeresources.xaml
  dev/RadioButtons/TestUI/RadioButtonsPage.xaml
  dev/RadioButtons/TestUI/RadioButtonsPage.xaml.cs
  dev/Repeater/ItemsRepeater.cpp
  dev/Repeater/NonVirtualizingLayout.cpp
  dev/Repeater/NonVirtualizingLayout.h
  dev/Repeater/SelectionModelSelectionChangedEventArgs.cpp
  dev/Repeater/SelectionModelSelectionChangedEventArgs.h
  dev/Repeater/ViewManager.cpp
  dev/Scroller/APITests/ScrollerLayoutTests.cs
  dev/inc/CppWinRTIncludes.h
Labels: auto merge, feature proposal, release note

#1665 ProgressBar Accessibility Features & Bug Fixes
  dev/ProgressBar/InteractionTests/ProgressBarTests.cs
  dev/ProgressBar/ProgressBar.cpp
  dev/ProgressBar/ProgressBar.h
  dev/ProgressBar/ProgressBar.idl
  dev/ProgressBar/ProgressBar.vcxitems
  dev/ProgressBar/ProgressBar.xaml
  dev/ProgressBar/ProgressBarAutomationPeer.cpp
  dev/ProgressBar/ProgressBarAutomationPeer.h
  dev/ProgressBar/TestUI/ProgressBarPage.xaml.cs
Labels: auto merge, release note

#1646 Update TreeView to support blocking drag&drop for specific items
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TestUI/TreeViewPage.xaml.cs
  dev/TreeView/TreeView.cpp
  dev/TreeView/TreeView.idl
  dev/TreeView/TreeViewDragItemsCompletedEventArgs.cpp
  dev/TreeView/TreeViewDragItemsCompletedEventArgs.h
  dev/TreeView/TreeViewDragItemsStartingEventArgs.cpp
  dev/TreeView/TreeViewDragItemsStartingEventArgs.h
  dev/TreeView/TreeViewItem.cpp
  dev/TreeView/TreeViewList.cpp
Labels: release note

#1667 Fix RadioButtons putting focus on wrong element when moving between RadioButton groups
  dev/RadioButtons/InteractionTests/RadioButtonsTests.cs
  dev/RadioButtons/RadioButtons.cpp
Labels: auto merge, release note

#1609 Fix problem where TeachingTip would not update position when target has moved
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: release note

#1692 Rename "NewParent" to "NewParentItem"
  dev/TreeView/TestUI/TreeViewPage.xaml.cs
  dev/TreeView/TreeView.idl
  dev/TreeView/TreeViewDragItemsCompletedEventArgs.cpp
  dev/TreeView/TreeViewDragItemsCompletedEventArgs.h
Labels: area-TreeView

#1689 Fix rounded corners for compact mode number box
  dev/NumberBox/NumberBox.xaml
Labels: auto merge

#1690 NumberBox: Change StepFrequency to SmallChange and LargeChange
  dev/Generated/NumberBox.properties.cpp
  dev/Generated/NumberBox.properties.h
  dev/NumberBox/InteractionTests/NumberBoxTests.cs
  dev/NumberBox/NumberBox.cpp
  dev/NumberBox/NumberBox.h
  dev/NumberBox/NumberBox.idl
  dev/NumberBox/NumberBoxAutomationPeer.cpp
  dev/NumberBox/TestUI/NumberBoxPage.xaml
  dev/Repeater/TestUI/Samples/CollectionChangeDemo.xaml
Labels: area-NumberBox, release note
