Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-09, with the labels that each got.

#1269 Modify buttons inside TextBox, PasswordBox and AutoSuggestBox to correctly support rounded corners
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/CommonStyles/PasswordBox_themeresources.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
Labels: needs-cherrypicktorelease

#1280 Fix bug where pane was open when app would start minimal with NavigationView
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  dev/NavigationView/TestUI/NavigationViewMinimalPage.xaml
Labels: needs-cherrypicktorelease

#1266 Add binding to name of NavigationView for menu lists, Closes #564
  dev/NavigationView/NavigationView.xaml
Labels: needs-cherrypicktorelease, release note

#1292 Fix MediaPlayerElement volume button alignment
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
Labels: area-Styling, needs-cherrypicktorelease

#1311 Changed InnerLoop solution
  FeatureAreas.props
  MUXControlsInnerLoop.sln
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: auto merge

#1300 Add key names to default control styles
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/CalendarDatePicker/CalendarDatePicker_themeresources.xaml
  dev/CheckBox/CheckBox_themeresources.xaml
  dev/ColorPicker/ColorPicker.xaml
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommandBarFlyout/CommandBarFlyout.xaml
  dev/CommonStyles/AppBarButton_themeresources.xaml
  dev/CommonStyles/AppBarToggleButton_themeresources.xaml
  dev/CommonStyles/Button_themeresources.xaml
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/CommonStyles/FlyoutPresenter_themeresources.xaml
  dev/CommonStyles/ListBox_themeresources.xaml
  dev/CommonStyles/ListViewItem_themeresources.xaml
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
  dev/CommonStyles/PasswordBox_themeresources.xaml
  dev/CommonStyles/ProgressBar_themeresources.xaml
  dev/CommonStyles/RepeatButton_themeresources.xaml
  dev/CommonStyles/RichEditBox_themeresources.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
  dev/CommonStyles/ToggleButton_themeresources.xaml
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
  dev/ContentDialog/ContentDialog_themeresources.xaml
  dev/DatePicker/DatePicker_themeresources.xaml
  dev/DropDownButton/DropDownButton.xaml
  dev/DropDownButton/DropDownButton_rs1.xaml
  dev/FlipView/FlipViewItem_themeresources.xaml
  dev/FlipView/FlipView_themeresources.xaml
  dev/MenuBar/MenuBar.xaml
  dev/PersonPicture/PersonPicture.xaml
  dev/Pivot/Pivot_themeresources.xaml
  dev/PullToRefresh/RefreshContainer/RefreshContainer.xaml
  dev/RadioButtons/RadioButton.xaml
  dev/RadioButtons/RadioButtons.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs1_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs2_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs4_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs5_themeresources.xaml
  dev/ScrollBar/ScrollBar_themeresources.xaml
  dev/ScrollViewer/ScrollViewer.xaml
  dev/Slider/Slider_themeresources.xaml
  dev/SplitView/SplitView_themeresources.xaml
  dev/SwipeControl/SwipeControl.xaml
  dev/SwipeControl/SwipeControl_rs1.xaml
  dev/TabView/TabView.xaml
  dev/TeachingTip/TeachingTip.xaml
  dev/ToolTip/ToolTip_rs1_themeresources.xaml
  dev/ToolTip/ToolTip_rs5_themeresources.xaml
  dev/TreeView/TreeView.xaml
  dev/TwoPaneView/TwoPaneView.xaml
  dev/TwoPaneView/TwoPaneView_rs1.xaml
Labels: area-Styling, needs-cherrypicktorelease

#1324 Fix a SplitView pane open/close issue when animations are disabled
  dev/SplitView/SplitView_themeresources.xaml
Labels: needs-cherrypicktorelease, release note

#1325 Fix bug with HorizontalContentAlignment not working on NavigationViewItem
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/NavigationView/TestUI/NavigationViewCaseBundle.xaml
  dev/NavigationView/TestUI/NavigationViewCaseBundle.xaml.cs
  dev/NavigationView/TestUI/NavigationViewMenuItemStretchPage.xaml
  dev/NavigationView/TestUI/NavigationViewMenuItemStretchPage.xaml.cs
  dev/NavigationView/TestUI/NavigationView_TestUI.projitems
Labels: needs-cherrypicktorelease, release note

#1328 Fix crash in RefreshVisualizer when not wrapping a ScrollViewer
  dev/PullToRefresh/RefreshVisualizer/RefreshVisualizer.cpp
Labels: needs-cherrypicktorelease, release note

#1340 SplitButton: Propagate FontFamily/Size/Weight properties to inner Button
  dev/SplitButton/SplitButton.xaml
  dev/SplitButton/TestUI/SplitButtonPage.xaml
Labels: needs-cherrypicktorelease, release note

#1339 Fix for terminal handling scrollviewer load issue
  FeatureAreas.props
  dev/TabView/TabView.cpp
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/SharedHelpers.cpp
  dev/inc/SharedHelpers.h
Labels: needs-cherrypicktorelease, release note

#1305 Fix Teaching Tip's Rounded Corners
  dev/Common/Common.vcxitems
  dev/Common/CornerRadiusToThicknessConverter.cpp
  dev/Common/CornerRadiusToThicknessConverter.h
  dev/Common/CornerRadiusToThicknessConverter.idl
  dev/CommonStyles/CornerRadius_themeresources.xaml
  dev/Generated/CornerRadiusToThicknessConverter.properties.cpp
  dev/Generated/CornerRadiusToThicknessConverter.properties.h
  dev/Generated/ThicknessFilterConverter.properties.cpp
  dev/Generated/ThicknessFilterConverter.properties.h
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: needs-cherrypicktorelease, release note

#1344 Fix bug with textbox clipping under small width and height
  dev/CommonStyles/TextBox_themeresources.xaml
Labels: release note

#1348 Fix glyph opacity issue when recycling elements in treeview.
  dev/TreeView/APITests/TreeViewTests.cs
  dev/TreeView/TreeViewItem.cpp
Labels: auto merge

#1357 Fix TreeViewNode content display
  dev/TreeView/TreeViewNode.cpp
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/NugetTestsCX.cs
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/MainPage.xaml
Labels: area-TreeView, release note
