Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-12, with the labels that each got.

#1703 Fix to layout cycle issue in Terminal
  dev/TabView/TabView.cpp
  dev/TabView/TabView.h
Labels: area-TabView, needs-cherrypicktorelease, team-Controls

#1580 fixed the closed button displaying bug
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
  dev/TabView/TestUI/TabViewPage.xaml.cs
Labels: needs-author-feedback

#1713 Fixes several bugs
  dev/NumberBox/NumberBox.cpp
  dev/NumberBox/NumberBox.h
  dev/NumberBox/NumberBox.xaml
Labels: needs-triage

#1716 Refactor tracker_ref a little to avoid ICE in VS 16.4
  dev/inc/tracker_ref.h
Labels: area-DevInternal, team-Controls

#1717 Updated WinUI 2.2 version references to 2.3.
  README.md
Labels: needs-triage

#1711 Fix bug where scrolling a NumberBox inside ScrollViewer would scroll both
  dev/NumberBox/InteractionTests/NumberBoxTests.cs
  dev/NumberBox/NumberBox.cpp
  dev/NumberBox/TestUI/NumberBoxPage.xaml
  dev/NumberBox/TestUI/NumberBoxPage.xaml.cs
Labels: area-NumberBox, needs-cherrypicktorelease, team-Controls

#1718 Remove WPF test apps
  MUXControls.sln
  test/MUXControlsTestAppForIslands/App.xaml
  test/MUXControlsTestAppForIslands/App.xaml.cs
  test/MUXControlsTestAppForIslands/Assets/LockScreenLogo.scale-200.png
  test/MUXControlsTestAppForIslands/Assets/SplashScreen.scale-200.png
  test/MUXControlsTestAppForIslands/Assets/Square150x150Logo.scale-200.png
  test/MUXControlsTestAppForIslands/Assets/Square44x44Logo.scale-200.png
  test/MUXControlsTestAppForIslands/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  test/MUXControlsTestAppForIslands/Assets/StoreLogo.png
  test/MUXControlsTestAppForIslands/Assets/Wide310x150Logo.scale-200.png
  test/MUXControlsTestAppForIslands/MUXControlsTestAppForIslands.csproj
  test/MUXControlsTestAppForIslands/MUXControlsTestAppForIslands_TemporaryKey.pfx
  test/MUXControlsTestAppForIslands/MainPage.xaml
  test/MUXControlsTestAppForIslands/MainPage.xaml.cs
  test/MUXControlsTestAppForIslands/NavigationViewTestPage.xaml
  test/MUXControlsTestAppForIslands/NavigationViewTestPage.xaml.cs
  test/MUXControlsTestAppForIslands/Package.appxmanifest
  test/MUXControlsTestAppForIslands/Properties/AssemblyInfo.cs
  test/MUXControlsTestAppForIslands/Properties/Default.rd.xml
  test/MUXControlsTestAppForIslands/TestInventory.cs
  test/MUXControlsTestAppForIslands/project.json
  test/MUXControlsTestAppWPF/App.config
  test/MUXControlsTestAppWPF/App.xaml
  test/MUXControlsTestAppWPF/App.xaml.cs
  test/MUXControlsTestAppWPF/MUXControlsTestAppWPF.csproj
  test/MUXControlsTestAppWPF/MainWindow.xaml
  test/MUXControlsTestAppWPF/MainWindow.xaml.cs
  test/MUXControlsTestAppWPF/Properties/AssemblyInfo.cs
  test/MUXControlsTestAppWPF/Properties/Resources.Designer.cs
  test/MUXControlsTestAppWPF/Properties/Resources.resx
  test/MUXControlsTestAppWPF/Properties/Settings.Designer.cs
  test/MUXControlsTestAppWPF/Properties/Settings.settings
  test/MUXControlsTestAppWPF/packages.config
  test/MUXControlsTestAppWPFPackage/Images/LockScreenLogo.scale-200.png
  test/MUXControlsTestAppWPFPackage/Images/Square150x150Logo.scale-200.png
  test/MUXControlsTestAppWPFPackage/Images/Square44x44Logo.scale-200.png
  test/MUXControlsTestAppWPFPackage/Images/Square44x44Logo.targetsize-24_altform-unplated.png
  test/MUXControlsTestAppWPFPackage/Images/StoreLogo.png
  test/MUXControlsTestAppWPFPackage/Images/Wide310x150Logo.scale-200.png
  test/MUXControlsTestAppWPFPackage/MUXControlsTestAppWPFPackage.wapproj
  test/MUXControlsTestAppWPFPackage/MUXControlsTestAppWPFPackage_TemporaryKey.pfx
  test/MUXControlsTestAppWPFPackage/Package.appxmanifest
  test/MUXControlsTestAppWPFPackage/pri.resfiles
  test/MUXControlsTestAppWPFPackage/priconfig.xml
Labels: area-DevInternal, needs-triage, team-Controls

#1723 Fix repeater holding onto elements
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/ItemsRepeater.cpp
Labels: needs-triage

#1724 Extend the fix for Recycling the focused element to non virtualized layouts
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/ItemsRepeater.cpp
Labels: needs-triage

#1719 RadioButtons layout account for available size.
  dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.cpp
  dev/RadioButtons/ColumnMajorUniformToLargestGridLayout.h
  dev/RadioButtons/InteractionTests/RadioButtonsTestPageElements.cs
  dev/RadioButtons/InteractionTests/RadioButtonsTests.cs
  dev/RadioButtons/TestUI/RadioButtonsPage.xaml
  dev/RadioButtons/TestUI/RadioButtonsPage.xaml.cs
Labels: area-RadioButtons, needs-cherrypicktorelease, release note, team-Controls

#1730 Upgrade MUXC project to latest C++/WinRT
  dev/Generated/FontIconSource.properties.cpp
  dev/IconSource/IconSource.idl
  dev/PullToRefresh/RefreshContainer/RefreshContainer.cpp
  dev/PullToRefresh/RefreshVisualizer/RefreshVisualizer.cpp
  dev/PullToRefresh/RefreshVisualizer/RefreshVisualizerEventArgs.cpp
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTipClosingEventArgs.cpp
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/packages.config
Labels: area-DevInternal, team-Controls

#1661 Re-enable code analysis and fix some CppCoreGuidelines checks
  .editorconfig
  build/PrefastWarnings.ruleset
  dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp
  dev/ColorPicker/ColorChangedEventArgs.h
  dev/Effects/microsoft.ui.composition.effects_impl.h
  dev/Lights/MaterialHelper.cpp
  dev/Lights/RevealHoverLight.h
  dev/MenuBar/MenuBarItem.h
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationViewDisplayModeChangedEventArgs.h
  dev/NavigationView/SplitDataSourceBase.h
  dev/NavigationView/TopNavigationViewDataProvider.cpp
  dev/NavigationView/TopNavigationViewDataProvider.h
  dev/NumberBox/NumberBoxParser.h
  dev/PersonPicture/InitialsGenerator.h
  dev/RadioButtons/RadioButtons.vcxitems.filters
  dev/RatingControl/RatingControl.h
  dev/Repeater/Phaser.h
  dev/Repeater/SelectionNode.h
  dev/Repeater/ViewManager.cpp
  dev/Telemetry/RuntimeProfiler.cpp
  dev/TreeView/TreeViewItem.cpp
  dev/TwoPaneView/DisplayRegionHelper.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/SharedHelpers.cpp
  dev/dll/XamlMetadataProvider.cpp
  dev/inc/CppWinRTHelpers.h
  dev/inc/RoutedEventHelpers.h
  dev/inc/RuntimeClassHelpers.h
  dev/inc/tracker_ref.h
Labels: area-DevInternal, team-Controls

#1729 Enable chk tests
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/CopyFilesToStagingDir.ps1
  dev/CommonManaged/PlatformConfiguration.cs
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  dev/Repeater/APITests/RepeaterTests.cs
  test/IXMPTestApp/Tests/MetadataProviderTests.cs
Labels: area-TestInfrastructure, team-Controls

#1733 Enable the RadioButtons Basic Keyboard Test
  dev/RadioButtons/InteractionTests/RadioButtonsTests.cs
Labels: area-RadioButtons, team-Controls

#1740 Fix ItemsRepeater overwriting DataContext
  dev/Repeater/APITests/Common/DataAsElementElementFactory.cs
  dev/Repeater/APITests/Common/ElementFromElementElementFactory.cs
  dev/Repeater/APITests/Repeater_APITests.projitems
  dev/Repeater/APITests/ViewManagerTests.cs
  dev/Repeater/ViewManager.cpp
Labels: area-ItemsRepeater, team-Controls

#1744 Fix to sizing issue when TabView is aligned left.
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TabView.h
  dev/TabView/TestUI/TabViewSizingPage.xaml
  dev/TabView/TestUI/TabViewSizingPage.xaml.cs
Labels: area-TabView, needs-cherrypicktorelease, team-Controls

#1738 Switch border brush in HC
  dev/NavigationView/NavigationView_rs2_themeresources.xaml
Labels: accessibility, area-NavigationView, area-UIDesign, team-Controls

#1748 Teaching tip (sub)title collapse when empty
  dev/Generated/TeachingTipTestHooks.properties.h
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTipTestHooks.cpp
  dev/TeachingTip/TeachingTipTestHooks.h
  dev/TeachingTip/TeachingTipTestHooks.idl
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: area-TeachingTip, team-Controls

#1750 Bump version in master to 2.4 and keep YYMMDDRRR version out of the release version
  build/AzurePipelinesTemplates/MUX-CreateNugetPackage-Job.yml
  build/MUX-CI.yml
  build/MUX-PGOInstrument.yml
  build/MUX-PR.yml
  build/MUX-Release.yml
  build/NuSpecs/MUXControls-Nuget-FrameworkPackage.props
  build/NuSpecs/build-nupkg.ps1
  dev/inc/BuildMacros.h
  docs/roadmap.md
  tools/PublishSymbols/PublishSymbols.ps1
  version.props
Labels: area-NugetPackage, team-Controls

#1758 Fixing Scroller's RepeatedSnapPoint bug: wrong snapping before first snap point
  dev/Scroller/APITests/ScrollerSnapPointTests.cs
  dev/Scroller/InteractionTests/ScrollerTestsWithInputHelper.cs
  dev/Scroller/ScrollerSnapPoint.cpp
  dev/Scroller/ScrollerSnapPoint.h
  dev/Scroller/TestUI/ScrollerPage.xaml
  dev/Scroller/TestUI/ScrollerPage.xaml.cs
  dev/Scroller/TestUI/ScrollerScrollSnapPointsPage.xaml
  dev/Scroller/TestUI/ScrollerScrollSnapPointsPage.xaml.cs
  dev/Scroller/TestUI/ScrollerZoomSnapPointsPage.xaml
  dev/Scroller/TestUI/ScrollerZoomSnapPointsPage.xaml.cs
  dev/Scroller/TestUI/Scroller_TestUI.projitems
Labels: area-Scrolling, bug

#1762 Fix IsInFrameworkPackage logic
  dev/dll/MUXControlsFactory.cpp
  dev/dll/SharedHelpers.cpp
  dev/dll/dllmain.cpp
  idl/Microsoft.UI.Xaml.idl
Labels: needs-triage

#1770 Disable unreliable test
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
Labels: area-TeachingTip, auto merge, needs-triage, team-Controls

#1753 Add an access key handler to radio buttons
  dev/RadioButtons/InteractionTests/RadioButtonsTests.cs
  dev/RadioButtons/RadioButtons.cpp
  dev/RadioButtons/RadioButtons.h
  dev/RadioButtons/TestUI/RadioButtonsPage.xaml
  test/MUXControls.Test/Common/KeyboardHelper.cs
Labels: area-RadioButtons, team-Controls

#1772 Enable C++/WinRT heap enforcement
  dev/AnimatedVisualPlayer/AnimatedVisualPlayer.h
  dev/Common/LifetimeHandler.h
  dev/ScrollViewer/ScrollBarController.h
  dev/dll/CommandingHelpers.cpp
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: area-DevInternal, team-Controls

#1754 Added more NavigationView tests
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  dev/NavigationView/TestUI/NavigationViewInitPage.xaml
  dev/NavigationView/TestUI/NavigationViewInitPage.xaml.cs
  dev/NavigationView/TestUI/NavigationViewPage.xaml
  dev/NavigationView/TestUI/NavigationViewPage.xaml.cs
Labels: area-NavigationView, team-Controls

#1767 Adjust the focus handler to further future proof the custom focus management.
  dev/RadioButtons/RadioButtons.cpp
Labels: area-RadioButtons, needs-cherrypicktorelease, team-Controls

#1776 Re-enable WINRT_LEAN_AND_MEAN against latest CppWinRT
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/packages.config
  dev/dll/pch.h
Labels: area-DevInternal, team-Controls

#1777 Disabled ScrollBar rounded corners pre RS5
  dev/ScrollBar/ScrollBar_themeresources.xaml
Labels: area-Styling, needs-triage

#1760 API Tests Refactor
  dev/AutoSuggestBox/APITests/AutoSuggestBoxTests.cs
  dev/CalendarView/APITests/CalendarViewTests.cs
  dev/ColorPicker/APITests/ColorPickerTests.cs
  dev/ComboBox/APITests/ComboBoxTests.cs
  dev/CommandBarFlyout/APITests/CommandBarFlyoutTests.cs
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/IconSource/APITests/IconSourceApiTests.cs
  dev/LayoutPanel/APITests/LayoutPanelTests.cs
  dev/Lights/ApiTests/Lights_ApiTests/LightConfigurationTests.cs
  dev/Materials/Acrylic/APITests/AcrylicBrushTests.cs
  dev/Materials/Reveal/APITests/RevealTests.cs
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
  dev/ParallaxView/APITests/ParallaxViewTests.cs
  dev/PersonPicture/APITests/PersonPictureTests.cs
  dev/PullToRefresh/RefreshVisualizer/APITests/RefreshVisualizerTests.cs
  dev/PullToRefresh/ScrollViewerIRefreshInfoProviderAdapter/APITests/ScrollViewerAdapterTests.cs
  dev/RatingControl/APITests/RatingControlTests.cs
  dev/Repeater/APITests/AccessibilityTests.cs
  dev/Repeater/APITests/EffectiveViewportScrollViewerTests.cs
  dev/Repeater/APITests/EffectiveViewportScrollerTests.cs
  dev/Repeater/APITests/ElementAnimatorTests.cs
  dev/Repeater/APITests/FlowLayoutCollectionChangeTests.cs
  dev/Repeater/APITests/FlowLayoutTests.cs
  dev/Repeater/APITests/IndexPathTests.cs
  dev/Repeater/APITests/InspectingDataSourceTests.cs
  dev/Repeater/APITests/ItemTemplateTests.cs
  dev/Repeater/APITests/LayoutTests.cs
  dev/Repeater/APITests/PhasingTests.cs
  dev/Repeater/APITests/RecyclePoolTests.cs
  dev/Repeater/APITests/RepeaterFocusTests.cs
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/APITests/Repeater_APITests.projitems
  dev/Repeater/APITests/SelectionModelTests.cs
  dev/Repeater/APITests/ViewManagerTests.cs
  dev/Repeater/APITests/ViewportTests.cs
  dev/ScrollViewer/APITests/ScrollViewerTests.cs
  dev/Scroller/APITests/ScrollControllerTests.cs
  dev/Scroller/APITests/ScrollerAnchoringTests.cs
  dev/Scroller/APITests/ScrollerBringIntoViewTests.cs
  dev/Scroller/APITests/ScrollerLayoutTests.cs
  dev/Scroller/APITests/ScrollerSnapPointTests.cs
  dev/Scroller/APITests/ScrollerTests.cs
  dev/Scroller/APITests/ScrollerViewChangeTests.cs
  dev/SplitButton/APITests/SplitButtonTests.cs
  dev/SwipeControl/SwipeControl_APITests/SwipeControlTests.cs
  dev/TeachingTip/APITests/TeachingTipTests.cs
  dev/TreeView/APITests/TreeViewTests.cs
  dev/TwoPaneView/APITests/TwoPaneViewTests.cs
  test/MUXControlsTestApp/LeakTests.cs
  test/MUXControlsTestApp/LocalizationTests.cs
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
  test/MUXControlsTestApp/ThemeResourcesTests.cs
  test/MUXControlsTestApp/Utilities/APITestBase.cs
  test/MUXControlsTestApp/Utilities/TestHelpers.cs
Labels: area-DevInternal, team-Controls

#1797 Fix test ItemsRepeater VerifyAnchor
  dev/Repeater/APITests/RepeaterTests.cs
Labels: needs-triage
