Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-07, with the labels that each got.

#967 Add CornerRadiusFilterConverter and fix FlipView corner radius
  dev/Common/Common.vcxitems
  dev/Common/Converters.cpp
  dev/Common/Converters.h
  dev/Common/Converters.idl
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/FlipView/FlipView.vcxitems
  dev/FlipView/FlipView_themeresources.xaml
  dev/FlipView/TestUI/FlipViewPage.xaml
Labels: area-Styling, release note

#922 Update CornerRadius property on NavigationViewItem, PivotHeaderItem and ScrollBar
  dev/CalendarDatePicker/CalendarDatePicker_themeresources.xaml
  dev/CommonStyles/InteractionTests/CommonStylesTests.cs
  dev/CommonStyles/TestUI/CornerRadiusPage.xaml
  dev/NavigationView/NavigationView.vcxitems
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/Pivot/Pivot.vcxitems
  dev/Pivot/Pivot_themeresources.xaml
  dev/ScrollBar/ScrollBar.vcxitems
  dev/ScrollBar/ScrollBar_rs1_themeresources.xaml
  dev/ScrollBar/ScrollBar_rs2_themeresources.xaml
  dev/ScrollBar/ScrollBar_rs3_themeresources.xaml
  dev/ScrollBar/ScrollBar_themeresources.xaml
  dev/ScrollViewer/ScrollViewer.xaml
Labels: area-Styling, auto merge, release note

#978 Set fixed height on NavigationView icon ViewBox
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
Labels: area-NavigationView, release note

#1001 Scroller: Simulating WUX ScrollViewer.ChangeView method in test app
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
Labels: area-Scrolling

#1015 NavigationView: Adding boolean property NavigationView.IsTitleBarAutoPaddingEnabled
  dev/Generated/NavigationView.properties.cpp
  dev/Generated/NavigationView.properties.h
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.idl
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  dev/NavigationView/TestUI/NavigationViewPage.xaml
  dev/NavigationView/TestUI/NavigationViewPage.xaml.cs
  dev/NavigationView/TestUI/NavigationViewTopNavStorePage.xaml
  dev/NavigationView/TestUI/NavigationViewTopNavStorePage.xaml.cs
Labels: area-NavigationView

#1019 disable flaky tests
  dev/Repeater/APITests/ViewManagerTests.cs
Labels: auto merge

#993 Move over ContentDialog template
  MUXControls.sln
  dev/ContentDialog/ContentDialog.vcxitems
  dev/ContentDialog/ContentDialog_themeresources.xaml
  dev/ContentDialog/TestUI/ContentDialogPage.xaml
  dev/ContentDialog/TestUI/ContentDialogPage.xaml.cs
  dev/ContentDialog/TestUI/ContentDialog_TestUI.projitems
  dev/ContentDialog/TestUI/ContentDialog_TestUI.shproj
  test/MUXControlsTestApp/Assets/DefaultIcon.png
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
  test/MUXControlsTestApp/TestInventory.cs
Labels: area-Styling, auto merge

#991 CommandBarFlyout corner radius
  dev/CommandBarFlyout/CommandBarFlyout.xaml
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  test/MUXControlsTestApp/Themes/DisableAnimationsStylesOutsideStore_rs2.xaml
Labels: area-Styling

#1014 Realize a single element even if the repeater is outside the realized range bug being measured
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/StackLayout.cpp
Labels: auto merge

#1033 Fix memory leak because Binding.Source
  dev/NavigationView/NavigationView.cpp
  dev/dll/SharedHelpers.cpp
  dev/inc/SharedHelpers.h
Labels: auto merge, release note

#972 Scroller: Fixing consecutive scroll/zoom operations' result
  dev/Scroller/APITests/ScrollControllerTests.cs
  dev/Scroller/APITests/ScrollerAnchoringTests.cs
  dev/Scroller/APITests/ScrollerBringIntoViewTests.cs
  dev/Scroller/APITests/ScrollerLayoutTests.cs
  dev/Scroller/APITests/ScrollerTests.cs
  dev/Scroller/APITests/ScrollerViewChangeTests.cs
  dev/Scroller/InteractionTrackerAsyncOperation.h
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
Labels: area-Scrolling, bug

#1023 ComboBox CornerRadius
  MUXControls.sln
  dev/ComboBox/APITests/ComboBoxTests.cs
  dev/ComboBox/APITests/ComboBox_APITests.projitems
  dev/ComboBox/APITests/ComboBox_APITests.shproj
  dev/ComboBox/ComboBox.vcxitems
  dev/ComboBox/ComboBoxHelper.cpp
  dev/ComboBox/ComboBoxHelper.h
  dev/ComboBox/ComboBoxHelper.idl
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/ComboBox/TestUI/ComboBoxPage.xaml
  dev/Common/Converters.cpp
  dev/Common/Converters.h
  dev/CommonStyles/TestUI/CornerRadiusPage.xaml
  dev/Generated/ComboBoxHelper.properties.cpp
  dev/Generated/ComboBoxHelper.properties.h
  dev/inc/CppWinRTIncludes.h
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: area-Styling

#1053 Bring over more templates
  FeatureAreas.props
  MUXControls.sln
  dev/CalendarView/CalendarView.vcxitems
  dev/CalendarView/CalendarView_themeresources.xaml
  dev/CalendarView/TestUI/CalendarViewPage.xaml
  dev/CalendarView/TestUI/CalendarViewPage.xaml.cs
  dev/CalendarView/TestUI/CalendarView_TestUI.projitems
  dev/CalendarView/TestUI/CalendarView_TestUI.shproj
  dev/CommonStyles/Button_themeresources.xaml
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/ToggleButton_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_rs1_themeresources.xaml
  dev/SplitView/SplitView.vcxitems
  dev/SplitView/SplitView_themeresources.xaml
  dev/SplitView/TestUI/SplitViewPage.xaml
  dev/SplitView/TestUI/SplitViewPage.xaml.cs
  dev/SplitView/TestUI/SplitView_TestUI.projitems
  dev/SplitView/TestUI/SplitView_TestUI.shproj
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControlsTestApp/Assets/CalendarView.png
  test/MUXControlsTestApp/Assets/SplitView.png
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
  tools/GenerateNewControlProject.ps1
  tools/GenerateNewControlProjectFiles/NEWCONTROL.vcxitems
Labels: area-Styling

#1060 Fix incremental build when updating cpp files
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: auto merge

#1059 Fix TintLuminosityOpacity crash by removing const_cast and passing by non-const
  dev/Generated/AcrylicBrush.properties.cpp
  dev/Generated/NavigationView.properties.cpp
  dev/Generated/ScrollViewer.properties.cpp
  dev/Generated/Scroller.properties.cpp
  dev/Materials/Acrylic/AcrylicBrush.cpp
  dev/Materials/Acrylic/AcrylicBrush.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/packages.config
  test/IXMPTestApp/MSTest/IXMPTestApp.csproj
  test/IXMPTestApp/TAEF/project.json
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
  test/MUXControlsTestApp/TAEF/project.json
  tools/CustomTasks/DependencyPropertyCodeGen.cs
  tools/CustomTasks/NuSpecs/MUXCustomBuildTasks.nuspec
  tools/CustomTasks/Properties/AssemblyInfo.cs
Labels: release note

#1063 fix build warning
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: auto merge

#1066 remove dead code
  dev/PersonPicture/LegacySource/PersonPicture.cpp
  dev/PersonPicture/LegacySource/PersonPicture.h
  dev/PersonPicture/LegacySource/PersonPictureAutomationPeer.cpp
  dev/PersonPicture/LegacySource/PersonPictureAutomationPeer.h
  dev/PersonPicture/LegacySource/Utilities/InitialsGenerator.cpp
  dev/PersonPicture/LegacySource/Utilities/InitialsGenerator.h
  dev/PersonPicture/LegacySource/Utilities/ResourceAccessor.cpp
  dev/PersonPicture/LegacySource/Utilities/ResourceAccessor.h
  dev/PersonPicture/LegacySource/Utilities/Utils.cpp
  dev/PersonPicture/LegacySource/Utilities/Utils.h
Labels: auto merge

#1072 Scroller: Adding support for ContentOrientation.Both
  dev/ScrollViewer/TestUI/ScrollViewerBlankPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerBlankPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewer_TestUI.projitems
  dev/Scroller/APITests/ScrollerLayoutTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/Scroller.idl
  dev/Scroller/ScrollerTestHooks.cpp
  dev/Scroller/ScrollerTestHooks.h
  dev/Scroller/ScrollerTestHooks.idl
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
Labels: area-Scrolling

#1083 NavigationView: Showing the PaneHeader and PaneTitle even when the PaneToggleButton is hidden
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/NavigationView/TestUI/NavigationViewCustomThemeResourcesPage.xaml
  dev/NavigationView/TestUI/NavigationViewCustomThemeResourcesPage.xaml.cs
  dev/NavigationView/TestUI/NavigationViewPage.xaml
  dev/NavigationView/TestUI/NavigationViewPage.xaml.cs
Labels: area-NavigationView

#1070 AutoSuggestBox CornerRadius
  MUXControls.sln
  dev/AutoSuggestBox/APITests/AutoSuggestBoxTests.cs
  dev/AutoSuggestBox/APITests/AutoSuggestBox_APITests.projitems
  dev/AutoSuggestBox/APITests/AutoSuggestBox_APITests.shproj
  dev/AutoSuggestBox/AutoSuggestBox.vcxitems
  dev/AutoSuggestBox/AutoSuggestBoxHelper.cpp
  dev/AutoSuggestBox/AutoSuggestBoxHelper.h
  dev/AutoSuggestBox/AutoSuggestBoxHelper.idl
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/ComboBox/ComboBoxHelper.cpp
  dev/Generated/AutoSuggestBoxHelper.properties.cpp
  dev/Generated/AutoSuggestBoxHelper.properties.h
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: area-Styling

#1078 Add static resource for corner radius
  MUXControls.sln
  dev/AutoSuggestBox/AutoSuggestBoxHelper.cpp
  dev/AutoSuggestBox/AutoSuggestBoxHelper.h
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/CalendarDatePicker/CalendarDatePicker_themeresources.xaml
  dev/CalendarView/CalendarView_themeresources.xaml
  dev/CheckBox/CheckBox_themeresources.xaml
  dev/ColorPicker/ColorPicker.xaml
  dev/ColorPicker/ColorSpectrum.xaml
  dev/ComboBox/ComboBoxHelper.cpp
  dev/ComboBox/ComboBoxHelper.h
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/ComboBox/TestUI/ComboBoxPage.xaml
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/CommandBarFlyout.xaml
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  dev/CommonStyles/Button_themeresources.xaml
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/CornerRadius_themeresources.xaml
  dev/CommonStyles/FlyoutPresenter_themeresources.xaml
  dev/CommonStyles/PasswordBox_themeresources.xaml
  dev/CommonStyles/RichEditBox_themeresources.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
  dev/CommonStyles/ToggleButton_themeresources.xaml
  dev/ContentDialog/ContentDialog_themeresources.xaml
  dev/ContentDialog/TestUI/ContentDialogPage.xaml.cs
  dev/DatePicker/DatePicker_themeresources.xaml
  dev/DatePicker/DateTimePickerFlyout_themeresources.xaml
  dev/DropDownButton/DropDownButton.xaml
  dev/DropDownButton/DropDownButton_rs1.xaml
  dev/FlipView/FlipView_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_19h1_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_rs1_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_rs5_themeresources.xaml
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/Pivot/Pivot_themeresources.xaml
  dev/ScrollBar/ScrollBar_themeresources.xaml
  dev/ScrollViewer/ScrollViewer.xaml
  dev/Slider/Slider_themeresources.xaml
  dev/SplitButton/SplitButton.xaml
  dev/SplitButton/SplitButton_rs1.xaml
  dev/TeachingTip/TeachingTip.xaml
  dev/TimePicker/TimePicker_themeresources.xaml
  dev/ToolTip/ToolTip_rs1_themeresources.xaml
  dev/ToolTip/ToolTip_rs5_themeresources.xaml
  dev/TreeView/TreeView.vcxitems
  dev/TreeView/TreeViewItem.xaml
  dev/TreeView/TreeViewItem_rs1.xaml
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: area-Styling

#1112 Minor feedback for a previous code review
  dev/ColorPicker/ColorPicker.cpp
  dev/dll/XamlMetadataProviderGenerated.h
Labels: auto merge

#243 TreeView selection APIs
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TestUI/ExplorerItem.cs
  dev/TreeView/TestUI/ExplorerItemTemplateSelector.cs
  dev/TreeView/TestUI/TreeViewPage.xaml
  dev/TreeView/TestUI/TreeViewPage.xaml.cs
  dev/TreeView/TestUI/TreeView_TestUI.projitems
  dev/TreeView/TreeView.cpp
  dev/TreeView/TreeView.h
  dev/TreeView/TreeView.idl
  dev/TreeView/TreeView.vcxitems
  dev/TreeView/TreeViewItem.cpp
  dev/TreeView/TreeViewItem.h
  dev/TreeView/TreeViewItemAutomationPeer.cpp
  dev/TreeView/TreeViewList.cpp
  dev/TreeView/TreeViewList.h
  dev/TreeView/TreeViewNode.cpp
  dev/TreeView/TreeView_rs5_themeresources.xaml
  dev/TreeView/ViewModel.cpp
  dev/TreeView/ViewModel.h
  test/MUXControlsTestApp/Assets/file.png
  test/MUXControlsTestApp/Assets/folder.png
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
Labels: area-TreeView, feature proposal, release note

#1116 Fixing AutoSuggestBox list for April 2018 Update and earlier OS versions
  MUXControls.sln
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/AutoSuggestBox/InteractionTests/AutoSuggestBoxTests.cs
  dev/AutoSuggestBox/InteractionTests/AutoSuggestBox_InteractionTests.projitems
  dev/AutoSuggestBox/InteractionTests/AutoSuggestBox_InteractionTests.shproj
  dev/AutoSuggestBox/TestUI/AutoSuggestBoxPage.xaml
  dev/AutoSuggestBox/TestUI/AutoSuggestBoxPage.xaml.cs
  test/MUXControls.Test/MUXControls.Test.Shared.targets
Labels: release note
