Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-05, with the labels that each got.

#637 Fix TeachingTip theming when page has RequestedTheme override
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TeachingTipTestHooks.cpp
  dev/TeachingTip/TeachingTipTestHooks.h
  dev/TeachingTip/TeachingTipTestHooks.idl
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
  test/MUXControls.Test/Common/FindElement.cs
Labels: auto merge

#500 Implement TreeViewItemDataAutomationPeer to fix treeviewitem narrator issue
  dev/TreeView/TreeView.vcxitems
  dev/TreeView/TreeViewAutomationPeers.idl
  dev/TreeView/TreeViewItemDataAutomationPeer.cpp
  dev/TreeView/TreeViewItemDataAutomationPeer.h
  dev/TreeView/TreeViewListAutomationPeer.cpp
  dev/inc/CppWinRTIncludes.h
Labels: release note

#656 Make $BuildOutput\release to $BuildOutput\$BuildFlavor
  build/NuSpecs/build-nupkg.ps1
Labels: auto merge

#652 NavView Hamburger btn and header overlap on launch in minimal mode
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  dev/NavigationView/TestUI/NavigationViewCaseBundle.xaml
  dev/NavigationView/TestUI/NavigationViewCaseBundle.xaml.cs
  dev/NavigationView/TestUI/NavigationViewMinimalPage.xaml
  dev/NavigationView/TestUI/NavigationViewMinimalPage.xaml.cs
  dev/NavigationView/TestUI/NavigationView_TestUI.projitems
Labels: area-NavigationView, needs-cherrypicktorelease

#650 Fix TeachingTip test reliability
  RunTests.ps1
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTipAutomationPeer.cpp
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/inc/CppWinRTHelpers.h
  dev/inc/CppWinRTIncludes.h
  test/MUXControls.Test/Common/InputHelper.cs
  test/MUXControlsTestApp/TAEF/MUXControlsTestApp.TAEF.csproj
Labels: needs-cherrypicktorelease

#619 TeachingTips display correctly when IsOpen is set early.
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/pch.h
  dev/inc/CppWinRTIncludes.h
  dev/inc/gsl/ReadMe.md
  dev/inc/gsl/gsl
  dev/inc/gsl/gsl_algorithm
  dev/inc/gsl/gsl_assert
  dev/inc/gsl/gsl_byte
  dev/inc/gsl/gsl_util
  dev/inc/gsl/multi_span
  dev/inc/gsl/pointers
  dev/inc/gsl/span
  dev/inc/gsl/string_span
Labels: area-TeachingTip, auto merge, needs-cherrypicktorelease

#671 Test case fixes to try to improve test pass reliability
  dev/CommandBarFlyout/InteractionTests/TextCommandBarFlyoutTests.cs
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  dev/TreeView/InteractionTests/TreeViewTests.cs
  test/MUXControls.Test/Common/AppsTestExtensions.cs
  test/MUXControls.Test/Infra/Application.cs
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
Labels: area-Commanding, area-TestInfrastructure, area-TreeView, test issue

#592 Adding support for mouse-wheel scrolling and zooming while mandatory irregular or repeated snap points are applied
  dev/Scroller/InteractionTests/ScrollerTestsWithInputHelper.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/ScrollerSnapPoint.cpp
  dev/Scroller/ScrollerSnapPoint.h
  dev/Scroller/ScrollerTrace.h
  dev/Scroller/SnapPointWrapper.cpp
  dev/Scroller/SnapPointWrapper.h
Labels: area-Scrolling

#669 Triggering rasterization of Scroller Content after zoom operation on RS5+
  dev/Generated/ScrollerTestHooks.properties.cpp
  dev/Generated/ScrollerTestHooks.properties.h
  dev/Scroller/APITests/ScrollerAnchoringTests.cs
  dev/Scroller/APITests/ScrollerTests.cs
  dev/Scroller/APITests/ScrollerViewChangeTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/Scroller.vcxitems
  dev/Scroller/ScrollerTestHooks.cpp
  dev/Scroller/ScrollerTestHooks.h
  dev/Scroller/ScrollerTestHooks.idl
  dev/Scroller/ScrollerTestHooksExpressionAnimationStatusChangedEventArgs.cpp
  dev/Scroller/ScrollerTestHooksExpressionAnimationStatusChangedEventArgs.h
  dev/Scroller/TestUI/ScrollerChainingAndRailingPage.xaml
  dev/Scroller/TestUI/ScrollerTestHooksHelper.cs
Labels: area-Scrolling

#713 Test regression fix for ApiTests.RepeaterTests.ViewportTests/EffectiveViewportScrollerTests following Scroller fix
  dev/Repeater/APITests/EffectiveViewportScrollerTests.cs
  dev/Repeater/APITests/ViewportTests.cs
Labels: area-Scrolling

#748 Scroller fix for Issue #561: Missing content-layout-offset updates in far-anchoring + overpanning modes
  dev/Scroller/InteractionTests/ScrollerTestsWithInputHelper.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/TestUI/ScrollersWithSimpleContentsPage.xaml
  dev/Scroller/TestUI/ScrollersWithSimpleContentsPage.xaml.cs
Labels: area-Scrolling

#745 Enable file version info in build
  MUXControls.sln
  build/AzurePipelinesTemplates/MUX-BuildProject-Steps.yml
  build/FrameworkPackage/MakeFrameworkPackage.ps1
  build/NuSpecs/build-nupkg.ps1
  custom.props
  dev/dll/Microsoft.UI.Xaml.rc
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
  dev/dll/version.h
  tools/PublishSymbols/PublishSymbols.ps1
  version.props
Labels: needs-cherrypicktorelease, release note

#749 Update NuGet and framework tests artifact name
  build/AzurePipelinesTemplates/MUX-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-NugetReleaseTest-Job.yml
  build/AzurePipelinesTemplates/MUX-PublishProjectOutput-Steps.yml
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/Helix/PrepareHelixPayload.ps1
  build/MUX-CI.yml
Labels: area-TestInfrastructure

#753 Splitting up test processing from the test job file
  build/AzurePipelinesTemplates/MUX-ProcessTestResults-Job.yml
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/MUX-CI.yml
  build/RunHelixTests.yml
Labels: auto merge

#770 Fix a Teaching Tip Crash in unpackaged apps
  dev/TeachingTip/TeachingTip.cpp
Labels: release note

#773 Update project url to be directly pointing at github
  build/NuSpecs/MUXControls.nuspec
  build/NuSpecs/MUXControlsFrameworkPackage.nuspec
Labels: needs-cherrypicktorelease

#772 Use latest available sdk version when making framework package
  build/FrameworkPackage/MakeFrameworkPackage.ps1
  build/MUX-Release.yml
Labels: needs-cherrypicktorelease

#781 Add wack test to release pipeline
  build/AzurePipelinesTemplates/MUX-WACKTests-Job.yml
  build/MUX-Release.yml
Labels: area-TestInfrastructure
