Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-06, with the labels that each got.

#568 Allow TeachingTip to reposition when the window size changes
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
  dev/inc/CppWinRTHelpers.h
Labels: area-TeachingTip

#805 Update up/down arrow keys' behavior for CommandBarFlyoutCommandBar
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
Labels: area-Commanding

#813 Minor spelling fixes
  docs/roadmap.md
Labels: auto merge

#787 Animate ScrollViewer's view when navigating with gamepad
  dev/ScrollViewer/InteractionTests/ScrollViewerTestsWithInputHelper.cs
  dev/ScrollViewer/ScrollViewer.cpp
  dev/ScrollViewer/ScrollViewer.h
  dev/ScrollViewer/ScrollViewer.vcxitems
  dev/ScrollViewer/ScrollViewerBringIntoViewOperation.cpp
  dev/ScrollViewer/ScrollViewerBringIntoViewOperation.h
  dev/ScrollViewer/TestUI/ScrollViewerKeyboardAndGamepadNavigationPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerKeyboardAndGamepadNavigationPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewer_TestUI.projitems
  dev/ScrollViewer/TestUI/ScrollViewersWithSimpleContentsPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewersWithSimpleContentsPage.xaml.cs
  dev/Telemetry/TraceLogging.h
Labels: area-Scrolling

#823 Switch final_release to be noexcept
  dev/inc/RuntimeClassHelpers.h
Labels: auto merge

#731 ScrollViewer supports UISettings' AutoHideScrollBars property
  build/Install-WindowsSdkISO.ps1
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.h
  dev/ScrollViewer/APITests/ScrollViewerTests.cs
  dev/ScrollViewer/ScrollBarController.cpp
  dev/ScrollViewer/ScrollViewer.cpp
  dev/ScrollViewer/ScrollViewer.h
  dev/ScrollViewer/ScrollViewer.vcxitems
  dev/ScrollViewer/ScrollViewer.xaml
  dev/ScrollViewer/ScrollViewerTestHooks.cpp
  dev/ScrollViewer/ScrollViewerTestHooks.h
  dev/ScrollViewer/ScrollViewerTestHooks.idl
  dev/ScrollViewer/ScrollViewer_rs1_themeresources.xaml
  dev/ScrollViewer/ScrollViewer_rs3_themeresources.xaml
  dev/ScrollViewer/ScrollViewer_rs4_themeresources.xaml
  dev/ScrollViewer/ScrollViewer_themeresources.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerTestHooksHelper.cs
  dev/ScrollViewer/TestUI/ScrollViewer_TestUI.projitems
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
  dev/inc/RegUtil.h
  dev/inc/SharedHelpers.h
Labels: area-Scrolling

#854 Enabling a non-animated version of NestedRepeaterWithDataTemplateScenario
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/ItemsRepeaterScrollHost.cpp
  dev/Repeater/RepeaterTrace.h
  dev/TestHooks/MUXControlsTestHooks.cpp
Labels: area-ItemsRepeater, area-Scrolling

#846 fix for uniformgrid property changed handler
  dev/Repeater/APITests/FlowLayoutTests.cs
  dev/Repeater/UniformGridLayout.cpp
Labels: release note

#752 Teaching Tip Fixes
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: area-TeachingTip

#850 Adding Scroller/ScrollViewer's AnimationMode.Auto enum value
  dev/ScrollViewer/InteractionTests/ScrollViewerTestsWithInputHelper.cs
  dev/ScrollViewer/ScrollBarController.cpp
  dev/ScrollViewer/ScrollBarController.h
  dev/ScrollViewer/ScrollViewer.cpp
  dev/ScrollViewer/ScrollViewer.h
  dev/ScrollViewer/TestUI/ScrollViewersWithSimpleContentsPage.xaml.cs
  dev/Scroller/APITests/ScrollControllerTests.cs
  dev/Scroller/APITests/ScrollerLayoutTests.cs
  dev/Scroller/APITests/ScrollerViewChangeTests.cs
  dev/Scroller/ScrollOptions.h
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/Scroller.idl
  dev/Scroller/ScrollerTestHooks.cpp
  dev/Scroller/ScrollerTestHooks.h
  dev/Scroller/ScrollerTestHooks.idl
  dev/Scroller/ScrollerTypeLogging.cpp
  dev/Scroller/TestUI/BiDirectionalScrollController.cs
  dev/Scroller/TestUI/CompositionScrollController.cs
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerSnapPointsPage.xaml.cs
  dev/Scroller/TestUI/ScrollerStackPanelAnchoringPage.xaml.cs
  dev/Scroller/TestUI/ScrollerTestHooksHelper.cs
  dev/Scroller/ZoomOptions.h
Labels: area-Scrolling

#865 Fix TreeView root node ItemsSource syncing
  dev/TreeView/APITests/TreeViewTests.cs
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TestUI/TreeViewPage.xaml
  dev/TreeView/TestUI/TreeViewPage.xaml.cs
  dev/TreeView/TreeView.cpp
  dev/TreeView/TreeViewNode.cpp
  dev/TreeView/TreeViewNode.h
Labels: area-TreeView, auto merge

#870 Scroller: Adding consumption of Control Panel's WheelScrollLines/WheelScrollChars settings on RS4-
  dev/Scroller/InteractionTests/ScrollerTestsBase.cs
  dev/Scroller/InteractionTests/ScrollerTestsWithInputHelper.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/ScrollerTestHooks.cpp
  dev/Scroller/ScrollerTestHooks.h
  dev/Scroller/ScrollerTestHooks.idl
  dev/Scroller/TestUI/ScrollerPage.xaml
  dev/Scroller/TestUI/ScrollerPage.xaml.cs
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
  dev/dll/RegUtil.cpp
  dev/inc/RegUtil.h
Labels: area-Scrolling

#893 Bring over FlyoutPresenter template
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/FlyoutPresenter_themeresources.xaml
Labels: area-Styling

#903 Move templates to MUX for future corner radius changes
  MUXControls.sln
  dev/ComboBox/ComboBox.vcxitems
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/ComboBox/TestUI/ComboBoxPage.xaml
  dev/ComboBox/TestUI/ComboBoxPage.xaml.cs
  dev/ComboBox/TestUI/ComboBox_TestUI.projitems
  dev/ComboBox/TestUI/ComboBox_TestUI.shproj
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/FlyoutPresenter_themeresources.xaml
  dev/CommonStyles/TestUI/CornerRadiusPage.xaml
  dev/FlipView/FlipView.vcxitems
  dev/FlipView/FlipViewItem_themeresources.xaml
  dev/FlipView/FlipView_themeresources.xaml
  dev/FlipView/TestUI/FlipViewPage.xaml
  dev/FlipView/TestUI/FlipViewPage.xaml.cs
  dev/FlipView/TestUI/FlipView_TestUI.projitems
  dev/FlipView/TestUI/FlipView_TestUI.shproj
  dev/Pivot/Pivot.vcxitems
  dev/Pivot/Pivot_themeresources.xaml
  dev/Pivot/TestUI/PivotPage.xaml
  dev/Pivot/TestUI/PivotPage.xaml.cs
  dev/Pivot/TestUI/Pivot_TestUI.projitems
  dev/Pivot/TestUI/Pivot_TestUI.shproj
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
  test/MUXControlsTestApp/TestInventory.cs
Labels: area-Styling

#923 Move ScrollBar template to MUX
  MUXControls.sln
  dev/ScrollBar/ScrollBar.vcxitems
  dev/ScrollBar/ScrollBar_rs1_themeresources.xaml
  dev/ScrollBar/ScrollBar_rs2_themeresources.xaml
  dev/ScrollBar/ScrollBar_rs3_themeresources.xaml
  dev/ScrollBar/ScrollBar_rs4_themeresources.xaml
  dev/ScrollBar/TestUI/ScrollBarPage.xaml
  dev/ScrollBar/TestUI/ScrollBarPage.xaml.cs
  dev/ScrollBar/TestUI/ScrollBar_TestUI.projitems
  dev/ScrollBar/TestUI/ScrollBar_TestUI.shproj
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
  test/MUXControlsTestApp/TestInventory.cs
Labels: area-Styling

#882 Fixing Scroller.Content flicker during rasterization for Issue #541.
  dev/Scroller/APITests/ScrollerViewChangeTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
Labels: area-Scrolling, bug, release note

#909 Add assets to test inventory for new control pages
  test/MUXControlsTestApp/Assets/ComboBox.png
  test/MUXControlsTestApp/Assets/FlipView.png
  test/MUXControlsTestApp/Assets/Pivot.png
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
  test/MUXControlsTestApp/TestInventory.cs
Labels: auto merge

#926 Avoid reset of containers when anchor element is replaced in ItemsRepeater
  dev/Repeater/APITests/FlowLayoutCollectionChangeTests.cs
  dev/Repeater/ElementManager.cpp
  dev/Repeater/UniformGridLayout.cpp
  dev/Repeater/UniformGridLayoutState.cpp
  dev/Repeater/UniformGridLayoutState.h
Labels: release note

#949 Fix RunLocWorkflow.ps1 so it finds MSBuild for VS2019
  build/Localization/RunLocWorkflow.ps1
  tools/VSTSRunLocWorkflow.cmd
Labels: auto merge

#894 Scroller: Fixing layout of partially stretched Content
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerDynamicPage.xaml.cs
  dev/Scroller/APITests/ScrollerLayoutTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
Labels: area-Scrolling, bug

#969 Add slider to CornerRadiusPage that allows changing all controls styles
  dev/CommonStyles/TestUI/CornerRadiusPage.xaml
  dev/CommonStyles/TestUI/CornerRadiusPage.xaml.cs
Labels: auto merge
