Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-03, with the labels that each got.

#364 Fix bad vsm setter for IconBorder.Child
  dev/Generated/TeachingTipTemplateSettings.properties.cpp
  dev/Generated/TeachingTipTemplateSettings.properties.h
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.idl
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
Labels: area-TeachingTip

#359 Fix NavigationView.IsPaneVisible
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
Labels: area-NavigationView, auto merge

#379 Docs: Add information about auto merge label
  docs/contribution_workflow.md
Labels: auto merge

#326 Add Teaching tip shadow
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
  dev/TestHooks/TeachingTipTestHooks.cpp
  dev/TestHooks/TeachingTipTestHooks.h
  dev/TestHooks/TeachingTipTestHooks.idl
Labels: area-TeachingTip

#372 Adding snap points support to bring-into-view contributions
  dev/Scroller/APITests/ScrollerBringIntoViewTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/Scroller.idl
  dev/Scroller/ScrollerBringingIntoViewEventArgs.cpp
  dev/Scroller/ScrollerBringingIntoViewEventArgs.h
  dev/Scroller/TestUI/ScrollerBringIntoViewPage.xaml
  dev/Scroller/TestUI/ScrollerBringIntoViewPage.xaml.cs
Labels: area-Scrolling

#358 Switch PersonPicture control to use VSM to change FontFamily/Text for visual states
  dev/Generated/MetadataSummary.cs
  dev/Generated/PersonPicture.properties.cpp
  dev/Generated/PersonPicture.properties.h
  dev/Generated/PersonPictureTemplateSettings.properties.cpp
  dev/Generated/PersonPictureTemplateSettings.properties.h
  dev/PersonPicture/APITests/PersonPictureTests.cs
  dev/PersonPicture/PersonPicture.cpp
  dev/PersonPicture/PersonPicture.h
  dev/PersonPicture/PersonPicture.idl
  dev/PersonPicture/PersonPicture.vcxitems
  dev/PersonPicture/PersonPicture.xaml
  dev/PersonPicture/PersonPictureTemplateSettings.h
  dev/dll/XamlMetadataProviderGenerated.tt
Labels: auto merge

#391 Allow TeachingTip's to be defined in resource dictionaries or the visual tree.
  build/Localization/Settings/LocConfig.xml
  dev/ResourceHelper/ResourceAccessor.h
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/Strings/en-us/Resources.resw
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.vcxitems
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: area-TeachingTip

#401 SplitButton - add TemplateBinding for content alignment properties
  dev/SplitButton/SplitButton.xaml
  dev/SplitButton/SplitButton_rs1.xaml
  dev/SplitButton/TestUI/SplitButtonPage.xaml
Labels: auto merge

#402 TeachingTip: Change the Attach property to a Target property
  dev/Generated/MetadataSummary.cs
  dev/Generated/TeachingTip.properties.cpp
  dev/Generated/TeachingTip.properties.h
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.idl
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: area-TeachingTip

#384 Scroller snap points updates
  dev/Scroller/APITests/ScrollerBringIntoViewTests.cs
  dev/Scroller/APITests/ScrollerSnapPointTests.cs
  dev/Scroller/InteractionTests/ScrollerTestsWithInputHelper.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/ScrollerPrimitives.idl
  dev/Scroller/ScrollerSnapPoint.cpp
  dev/Scroller/ScrollerSnapPoint.h
  dev/Scroller/TestUI/ScrollerBringIntoViewPage.xaml.cs
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
  dev/Scroller/TestUI/ScrollerSnapPointsPage.xaml
  dev/Scroller/TestUI/ScrollerSnapPointsPage.xaml.cs
  dev/TestHooks/ScrollerTestHooks.cpp
  dev/TestHooks/ScrollerTestHooks.h
  dev/TestHooks/ScrollerTestHooks.idl
  dev/dll/pch.h
  test/MUXControlsTestAppWPFPackage/Package.appxmanifest
Labels: area-Scrolling

#126 Support visualtree verification for Controls
  MUXControls.sln
  dev/CommonManaged/PlatformConfiguration.cs
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/CommonStyles/APITests/CommonStyles_APITests.projitems
  dev/CommonStyles/APITests/CommonStyles_APITests.shproj
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
  test/MUXControlsTestApp/MSTest/Package.appxmanifest
  test/MUXControlsTestApp/MSTest/project.json
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
  test/MUXControlsTestApp/TAEF/Package.VS.appxmanifest
  test/MUXControlsTestApp/TAEF/project.json
  test/MUXControlsTestApp/VisualTreeTestHelper.cs
  test/MUXControlsTestApp/master/VerifyVisualTreeExampleForLightTheme_Light-7.xml
  test/MUXControlsTestApp/master/VerifyVisualTreeExampleLoadAndVerifyForAllThemes_Dark-7.xml
  test/MUXControlsTestApp/master/VerifyVisualTreeExampleLoadAndVerifyForAllThemes_Light-7.xml
  test/MUXControlsTestApp/master/VerifyVisualTreeExampleLoadAndVerifyForDarkThemeWithCustomName-7.xml
  test/MUXControlsTestApp/master/VerifyVisualTreeExampleWithCustomerFilter-7.xml
  test/MUXControlsTestApp/master/VerifyVisualTreeExampleWithCustomerPropertyValueTranslator-7.xml
  test/MUXControlsTestApp/master/VerifyVisualTreeForAppBarAndAppBarToggleButton-7.xml
  test/TestAppUtils/TestAppUtils.projitems
  test/TestAppUtils/VisualTreeDumper.cs
Labels: auto merge

#438 Fix TreeViewItem left padding
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TreeViewItem.xaml
  dev/TreeView/TreeViewItem_rs1.xaml
Labels: area-TreeView

#437 Add release notes links to readme
  README.md
Labels: auto merge, documentation

#421 Scroller: Adding support for mouse-wheel scrolling on pre-RS5 Windows
  dev/ScrollViewer/TestUI/ScrollViewerPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewerWithRTLFlowDirectionPage.xaml
  dev/ScrollViewer/TestUI/ScrollViewerWithRTLFlowDirectionPage.xaml.cs
  dev/ScrollViewer/TestUI/ScrollViewer_TestUI.projitems
  dev/Scroller/APITests/ScrollerTests.cs
  dev/Scroller/InteractionTests/ScrollerTestsWithInputHelper.cs
  dev/Scroller/OffsetsChangeWithAdditionalVelocity.cpp
  dev/Scroller/OffsetsChangeWithAdditionalVelocity.h
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/TestUI/ScrollerPage.xaml
  dev/Scroller/TestUI/ScrollerPage.xaml.cs
  dev/Scroller/ZoomFactorChangeWithAdditionalVelocity.cpp
  dev/Scroller/ZoomFactorChangeWithAdditionalVelocity.h
  dev/TestHooks/ScrollerTestHooks.cpp
  dev/TestHooks/ScrollerTestHooks.h
  dev/TestHooks/ScrollerTestHooks.idl
  dev/dll/SharedHelpers.cpp
  dev/inc/SharedHelpers.h
Labels: area-Scrolling

#455 Make RadioMenuFlyoutItem public
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem.idl
Labels: auto merge

#400 Run NuGet and framework package tests in CI pipeline
  build/AzurePipelinesTemplates/MUX-CreateNugetPackage-Job.yml
  build/AzurePipelinesTemplates/MUX-NugetReleaseTest-Job.yml
  build/AzurePipelinesTemplates/MUX-PublishProjectOutput-Steps.yml
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/Helix/InstallTestAppDependencies.ps1
  build/Helix/PrepareHelixPayload.ps1
  build/Helix/RunTestsInHelix.proj
  build/Helix/runtests.cmd
  build/MUX-CI.yml
  build/MUX-PR.yml
  build/MUX-Release.yml
  build/RunHelixTests.yml
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/MUXControls.ReleaseTest.Shared.projitems
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/NugetTests.cs
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/NugetTestsCX.cs
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/Properties/MUXControls.ReleaseTest.rd.xml
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/ReleaseTestEnvironment.cs
  test/MUXControlsReleaseTest/NugetPackageTestApp/NugetPackageTestApp.csproj
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/NugetPackageTestAppCX.vcxproj
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/packages.config
Labels: area-TestInfrastructure

#441 Build the manifest activatable class entries for the framework package from the winmd instead of test app manifest
  build/FrameworkPackage/MakeFrameworkPackage.ps1
  tools/Utils.psm1
Labels: release note

#447 Adding support for Center/Far scroll snap points alignments.
  dev/Scroller/APITests/ScrollerSnapPointTests.cs
  dev/Scroller/InteractionTests/ScrollerTestsWithInputHelper.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/ScrollerPrimitives.idl
  dev/Scroller/ScrollerSnapPoint.cpp
  dev/Scroller/ScrollerSnapPoint.h
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
  dev/Scroller/TestUI/ScrollerSnapPointsPage.xaml
  dev/Scroller/TestUI/ScrollerSnapPointsPage.xaml.cs
Labels: area-Scrolling

#473 Close NavView pane when switching from expand mode to compact mode
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  test/MUXControls.Test/Common/KeyboardHelper.cs
Labels: area-NavigationView, auto merge

#472 Move FrameworkPackage generation to post-signing job
  build/AzurePipelinesTemplates/MUX-BuildDevProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-CreateNugetPackage-Job.yml
  build/AzurePipelinesTemplates/MUX-InstallWindowsSDK-Steps.yml
  build/AzurePipelinesTemplates/MUX-MakeFrameworkPackages-Steps.yml
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/FrameworkPackage/MakeFrameworkPackage.ps1
  build/MUX-Release.yml
  tools/MakeAppxHelper.cmd
Labels: auto merge

#485 Remove unused header file
  dev/inc/RuntimeClassHelpers.h
  dev/inc/TypeHelper.h
Labels: auto merge

#456 Provide API to enable compact in app level.
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/CommonStyles/TestUI/CompactPage.xaml
  dev/CommonStyles/TestUI/CompactPage.xaml.cs
  dev/Generated/XamlControlsResources.properties.cpp
  dev/Generated/XamlControlsResources.properties.h
  dev/dll/MUXControlsFactory.cpp
  dev/dll/MUXControlsFactory.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
  dev/dll/ThemeResources.h
  dev/dll/ThemeResourcesFactory.cpp
  dev/dll/ThemeResourcesFactory.h
  dev/dll/XamlControlsResources.cpp
  dev/dll/XamlControlsResources.h
  dev/dll/XamlMetadataProviderGenerated.tt
  idl/Microsoft.UI.Xaml.idl
  test/MUXControlsTestApp/App.xaml
Labels: auto merge, release note

#469 TeachingTip Keyboarding and Accessibility
  dev/Generated/MetadataSummary.cs
  dev/ResourceHelper/ResourceAccessor.h
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/Strings/en-us/Resources.resw
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TeachingTipAutomationPeer.cpp
  dev/TeachingTip/TeachingTipAutomationPeer.h
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
  test/MUXControls.Test/Common/KeyboardHelper.cs
Labels: auto merge, release note

#489 Support incremental compilation for xaml file change
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: auto merge

#480 Add the ShouldConstrainToRootBounds API and adjust the placement algorithm
  dev/Generated/TeachingTip.properties.cpp
  dev/Generated/TeachingTip.properties.h
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.idl
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
  dev/TestHooks/TeachingTipTestHooks.cpp
  dev/TestHooks/TeachingTipTestHooks.h
  dev/TestHooks/TeachingTipTestHooks.idl
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
  dev/inc/enum_array.h
  dev/inc/enum_vector.h
Labels: area-TeachingTip

#436 A follow up task on Support visualtree verification for Controls (#126)
  dev/CommonStyles/APITests/CommonStylesTests.cs
  test/MUXControlsTestApp/VisualTreeTestHelper.cs
  test/TestAppUtils/VisualTreeDumper.cs
Labels: auto merge

#495 PlacementMode API
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.idl
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
Labels: area-TeachingTip, auto merge

#505 Make automation peer public, use popup3 cast instead of 19h1 check
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTipAutomationPeer.idl
Labels: area-TeachingTip, auto merge
