Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-08, with the labels that each got.

#1120 Fixing the test number check for MUX-Release
  build/MUX-Release.yml
Labels: auto merge

#1121 Fix NavView VisualState for pane closing
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
Labels: area-NavigationView

#990 Fix issue where TeachingTip's background is not correct for LightDismiss
  dev/TeachingTip/APITests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
Labels: release note

#1107 Update nuget packages and fix some build warnings
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/IXMPTestApp/MSTest/IXMPTestApp.csproj
  test/IXMPTestApp/MSTest/project.json
  test/IXMPTestApp/TAEF/project.json
  test/MUXControls.Test/MSTest/MUXControls.Test.csproj
  test/MUXControlsAdhocApp/MUXControlsAdhocApp.csproj
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/MSTest/MUXControls.ReleaseTest.csproj
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/TAEF/MUXControls.ReleaseTest.TAEF.csproj
  test/MUXControlsReleaseTest/NugetPackageTestApp/NugetPackageTestApp.csproj
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/NugetPackageTestAppCX.vcxproj
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/packages.config
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
  test/MUXControlsTestApp/MSTest/project.json
  test/MUXControlsTestApp/TAEF/project.json
  test/MUXControlsTestAppForIslands/project.json
  test/MUXControlsTestAppWPF/MUXControlsTestAppWPF.csproj
Labels: auto merge

#1111 Get MUX compiling with /permissive-
  dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp
  dev/Collections/Vector.h
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/TextCommandBarFlyout.cpp
  dev/DropDownButton/DropDownButtonAutomationPeer.cpp
  dev/LayoutPanel/LayoutPanel.cpp
  dev/Lights/RevealTestApi.cpp
  dev/Materials/Reveal/RevealBrush.cpp
  dev/MenuBar/MenuBarItem.cpp
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationViewItem.cpp
  dev/NavigationView/NavigationViewList.cpp
  dev/NavigationView/SplitDataSourceBase.h
  dev/ParallaxView/ParallaxView.cpp
  dev/PullToRefresh/RefreshVisualizer/RefreshVisualizer.cpp
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem.h
  dev/RatingControl/RatingControl.cpp
  dev/Repeater/ItemTemplateWrapper.cpp
  dev/Repeater/ItemsRepeater.cpp
  dev/Repeater/RecyclingElementFactory.cpp
  dev/Repeater/RepeaterAutomationPeer.cpp
  dev/Repeater/SelectionModel.cpp
  dev/Repeater/SelectionNode.cpp
  dev/Repeater/ViewManager.cpp
  dev/Repeater/ViewportManagerDownlevel.cpp
  dev/Repeater/ViewportManagerWithPlatformFeatures.cpp
  dev/ScrollViewer/ScrollViewer.cpp
  dev/Scroller/OffsetsChangeWithAdditionalVelocity.h
  dev/Scroller/Scroller.cpp
  dev/Scroller/SnapPointWrapper.cpp
  dev/Scroller/SnapPointWrapper.h
  dev/SplitButton/SplitButtonAutomationPeer.cpp
  dev/SplitButton/ToggleSplitButtonAutomationPeer.cpp
  dev/SwipeControl/SwipeControl.cpp
  dev/SwipeControl/SwipeItem.cpp
  dev/TabView/TabViewItem.cpp
  dev/Telemetry/RuntimeProfiler.cpp
  dev/TreeView/TreeView.cpp
  dev/TreeView/TreeViewItem.cpp
  dev/TreeView/TreeViewItemAutomationPeer.cpp
  dev/TreeView/TreeViewList.cpp
  dev/TwoPaneView/DisplayRegionHelper.cpp
  dev/dll/CommandingHelpers.cpp
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
  dev/inc/CastHelpers.h
  dev/inc/RuntimeClassHelpers.h
  dev/inc/SharedHelpers.h
  dev/inc/tracker_ref.h
Labels: auto merge

#1131 update to repeater to allow passing in uielements in itemssource
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/TestUI/RepeaterTestUIPage.xaml
  dev/Repeater/TestUI/RepeaterTestUIPage.xaml.cs
  dev/Repeater/TestUI/Repeater_TestUI.projitems
  dev/Repeater/TestUI/Samples/ElementsInItemsSourcePage.xaml
  dev/Repeater/TestUI/Samples/ElementsInItemsSourcePage.xaml.cs
  dev/Repeater/ViewManager.cpp
Labels: auto merge

#1153 Adding links to documentation to add context
  docs/developer_guide.md
Labels: auto merge

#1141 Move over some more templates
  dev/CommonStyles/Button_themeresources.xaml
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
  dev/CommonStyles/ProgressBar_themeresources.xaml
Labels: area-Styling

#1168 TabView: API changes to match spec
  dev/Generated/TabView.properties.cpp
  dev/Generated/TabView.properties.h
  dev/Generated/TabViewItem.properties.cpp
  dev/Generated/TabViewItem.properties.h
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TabView.h
  dev/TabView/TabView.idl
  dev/TabView/TabView.xaml
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
  dev/TabView/TestUI/TabViewPage.xaml
  dev/TabView/TestUI/TabViewPage.xaml.cs
Labels: release note

#1179 Fix the PaneVisible initialziation problem
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  dev/NavigationView/TestUI/NavigationViewInitPage.xaml
  dev/NavigationView/TestUI/NavigationViewInitPage.xaml.cs
Labels: auto merge, release note

#1165 CornerRadius updates/fixes
  dev/AutoSuggestBox/APITests/AutoSuggestBoxTests.cs
  dev/AutoSuggestBox/AutoSuggestBoxHelper.cpp
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/CalendarDatePicker/CalendarDatePicker_themeresources.xaml
  dev/ComboBox/APITests/ComboBoxTests.cs
  dev/ComboBox/ComboBoxHelper.cpp
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommonStyles/CornerRadius_themeresources.xaml
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
  dev/CommonStyles/ProgressBar_themeresources.xaml
  dev/CommonStyles/TestUI/CornerRadiusPage.xaml
  dev/DatePicker/DatePicker_themeresources.xaml
  dev/Slider/Slider_themeresources.xaml
Labels: area-Styling

#1171 Hover and pressed visual updates
  dev/CheckBox/CheckBox_themeresources.xaml
  dev/CheckBox/TestUI/CheckBoxPage.xaml
  dev/CommonStyles/Button_themeresources.xaml
  dev/CommonStyles/ToggleButton_themeresources.xaml
  dev/RadioButtons/RadioButton.xaml
  dev/RadioButtons/RadioButton_themeresources.xaml
  dev/RadioButtons/RadioButtons.vcxitems
  dev/RadioButtons/RadioButtons.vcxitems.filters
  dev/RadioButtons/RadioButtons_themeresources.xaml
  dev/RadioButtons/TestUI/RadioButtonsPage.xaml
  dev/SplitButton/SplitButton_themeresources.xaml
  dev/TreeView/TreeView.vcxitems
  dev/TreeView/TreeViewItem.xaml
  dev/TreeView/TreeViewItem_rs1.xaml
  dev/TreeView/TreeView_rs2_themeresources.xaml
  dev/TreeView/TreeView_themeresources.xaml
Labels: area-Styling

#1192 TabView: Visual update
  dev/Generated/TabView.properties.cpp
  dev/Generated/TabView.properties.h
  dev/TabView/TabView.cpp
  dev/TabView/TabView.idl
  dev/TabView/TabView.xaml
  dev/TabView/TabView_themeresources.xaml
  dev/TabView/TestUI/TabViewPage.xaml.cs
Labels: release note

#1196 Change Localization pipeline to PackageES Standard Build pool
  build/MUX-LocalizationHandoff.yml
Labels: auto merge

#1195 NavigationView: Fixing visibility of close button in Auto PaneDisplayMode and Minimal DisplayMode
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
Labels: area-NavigationView, bug, release note

#1202 Fix ItemsSource and TreeViewNode syncing
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TreeViewNode.cpp
  dev/TreeView/TreeViewNode.h
Labels: area-TreeView

#1219 Avoid crash when customer set selecteditem to not existing item in datasource.
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
  dev/NavigationView/TestUI/NavigationViewTopNavOnlyPage.xaml
  dev/NavigationView/TestUI/NavigationViewTopNavOnlyPage.xaml.cs
Labels: auto merge

#1223 More visual updates
  dev/CalendarDatePicker/CalendarDatePicker_themeresources.xaml
  dev/CheckBox/CheckBox_themeresources.xaml
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommonStyles/Button_themeresources.xaml
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/RepeatButton_themeresources.xaml
  dev/CommonStyles/TestUI/BorderThicknessPage.xaml
  dev/CommonStyles/TestUI/CornerRadiusPage.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
  dev/DatePicker/DatePicker_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_rs2_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_rs4_themeresources.xaml
  dev/NavigationView/NavigationView.xaml
  dev/RadioButtons/RadioButton.xaml
  dev/RadioButtons/RadioButton_themeresources.xaml
  dev/Slider/Slider_themeresources.xaml
  dev/TimePicker/TimePicker_themeresources.xaml
  test/TestAppUtils/Themes/Generic.xaml
Labels: area-Styling

#1234 A few small changes
  dev/Generated/TabView.properties.cpp
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TabView.idl
  dev/TabView/TabView.xaml
  dev/TabView/TabView_themeresources.xaml
  dev/TabView/TestUI/TabViewPage.xaml
Labels: auto merge

#1236 Add reveal style to Settings button in NavigationView in top mode,Closes #942
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
Labels: auto merge
