Repository microsoft/microsoft-ui-xaml, pull requests merged in 2019-04, with the labels that each got.

#471 Scroller snap points sharing bug fix
  dev/Scroller/APITests/ScrollerSnapPointTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/Scroller.h
  dev/Scroller/Scroller.vcxitems
  dev/Scroller/ScrollerSnapPoint.cpp
  dev/Scroller/ScrollerSnapPoint.h
  dev/Scroller/SnapPointWrapper.cpp
  dev/Scroller/SnapPointWrapper.h
  dev/Scroller/TestUI/ScrollerSnapPointsPage.xaml.cs
  dev/TestHooks/ScrollerTestHooks.cpp
  dev/TestHooks/ScrollerTestHooks.h
  dev/TestHooks/ScrollerTestHooks.idl
Labels: area-Scrolling

#531 Fixing busted relative links
  docs/developer_guide.md
Labels: auto merge

#553 Fixes Build.cmd if VS2019 is also installed on the system.
  Build.cmd
Labels: auto merge

#557 Fix layout cycle when an inner repeater needs corrections in non-scrollable direction
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/APITests/ViewManagerTests.cs
  dev/Repeater/FlowLayout.cpp
  dev/Repeater/FlowLayout.h
  dev/Repeater/FlowLayoutAlgorithm.cpp
  dev/Repeater/FlowLayoutAlgorithm.h
  dev/Repeater/ItemsRepeater.cpp
  dev/Repeater/ItemsRepeater.h
  dev/Repeater/LayoutContext.h
  dev/Repeater/RepeaterTrace.h
  dev/Repeater/StackLayout.cpp
  dev/Repeater/UniformGridLayout.cpp
  dev/Repeater/ViewManager.cpp
  dev/Repeater/ViewportManagerWithPlatformFeatures.cpp
  dev/Repeater/ViewportManagerWithPlatformFeatures.h
Labels: release note

#545 CommandBarFlyout keyboarding updates and RTL keyboarding fix
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/CommandBarFlyout.h
  dev/CommandBarFlyout/CommandBarFlyout.vcxitems
  dev/CommandBarFlyout/CommandBarFlyout.xaml
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.h
  dev/CommandBarFlyout/CommandBarFlyoutTrace.h
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutMainPage.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutMainPage.xaml.cs
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml.cs
  dev/Telemetry/TraceLogging.h
  dev/Telemetry/TypeLogging.cpp
  dev/Telemetry/TypeLogging.h
  dev/TestHooks/MUXControlsTestHooks.cpp
  dev/inc/RoutedEventHelpers.h
Labels: area-Commanding, release note

#566 Update readme for 2.1
  README.md
Labels: auto merge

#567 Scroller layout fix for cases where size is only constrained by MaxWidth/MaxHeight
  dev/Scroller/APITests/ScrollerLayoutTests.cs
  dev/Scroller/Scroller.cpp
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml
  dev/Scroller/TestUI/ScrollerDynamicPage.xaml.cs
Labels: area-Scrolling

#574 Update Target min version for 2.1
  README.md
Labels: auto merge

#586 Stop installing SDK in Nuget creation job
  build/AzurePipelinesTemplates/MUX-CreateNugetPackage-Job.yml
  build/FrameworkPackage/MakeFrameworkPackage.ps1
Labels: auto merge

#600 Set XamlRoot on TeachingTip so it can find its correct root in XamlIsland
  dev/TeachingTip/TeachingTip.cpp
Labels: auto merge

#589 Make consistency behaviour when clicking on a unselected item or clicking on a selected item
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTests.cs
Labels: auto merge

#612 Fix test cleanup failures
  test/MUXControlsTestApp/Utilities/TestHelpers.cs
Labels: auto merge, test issue

#609 Update ItemsSource when TreeViewNode changes
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TestUI/TreeViewPage.xaml.cs
  dev/TreeView/TreeView.cpp
  dev/TreeView/TreeViewItem.cpp
  dev/TreeView/TreeViewList.cpp
  dev/TreeView/TreeViewList.h
  dev/TreeView/TreeViewNode.cpp
  dev/TreeView/TreeViewNode.h
Labels: area-TreeView

#617 Remove UAP condition from release nuget package as well
  build/NuSpecs/MUXControls-Nuget-FrameworkPackage.targets
Labels: needs-cherrypicktorelease

#624 Updating condition for adding reference to VCLibs.
  build/NuSpecs/MUXControls-Nuget-FrameworkPackage.props
Labels: needs-cherrypicktorelease

#630 avoid reading index property on args during reset.
  dev/Repeater/APITests/InspectingDataSourceTests.cs
  dev/Repeater/InspectingDataSource.cpp
Labels: needs-cherrypicktorelease

#632 Fixing a spacing issue that is tied to orientation
  dev/Repeater/APITests/FlowLayoutTests.cs
  dev/Repeater/UniformGridLayout.h
  dev/Repeater/UniformGridLayoutState.cpp
Labels: needs-cherrypicktorelease
