Repository microsoft/microsoft-ui-xaml, pull requests merged in 2020-08, with the labels that each got.

#2969 Fix crash with UniformGridLayout trying to scroll to first item
  dev/Repeater/APITests/LayoutTests.cs
  dev/Repeater/UniformGridLayout.cpp
  dev/Repeater/UniformGridLayoutState.cpp
  dev/Repeater/UniformGridLayoutState.h
Labels: area-ItemsRepeater, team-Controls

#2881 Add CI mode button
  dev/Repeater/APITests/RepeaterFocusTests.cs
  dev/TabView/InteractionTests/TabViewTests.cs
  test/TestAppUtils/TestFrame.cs
  test/TestAppUtils/Themes/Generic.xaml
Labels: area-DevInternal, team-Controls

#3028 Fix issue with item that just got uncollapsed not showing selection
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/TestUI/NavigationViewIsPaneOpenPage.xaml
  dev/NavigationView/TestUI/NavigationViewIsPaneOpenPage.xaml.cs
Labels: area-NavigationView, team-Controls

#3022 Fix issue with TextCommandBarFlyout not opening when using custom button
  dev/CommandBarFlyout/InteractionTests/TextCommandBarFlyoutTests.cs
  dev/CommandBarFlyout/TestUI/ExtraCommandBarFlyoutPage.xaml
  dev/CommandBarFlyout/TestUI/ExtraCommandBarFlyoutPage.xaml.cs
  dev/CommandBarFlyout/TextCommandBarFlyout.cpp
Labels: area-Commanding, team-Controls

#2682 NavigationView ItemInvoked returning incorrect item fix
  dev/NavigationView/NavigationViewItemBase.h
  dev/NavigationView/NavigationViewItemsFactory.cpp
  dev/NavigationView/NavigationViewItemsFactory.h
  dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs
  dev/NavigationView/NavigationView_InteractionTests/EventTests.cs
  dev/NavigationView/TestUI/NavigationViewItemTemplatePage.xaml
  dev/NavigationView/TestUI/NavigationViewItemTemplatePage.xaml.cs
Labels: area-NavigationView, team-Controls

#2968 Remove legacy EIC style in WinUI
  dev/MenuFlyout/MenuFlyout_themeresources.xaml
Labels: area-Styling, team-Ink

#3044 Update ShouldSkipPRBuild to include .png and .PNG
  build/ShouldSkipPRBuild.ps1
Labels: area-DevInternal, team-Controls

#1997 NavigationView BottomMenuItems implementation
  dev/Generated/NavigationView.properties.cpp
  dev/Generated/NavigationView.properties.h
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  dev/NavigationView/NavigationView.idl
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationViewHelper.h
  dev/NavigationView/NavigationViewItem.cpp
  dev/NavigationView/NavigationViewItemAutomationPeer.cpp
  dev/NavigationView/NavigationViewItemAutomationPeer.h
  dev/NavigationView/NavigationViewItemSeparator.cpp
  dev/NavigationView/NavigationViewItemsFactory.cpp
  dev/NavigationView/NavigationViewItemsFactory.h
  dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs
  dev/NavigationView/NavigationView_InteractionTests/EventTests.cs
  dev/NavigationView/NavigationView_InteractionTests/FocusBehaviorTests.cs
  dev/NavigationView/NavigationView_InteractionTests/PaneBehaviorTests.cs
  dev/NavigationView/TestUI/NavigationViewInitPage.xaml
  dev/NavigationView/TestUI/NavigationViewInitPage.xaml.cs
  dev/NavigationView/TestUI/NavigationViewPage.xaml
  dev/NavigationView/TestUI/NavigationViewPage.xaml.cs
  dev/NavigationView/TestUI/NavigationViewPageDataContext.xaml.cs
  dev/NavigationView/TestUI/NavigationViewTopNavPage.xaml
  dev/NavigationView/TestUI/NavigationViewTopNavPage.xaml.cs
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-5.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-6.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTop.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent.xml
Labels: area-NavigationView, team-Controls

#3056 Move Common_themeresources.xml file from Common to CommonStyles directory.
  dev/Common/Common.vcxitems
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/Common_themeresources.xaml
Labels: area-DevInternal, needs-triage, team-Controls

#3054 CommandBar closes itself when buttons with flyouts are clicked.
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
Labels: area-Commanding, team-Controls

#3053 ListBox: Update selection brushes to improve color contrast and align with ListView
  dev/CommonStyles/ListBox_themeresources.xaml
Labels: area-Lists, team-Controls

#3048 RadioButtons: Fix selected radio button not being focused on tab navigation when first element in TAB navigation
  dev/RadioButtons/InteractionTests/RadioButtonsFocusTestPageElements.cs
  dev/RadioButtons/InteractionTests/RadioButtonsTestPageElements.cs
  dev/RadioButtons/InteractionTests/RadioButtonsTests.cs
  dev/RadioButtons/InteractionTests/RadioButtons_InteractionTests.projitems
  dev/RadioButtons/RadioButtons.cpp
  dev/RadioButtons/TestUI/RadioButtonsCaseBundle.xaml
  dev/RadioButtons/TestUI/RadioButtonsCaseBundle.xaml.cs
  dev/RadioButtons/TestUI/RadioButtonsFocusPage.xaml
  dev/RadioButtons/TestUI/RadioButtonsFocusPage.xaml.cs
  dev/RadioButtons/TestUI/RadioButtonsPage.xaml.cs
  dev/RadioButtons/TestUI/RadioButtons_TestUI.projitems
Labels: area-RadioButtons, team-Controls

#3068 Add workaround so ItemsRepeater doesn't leak the result of DataTemplate::Load
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/ItemsRepeater.cpp
  dev/Repeater/TestUI/Repeater_TestUI.projitems
  dev/Repeater/TestUI/Samples/ItemTemplateSamples/DisposableUserControl.xaml
  dev/Repeater/TestUI/Samples/ItemTemplateSamples/DisposableUserControl.xaml.cs
  dev/Repeater/TestUI/Samples/ItemTemplateSamples/ItemTemplateDemo.xaml
  dev/Repeater/TestUI/Samples/ItemTemplateSamples/ItemTemplateDemo.xaml.cs
  test/MUXControlsTestApp/Utilities/RunOnUIThread.cs
Labels: area-ItemsRepeater, team-Controls

#3055 Add support for ReadOnlyList/VectorView and notifycollectionchange
  dev/Repeater/APITests/Common/ReadOnlyNotifyPropertyChangedCollection.cs
  dev/Repeater/APITests/InspectingDataSourceTests.cs
  dev/Repeater/APITests/Repeater_APITests.projitems
  dev/Repeater/InspectingDataSource.cpp
  dev/Repeater/InspectingDataSource.h
Labels: area-ItemsRepeater, team-Controls

#2977 Initial Pager Control Check-In - Partial C# Prototype
  FeatureAreas.props
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/Pager/InteractionTests/PagerTests.cs
  dev/Pager/InteractionTests/PagerTestsPageElements.cs
  dev/Pager/InteractionTests/Pager_InteractionTests.projitems
  dev/Pager/InteractionTests/Pager_InteractionTests.shproj
  dev/Pager/PrototypePager/PageChangedEventArgs.cs
  dev/Pager/PrototypePager/PrototypePager.Events.cs
  dev/Pager/PrototypePager/PrototypePager.Properties.cs
  dev/Pager/PrototypePager/PrototypePager.TestHooks.cs
  dev/Pager/PrototypePager/PrototypePager.cs
  dev/Pager/PrototypePager/PrototypePager.projitems
  dev/Pager/PrototypePager/PrototypePager.shproj
  dev/Pager/PrototypePager/Themes/PrototypePager.xaml
  dev/Pager/TestUI/PagerPage.xaml
  dev/Pager/TestUI/PagerPage.xaml.cs
  dev/Pager/TestUI/Pager_TestUI.projitems
  dev/Pager/TestUI/Pager_TestUI.shproj
  dev/Telemetry/RuntimeProfiler.h
  test/MUXControls.Test/MSTest/MUXControls.Test.csproj
  test/MUXControlsTestApp/App.xaml.cs
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: area-Pager, team-Controls

#3079 Fix issue with flyouts created in CommandBarFlyout not closing when commandbar closes
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
Labels: area-Commanding, team-Controls

#3005 NumberBox: Fix header foreground color not being properly updated when NumberBox is disabled.
  dev/NumberBox/APITests/NumberBoxTests.cs
  dev/NumberBox/NumberBox.cpp
  dev/NumberBox/NumberBox.h
  dev/NumberBox/NumberBox.xaml
Labels: area-NumberBox, team-Controls

#2901 TextAlignment property added to NumberBox
  dev/Generated/NumberBox.properties.cpp
  dev/Generated/NumberBox.properties.h
  dev/NumberBox/APITests/NumberBoxTests.cs
  dev/NumberBox/NumberBox.idl
  dev/NumberBox/NumberBox.xaml
  dev/NumberBox/TestUI/NumberBoxPage.xaml
  dev/NumberBox/TestUI/NumberBoxPage.xaml.cs
Labels: area-NumberBox, team-Controls

#3095 Enable PR build to run on new winuibuildagents build pool
  .vsconfig
  build/AzurePipelinesTemplates/MUX-InstallWindowsSDK-Steps.yml
  build/Install-WindowsSdkISO.ps1
  build/MUX-PR.yml
  build/MUX-SimpleBuildAndTest.yml
  dev/dll/Microsoft.UI.Xaml.vcxproj
  tools/MUXPGODatabase/restore-pgodb.ps1
  tools/NugetWrapper.cmd
Labels: needs-triage

#3088 Change disabled tests to use [TestProperty("Ignore", "True")]
  dev/AutoSuggestBox/APITests/AutoSuggestBoxTests.cs
  dev/Lights/ApiTests/Lights_ApiTests/LightConfigurationTests.cs
  dev/Materials/Reveal/APITests/RevealTests.cs
  dev/Materials/Reveal/InteractionTests/Reveal_InteractionTests/RevealBrushTests.cs
  dev/MenuBar/MenuBar_InteractionTests/MenuBarTests.cs
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
  dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs
  dev/NavigationView/NavigationView_InteractionTests/FocusBehaviorTests.cs
  dev/NavigationView/NavigationView_InteractionTests/PaneBehaviorTests.cs
  dev/NavigationView/NavigationView_InteractionTests/SelectionTests.cs
  dev/PullToRefresh/ScrollViewerIRefreshInfoProviderAdapter/InteractionTests/ScrollViewerAdapterTests.cs
  dev/RadioMenuFlyoutItem/InteractionTests/RadioMenuFlyoutItemTests.cs
  dev/RatingControl/InteractionTests/RatingControlTests.cs
  dev/Repeater/APITests/FlowLayoutCollectionChangeTests.cs
  dev/Repeater/APITests/ViewManagerTests.cs
  dev/Repeater/APITests/ViewportTests.cs
  dev/ScrollPresenter/InteractionTests/ScrollPresenterTestsWithInputHelper.cs
  dev/SwipeControl/SwipeControl_InteractionTests/SwipeControlTests.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TreeView/APITests/TreeViewTests.cs
  dev/TreeView/InteractionTests/TreeViewTests.cs
Labels: area-TestInfrastructure, team-Controls

#3094 Disable TabViewTests.GamePadTest on RS2
  dev/TabView/InteractionTests/TabViewTests.cs
Labels: area-TabView, area-TestInfrastructure, team-Controls

#3100 Restructure test UI pages for NavigationView
  dev/NavigationView/TestUI/Common/NavigationViewAnimationPage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewAnimationPage.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewBlankPage1.xaml
  dev/NavigationView/TestUI/Common/NavigationViewBlankPage1.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewCompactPaneLengthTestPage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewCompactPaneLengthTestPage.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewInitPage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewInitPage.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewIsPaneOpenPage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewIsPaneOpenPage.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewMenuItemStretchPage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewMenuItemStretchPage.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewMinimalPage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewMinimalPage.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewPage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewPage.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewPageDataContext.xaml
  dev/NavigationView/TestUI/Common/NavigationViewPageDataContext.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewSelectedItemEdgeCasePage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewSelectedItemEdgeCasePage.xaml.cs
  dev/NavigationView/TestUI/Common/NavigationViewStretchPage.xaml
  dev/NavigationView/TestUI/Common/NavigationViewStretchPage.xaml.cs
  dev/NavigationView/TestUI/CustomResources/NavigationViewCustomThemeResourcesPage.xaml
  dev/NavigationView/TestUI/CustomResources/NavigationViewCustomThemeResourcesPage.xaml.cs
  dev/NavigationView/TestUI/CustomResources/NavigationViewItemTemplatePage.xaml
  dev/NavigationView/TestUI/CustomResources/NavigationViewItemTemplatePage.xaml.cs
  dev/NavigationView/TestUI/Hierarchical/HierarchicalNavigationViewDataBinding.xaml
  dev/NavigationView/TestUI/Hierarchical/HierarchicalNavigationViewDataBinding.xaml.cs
  dev/NavigationView/TestUI/Hierarchical/HierarchicalNavigationViewMarkup.xaml
  dev/NavigationView/TestUI/Hierarchical/HierarchicalNavigationViewMarkup.xaml.cs
  dev/NavigationView/TestUI/NavigationViewCaseBundle.xaml
  dev/NavigationView/TestUI/NavigationViewCaseBundle.xaml.cs
  dev/NavigationView/TestUI/NavigationView_TestUI.projitems
  dev/NavigationView/TestUI/Regression/NavigationViewRS3Page.xaml
  dev/NavigationView/TestUI/Regression/NavigationViewRS3Page.xaml.cs
  dev/NavigationView/TestUI/Regression/NavigationViewRS4Page.xaml
  dev/NavigationView/TestUI/Regression/NavigationViewRS4Page.xaml.cs
  dev/NavigationView/TestUI/TopMode/NavigationViewTopNavOnlyPage.xaml
  dev/NavigationView/TestUI/TopMode/NavigationViewTopNavOnlyPage.xaml.cs
  dev/NavigationView/TestUI/TopMode/NavigationViewTopNavPage.xaml
  dev/NavigationView/TestUI/TopMode/NavigationViewTopNavPage.xaml.cs
  dev/NavigationView/TestUI/TopMode/NavigationViewTopNavStorePage.xaml
  dev/NavigationView/TestUI/TopMode/NavigationViewTopNavStorePage.xaml.cs
Labels: area-NavigationView, area-TestInfrastructure, team-Controls

#3122 Update the Bug report template for WinUI 3
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, team-Controls

#2982 Add initial architecture docs for NavView
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/NavigationView/docs/NavigationViewItem.md
  dev/NavigationView/docs/rendering.md
  dev/NavigationView/readme.md
Labels: area-NavigationView, documentation, team-Controls

#3065 Add missing controls to toolbox file
  build/NuSpecs/VisualStudioToolsManifest.xml
Labels: area-DevInternal, team-Controls

#3153 Fix the build breaks in the CI loop
  dev/NumberBox/NumberBoxParser.cpp
  dev/Repeater/ViewportManagerWithPlatformFeatures.cpp
  dev/ScrollPresenter/ScrollPresenter.cpp
  dev/ScrollPresenter/ScrollPresenter.h
  dev/ScrollPresenter/ScrollPresenterTestHooks.cpp
Labels: needs-triage

#3146 Fix NumberBox's APITests project location in the innerloop solution.
  MUXControlsInnerLoop.sln
Labels: area-DevInternal, team-Controls

#3138 Fix issue with collection change inside item invoked crashing NavigationView
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/TestUI/Common/NavigationViewPageDataContext.xaml
  dev/NavigationView/TestUI/Common/NavigationViewPageDataContext.xaml.cs
Labels: area-NavigationView, team-Controls

#3126 Update issue refs
  dev/Lights/ApiTests/Lights_ApiTests/LightConfigurationTests.cs
  dev/Materials/Reveal/InteractionTests/Reveal_InteractionTests/RevealBrushTests.cs
  dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs
  dev/NavigationView/NavigationView_InteractionTests/PaneBehaviorTests.cs
  dev/PullToRefresh/ScrollViewerIRefreshInfoProviderAdapter/InteractionTests/ScrollViewerAdapterTests.cs
  dev/RadioMenuFlyoutItem/InteractionTests/RadioMenuFlyoutItemTests.cs
  dev/RatingControl/InteractionTests/RatingControlTests.cs
  dev/Repeater/APITests/FlowLayoutCollectionChangeTests.cs
  dev/Repeater/APITests/ViewportTests.cs
  dev/ScrollPresenter/InteractionTests/ScrollPresenterTestsWithInputHelper.cs
  dev/SwipeControl/SwipeControl_InteractionTests/SwipeControlTests.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TreeView/InteractionTests/TreeViewTests.cs
Labels: documentation, team-Controls

#3152 Update gamepad helper
  test/MUXControls.Test/Common/GamepadHelper.cs
  test/TestAppUtils/TestFrame.cs
  test/TestAppUtils/Themes/Generic.xaml
Labels: area-TestInfrastructure, team-Controls

#3145 Fix issue with NavigationView ShoulderNavigation always not behaving correctly
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_InteractionTests/FocusBehaviorTests.cs
  dev/NavigationView/TestUI/TopMode/NavigationViewTopNavOnlyPage.xaml
  dev/NavigationView/TestUI/TopMode/NavigationViewTopNavOnlyPage.xaml.cs
Labels: area-NavigationView, team-Controls

#3130 NumberBox: Updated the border and background of the spin button popup to match Fluent Design guidelines.
  dev/NumberBox/NumberBox.xaml
  dev/NumberBox/NumberBox_themeresources.xaml
Labels: area-NumberBox, team-Controls

#3177 Remove screenshots field from failed test runs report in AzDO
  build/Helix/UpdateUnreliableTests.ps1
Labels: area-DevInternal, team-Controls

#3160 Add binlog documentation
  docs/debugging_buildfailures.md
  docs/images/binlog-images/buildandrunoptions.png
  docs/images/binlog-images/buildlogging_menuitem.png
  docs/images/binlog-images/buildlogging_window.png
Labels: documentation

#3195 Remove define intellisense
  dev/inc/CppWinRTIncludes.h
Labels: area-DevInternal, team-Controls

#3182 Reenable tests
  dev/RadioButtons/InteractionTests/RadioButtonsTests.cs
  dev/RatingControl/InteractionTests/RatingControlTests.cs
  dev/TreeView/InteractionTests/TreeViewTests.cs
Labels: area-DevInternal, team-Controls

#3136 Fix issue with setting SelectedItem on TreeView would crash application
  dev/TreeView/APITests/TreeViewTests.cs
  dev/TreeView/TreeView.cpp
Labels: area-TreeView, team-Controls
