Repository microsoft/microsoft-ui-xaml, pull requests merged in 2020-10, with the labels that each got.

#3271 TeachingTip: Fix HeroContentPlacement being ignored when initially set from XAML markup
  dev/TeachingTip/APITests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
Labels: area-TeachingTip, team-Controls

#3358 RadioButtons: Fix header not having correct color when disabled
  dev/RadioButtons/APITests/RadioButtonsTests.cs
  dev/RadioButtons/RadioButtons.cpp
  dev/RadioButtons/RadioButtons.h
  dev/RadioButtons/RadioButtons.xaml
  dev/RadioButtons/RadioButtons_themeresources.xaml
Labels: area-RadioButtons, area-Styling, team-Controls

#3354 Add advice about BCSmake build error.
  docs/developer_guide.md
  docs/images/BrowseInformation.PNG
Labels: documentation, team-Controls

#3366 Remove margin on ColorSpectrum ellipse resulting in partial cutoff
  dev/ColorPicker/ColorSpectrum.xaml
Labels: area-ColorPicker, team-Controls

#3395 Change handlers to revokers
  dev/MenuBar/MenuBarItem.cpp
  dev/MenuBar/MenuBarItem.h
Labels: Area-Desktop, area-Menus, team-Controls, winui3preview

#3396 Update progress ring API
  dev/Generated/ProgressRing.properties.cpp
  dev/Generated/ProgressRing.properties.h
  dev/ProgressRing/InteractionTests/ProgressRingTests.cs
  dev/ProgressRing/ProgressRing.cpp
  dev/ProgressRing/ProgressRing.h
  dev/ProgressRing/ProgressRing.idl
  dev/ProgressRing/ProgressRingAutomationPeer.cpp
  dev/ProgressRing/ProgressRingAutomationPeer.h
  dev/ProgressRing/TestUI/ProgressRingPage.xaml
Labels: area-Progress, team-Controls

#3405 Minor typos
  dev/TreeView/ViewModel.cpp
Labels: documentation

#3428 Set correct date for next community call
  index.html
Labels: needs-triage

#3403 Suggext -> Suggest
  dev/AutoSuggestBox/AutoSuggestBoxHelper.cpp
Labels: area-AutoSuggestBox, team-Controls

#3435 ComboBox: Add ComboBoxBackgroundFocused resource for focused state
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/ComboBox/TestUI/ComboBoxPage.xaml
Labels: area-ComboBox, area-Styling, team-Controls

#3446 Fix pipeline instability.
  build/Helix/ProcessHelixFiles.ps1
Labels: needs-triage

#3454 Updating the order of feature roadmap
  docs/roadmap.md
Labels: needs-triage

#3429 Updating community call calendar invite
  WinUICommunityCall.ics
Labels: documentation, team-Controls

#3452 Pipeline stability fix take 2
  build/Helix/ProcessHelixFiles.ps1
Labels: area-DevInternal

#3387 Updating release date in readme
  README.md
Labels: documentation, winui3preview

#3327 Add PagerControl
  FeatureAreas.props
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/Generated/PagerControl.properties.cpp
  dev/Generated/PagerControl.properties.h
  dev/Generated/PagerControlAutomationPeer.properties.cpp
  dev/Generated/PagerControlTemplateSettings.properties.cpp
  dev/Generated/PagerControlTemplateSettings.properties.h
  dev/Pager/InteractionTests/PagerTests.cs
  dev/Pager/PrototypePager/PageChangedEventArgs.cs
  dev/Pager/PrototypePager/PrototypePager.Events.cs
  dev/Pager/PrototypePager/PrototypePager.Properties.cs
  dev/Pager/PrototypePager/PrototypePager.TestHooks.cs
  dev/Pager/PrototypePager/PrototypePager.cs
  dev/Pager/PrototypePager/PrototypePager.projitems
  dev/Pager/PrototypePager/PrototypePagerElementFactory.cs
  dev/Pager/TestUI/PagerPage.xaml.cs
  dev/PagerControl/APITests/PagerControlTests.cs
  dev/PagerControl/APITests/PagerControl_APITests.projitems
  dev/PagerControl/APITests/PagerControl_APITests.shproj
  dev/PagerControl/InteractionTests/PagerControlTestBase.cs
  dev/PagerControl/InteractionTests/PagerControlTestPageElements.cs
  dev/PagerControl/InteractionTests/PagerControlTests.cs
  dev/PagerControl/InteractionTests/PagerControl_InteractionTests.projitems
  dev/PagerControl/InteractionTests/PagerControl_InteractionTests.shproj
  dev/PagerControl/PagerControl.cpp
  dev/PagerControl/PagerControl.h
  dev/PagerControl/PagerControl.idl
  dev/PagerControl/PagerControl.vcxitems
  dev/PagerControl/PagerControl.xaml
  dev/PagerControl/PagerControlAutomationPeer.cpp
  dev/PagerControl/PagerControlAutomationPeer.h
  dev/PagerControl/PagerControlAutomationPeer.idl
  dev/PagerControl/PagerControlSelectedIndexChangedEventArgs.h
  dev/PagerControl/PagerControlTemplateSettings.cpp
  dev/PagerControl/PagerControlTemplateSettings.h
  dev/PagerControl/PagerControl_themeresources.xaml
  dev/PagerControl/Resources.resw
  dev/PagerControl/TestUI/PagerControlPage.xaml
  dev/PagerControl/TestUI/PagerControlPage.xaml.cs
  dev/PagerControl/TestUI/PagerControl_TestUI.projitems
  dev/PagerControl/TestUI/PagerControl_TestUI.shproj
  dev/PagerControl/readme.md
  dev/ResourceHelper/ResourceAccessor.h
  dev/Telemetry/RuntimeProfiler.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControls.Test/MSTest/MUXControls.Test.csproj
  test/MUXControls.Test/MUXControls.Test.Shared.targets
  test/MUXControlsReleaseTest/MUXControlsReleaseTest.sln
  test/MUXControlsTestApp/App.xaml.cs
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
  tools/CustomTasks/DependencyPropertyCodeGen.cs
Labels: area-Pager, team-Controls

#3465 Pipeline fixes take 3
  build/Helix/ProcessHelixFiles.ps1
Labels: needs-triage

#3325 Adding InfoBar Control
  FeatureAreas.props
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/Generated/CloseButtonClickEventArgs.properties.cpp
  dev/Generated/InfoBar.properties.cpp
  dev/Generated/InfoBar.properties.h
  dev/Generated/InfoBarAutomationPeer.properties.cpp
  dev/Generated/InfoBarClosedEventArgs.properties.cpp
  dev/Generated/InfoBarClosingEventArgs.properties.cpp
  dev/Generated/InfoBarPanel.properties.cpp
  dev/Generated/InfoBarPanel.properties.h
  dev/Generated/InfoBarTemplateSettings.properties.cpp
  dev/Generated/InfoBarTemplateSettings.properties.h
  dev/InfoBar/InfoBar.cpp
  dev/InfoBar/InfoBar.h
  dev/InfoBar/InfoBar.idl
  dev/InfoBar/InfoBar.vcxitems
  dev/InfoBar/InfoBar.xaml
  dev/InfoBar/InfoBarAutomationPeer.cpp
  dev/InfoBar/InfoBarAutomationPeer.h
  dev/InfoBar/InfoBarClosedEventArgs.cpp
  dev/InfoBar/InfoBarClosedEventArgs.h
  dev/InfoBar/InfoBarClosingEventArgs.cpp
  dev/InfoBar/InfoBarClosingEventArgs.h
  dev/InfoBar/InfoBarPanel.cpp
  dev/InfoBar/InfoBarPanel.h
  dev/InfoBar/InfoBarTemplateSettings.cpp
  dev/InfoBar/InfoBarTemplateSettings.h
  dev/InfoBar/InfoBar_themeresources.xaml
  dev/InfoBar/InteractionTests/InfoBarTests.cs
  dev/InfoBar/InteractionTests/InfoBar_InteractionTests.shproj
  dev/InfoBar/Strings/en-us/Resources.resw
  dev/InfoBar/TestUI/InfoBar.cs
  dev/InfoBar/TestUI/InfoBarPage.xaml
  dev/InfoBar/TestUI/InfoBarPage.xaml.cs
  dev/InfoBar/TestUI/InfoBar_TestUI.projitems
  dev/InfoBar/TestUI/InfoBar_TestUI.shproj
  dev/InfoBar/TestUI/Themes/InfoBarStyles.xaml
  dev/ResourceHelper/ResourceAccessor.h
  dev/Telemetry/RuntimeProfiler.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControlsTestApp/App.xaml.cs
Labels: area-InfoBar, team-Controls

#3511 Move build to windevbuildagents
  build/MUX-CI.yml
  build/MUX-PR.yml
  build/MUX-Release.yml
  build/MUX-SimpleBuildAndTest.yml
Labels: needs-triage

#3512 Remove infobar from innerloop when it isn't explicitly included.
  InnerLoopAreas.props
  MUXControlsInnerLoop.sln
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: area-DevInternal, team-Controls

#3474 Update script to add API test projects and add empty dependency list in FeatureArea.props file
  tools/GenerateNewControlProject.ps1
  tools/GenerateNewControlProjectFiles/APITests/NEWCONTROLTests.cs
  tools/GenerateNewControlProjectFiles/APITests/NEWCONTROL_APITests.projitems
  tools/GenerateNewControlProjectFiles/APITests/NEWCONTROL_APITests.shproj
Labels: area-DevInternal, team-Controls

#3438 VisualTreeUtils: Improved API consistency, code cleanup
  dev/CommonStyles/TestUI/CommonStylesPage.xaml.cs
  dev/CommonStyles/TestUI/CompactPage.xaml.cs
  dev/Repeater/TestUI/Samples/LayoutSamples/NestedLayoutSamples/ItemsViewWithDataPage.xaml.cs
  dev/TabView/TestUI/TabViewTabItemsSourcePage.xaml.cs
  test/MUXControlsTestApp/Utilities/VisualTreeUtils.cs
Labels: area-DevInternal, team-Controls

#3404 IsSelectionRequried -> IsSelectionRequired
  dev/TreeView/TreeViewListAutomationPeer.cpp
  dev/TreeView/TreeViewListAutomationPeer.h
Labels: area-TreeView, team-Controls

#3359 Fix inner loop solution test runs
  test/testinfra/MUXTestInfra/Infra/TestEnvironment.cs
  test/testinfra/MUXTestInfra/MSTest/MUXTestInfra.MSTest.csproj
  test/testinfra/MUXTestInfra/TAEF/MUXTestInfra.TAEF.csproj
Labels: area-TestInfrastructure, team-Controls
