Repository microsoft/microsoft-ui-xaml, pull requests merged in 2020-07, with the labels that each got.

#2778 Add support for NotifyCollectionChangedAction.Move to ItemsRepeater
  dev/Repeater/APITests/Common/CollectionChangeEventArgsConverters.cs
  dev/Repeater/APITests/Common/CustomItemsSource.cs
  dev/Repeater/APITests/FlowLayoutCollectionChangeTests.cs
  dev/Repeater/ElementManager.cpp
  dev/Repeater/TestUI/Samples/ItemsSourceSamples/CollectionChangeDemo.xaml
  dev/Repeater/TestUI/Samples/ItemsSourceSamples/CollectionChangeDemo.xaml.cs
  dev/Repeater/UniformGridLayoutState.cpp
Labels: area-ItemsRepeater, team-Controls

#2801 Fix generateproject script
  tools/GenerateNewControlProject.ps1
Labels: area-DevInternal, team-Controls

#2784 Add instructions for switching to/from MUXControlsInnerLoop.sln
  docs/developer_guide.md
Labels: documentation, team-Controls

#2759 Hide NavigationViewItem Chevron if Children is empty
  dev/NavigationView/NavigationViewItem.cpp
  dev/NavigationView/NavigationViewItem.h
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
Labels: area-NavigationView, team-Controls

#2809 README: Update WinUI 2 Version support section
  README.md
Labels: auto merge, documentation, needs-triage, team-Controls

#2765 NumberBox: Fix deselecting text when opening context menu
  dev/NumberBox/InteractionTests/NumberBoxTests.cs
  dev/NumberBox/NumberBox.cpp
  dev/NumberBox/NumberBox.h
Labels: area-NumberBox, team-Controls

#2806 Fix issue with SplitButton overriding every flyout placement
  dev/SplitButton/SplitButton.cpp
  dev/SplitButton/TestUI/SplitButtonPage.xaml
Labels: Area-SplitButton, team-Controls

#2815 Create debugging_crashes.md doc
  docs/debugging_crashes.md
Labels: needs-triage

#2833 Add missed Slider dependency to ColorPicker InnerLoop
  FeatureAreas.props
Labels: needs-triage

#2842 Switch signing cert to WindowsRT
  build/SignConfig.xml
Labels: needs-triage

#2850 remove unused files
  tools/CodeCoverage/CodeCoverage.psm1
  tools/CodeCoverage/CreateCodeCoverageReport.cmd
  tools/CodeCoverage/CreateCodeCoverageReport.ps1
  tools/CodeCoverage/CreateCodeCoverageReportWrapper.cmd
  tools/CodeCoverage/InstrumentBinaries.cmd
  tools/CodeCoverage/InstrumentBinaries.ps1
  tools/CodeCoverage/PkgGen.cmd
  tools/CodeCoverage/PostBuild.cmd
  tools/CodeCoverage/PostBuildWrapper.cmd
  tools/CodeCoverage/PushCodeCoverageData.ps1
  tools/CodeCoverage/PushCodeCoverageSymbols.cmd
  tools/CodeCoverage/PushCodeCoverageSymbols.ps1
  tools/CodeCoverage/StartCodeCoverage.ps1
  tools/CodeCoverage/StopCodeCoverage.ps1
Labels: area-DevInternal, needs-triage, team-Controls

#2857 Disable multi-proc building in lab
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: area-DevInternal, team-Controls

#2840 Readme: Add link to WinUI's website and move Project Reunion blurb to the end
  README.md
Labels: documentation, team-Controls

#2858 Fix Arm exclusive build breaks.
  dev/Repeater/FlowLayoutAlgorithm.cpp
  dev/Repeater/ItemsRepeaterScrollHost.cpp
  dev/Repeater/UniformGridLayout.cpp
  dev/ScrollPresenter/ScrollPresenter.cpp
  dev/ScrollPresenter/ScrollPresenterAnchoring.cpp
  dev/ScrollPresenter/ScrollPresenterPrivate.cpp
  dev/TwoPaneView/DisplayRegionHelper.cpp
Labels: area-DevInternal, auto merge, team-Controls

#2865 Disable multi-proc build for lab machines
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: needs-triage

#2869 Run Code Analysis in the lab only on debug
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: needs-triage

#2788 InfoBar prototype
  FeatureAreas.props
  MUXControls.sln
  dev/InfoBar/InteractionTests/InfoBarTests.cs
  dev/InfoBar/InteractionTests/InfoBar_InteractionTests.projitems
  dev/InfoBar/InteractionTests/InfoBar_InteractionTests.shproj
  dev/InfoBar/TestUI/InfoBar.cs
  dev/InfoBar/TestUI/InfoBarPage.xaml
  dev/InfoBar/TestUI/InfoBarPage.xaml.cs
  dev/InfoBar/TestUI/InfoBar_TestUI.projitems
  dev/InfoBar/TestUI/InfoBar_TestUI.shproj
  dev/InfoBar/TestUI/Themes/InfoBarStyles.xaml
  dev/Telemetry/RuntimeProfiler.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControls.Test/MUXControls.Test.Shared.targets
  test/MUXControlsTestApp/App.xaml
  test/MUXControlsTestApp/App.xaml.cs
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: area-InfoBar, team-Controls

#2880 Minor update to CreateVpackFromNupkg.ps1
  build/FrameworkPackage/CreateVpackFromNupkg.ps1
Labels: area-DevInternal, team-Controls

#2810 NavigationView incorrectly sizing items as compact on launch
  dev/NavigationView/NavigationView.cpp
Labels: area-NavigationView, team-Controls

#2660 Update doc for visual tree masters update
  docs/developer_guide.md
  docs/images/test_fail_page3.png
  docs/images/test_pipeline_drop.png
  docs/images/test_pipeline_drop2.png
  docs/images/test_pipeline_verificationfiles_links.png
Labels: area-TestInfrastructure, documentation, team-Controls

#2892 Update comment in innerloop area file
  InnerLoopAreas.props
Labels: documentation, team-Controls

#2692 NavigationView not updating UIA users about changed selection and expand state
  dev/Generated/NavigationViewItem.properties.cpp
  dev/Generated/NavigationViewItem.properties.h
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  dev/NavigationView/NavigationView.idl
  dev/NavigationView/NavigationViewAutomationPeer.cpp
  dev/NavigationView/NavigationViewAutomationPeer.h
  dev/NavigationView/NavigationViewItem.cpp
  dev/NavigationView/NavigationViewItem.h
Labels: accessibility, area-NavigationView, needs-cherrypicktorelease, team-Controls

#2909 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#2914 Updating website stuff for preview 2
  about.html
  index.html
Labels: documentation, website

#2907 Trying to fix broken link in roadmap
  docs/roadmap.md
Labels: needs-triage

#2915 Create preview_upgrade_instructions.md
  docs/preview_upgrade_instructions.md
Labels: documentation

#2827 Tabview switch to converter instead of template settings
  dev/Common/CornerRadiusToThicknessConverter.cpp
  dev/Common/CornerRadiusToThicknessConverter.h
  dev/Common/CornerRadiusToThicknessConverter.idl
  dev/CommonStyles/CornerRadius_themeresources.xaml
  dev/Generated/CornerRadiusToThicknessConverter.properties.cpp
  dev/Generated/CornerRadiusToThicknessConverter.properties.h
  dev/Generated/TabViewItemTemplateSettings.properties.cpp
  dev/Generated/TabViewItemTemplateSettings.properties.h
  dev/TabView/TabView.idl
  dev/TabView/TabView.xaml
  dev/TabView/TabViewItem.cpp
Labels: area-TabView, team-Controls

#2919 Readme: Update for WinUI 3 Preview 2
  README.md
Labels: documentation

#2899 Remove stray close braces
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_19h1_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_rs3_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_rs4_themeresources.xaml
Labels: area-Styling, team-Controls

#2889 Add check to only open flyout if a menubaritem has items
  dev/MenuBar/MenuBarItem.cpp
  dev/MenuBar/MenuBar_InteractionTests/MenuBarTests.cs
  dev/MenuBar/MenuBar_TestUI/MenuBarPage.xaml
  dev/MenuBar/MenuBar_TestUI/MenuBarPage.xaml.cs
Labels: area-Menus, team-Controls

#2936 Adding public ScrollView.CurrentAnchor read-only property
  dev/ScrollPresenter/APITests/ScrollPresenterAnchoringTests.cs
  dev/ScrollPresenter/ScrollPresenter.h
  dev/ScrollPresenter/ScrollPresenterPrimitives.idl
  dev/ScrollPresenter/TestUI/ScrollPresenterRepeaterAnchoringPage.xaml
  dev/ScrollPresenter/TestUI/ScrollPresenterRepeaterAnchoringPage.xaml.cs
  dev/ScrollPresenter/TestUI/ScrollPresenterStackPanelAnchoringPage.xaml
  dev/ScrollPresenter/TestUI/ScrollPresenterStackPanelAnchoringPage.xaml.cs
  dev/ScrollView/APITests/ScrollViewTests.cs
  dev/ScrollView/ScrollView.cpp
  dev/ScrollView/ScrollView.h
  dev/ScrollView/ScrollView.idl
  dev/ScrollView/TestUI/ScrollViewDynamicPage.xaml
  dev/ScrollView/TestUI/ScrollViewDynamicPage.xaml.cs
Labels: area-Scrolling, needs-triage

#2823 TabView: Enable separate lightweight styling of the Add button and the TabViewItem's Close button
  dev/TabView/TabView.xaml
  dev/TabView/TabView_themeresources.xaml
Labels: area-Styling, area-TabView, team-Controls

#2856 Add TabView SelectionPattern
  dev/TabView/APITests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TabViewAutomationPeer.cpp
  dev/TabView/TabViewAutomationPeer.h
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
  dev/TabView/TabViewItemAutomationPeer.cpp
  dev/TabView/TabViewItemAutomationPeer.h
Labels: accessibility, area-TabView, team-Controls

#2955 Replace as casts with unbox_value
  dev/dll/CommonHelpers.tt
Labels: needs-triage

#2959 Fix typo in ProcessHelixFiles
  build/Helix/ProcessHelixFiles.ps1
Labels: needs-triage

#2960 Updating date and ics for community call
  WinUICommunityCall.ics
  index.html
Labels: documentation, team-Controls

#2819 Fix issue with invoke pattern being provided for top navview item
  dev/NavigationView/NavigationViewItemAutomationPeer.cpp
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
  dev/NavigationView/NavigationView_InteractionTests/EventTests.cs
  dev/NavigationView/NavigationView_InteractionTests/FocusBehaviorTests.cs
  dev/NavigationView/NavigationView_InteractionTests/NavigationViewTestsBase.cs
  dev/NavigationView/NavigationView_InteractionTests/PaneBehaviorTests.cs
  dev/NavigationView/NavigationView_InteractionTests/SelectionTests.cs
  dev/NavigationView/NavigationView_InteractionTests/TopModeTests.cs
Labels: area-NavigationView, team-Controls

#2923 NavigationView: Add more theme resources to configure margins
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
Labels: area-NavigationView, team-Controls

#2943 Updating roadmap image to latest
  docs/images/WinUI-RoadmapJuly2020.png
  docs/images/winui-roadmap-img.PNG
  docs/preview_upgrade_instructions.md
  docs/roadmap.md
Labels: documentation, team-Controls

#2997 Fixing broken link
  docs/preview_upgrade_instructions.md
Labels: documentation, team-Controls

#3016 Treeview: Fix Background API not being applied to TreeView UI.
  dev/TreeView/APITests/TreeViewTests.cs
  dev/TreeView/TreeView.xaml
Labels: area-Styling, area-TreeView, team-Controls

#2981 Add NumberBox_APITests project to InnerLoop solution
  MUXControlsInnerLoop.sln
Labels: area-NumberBox, team-Controls

#2905 Add resource for topmode CustomContentPane minimum width
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
Labels: area-NavigationView, team-Controls
