Repository microsoft/microsoft-ui-xaml, pull requests merged in 2020-12, with the labels that each got.

#3739 More InfoBarPanel API udpates
  dev/Generated/InfoBarPanel.properties.cpp
  dev/Generated/InfoBarPanel.properties.h
  dev/InfoBar/InfoBar.idl
  dev/InfoBar/InfoBar.xaml
  dev/InfoBar/InfoBarPanel.cpp
  dev/InfoBar/InfoBar_themeresources.xaml
Labels: area-InfoBar, team-Controls

#3742 Innerloop: Add RadioButtons control dependency to NavigationView
  FeatureAreas.props
  MUXControlsInnerLoop.sln
Labels: area-DevInternal

#3758 Updating links, etc for security on website
  about.html
  css/landing-page.css
  index.html
Labels: needs-triage

#3755 add missing PipsPager generatd file
  dev/Generated/PipsPager.properties.cpp
  dev/Generated/PipsPager.properties.h
  dev/Generated/PipsPagerAutomationPeer.properties.cpp
  dev/Generated/PipsPagerTemplateSettings.properties.cpp
  dev/Generated/PipsPagerTemplateSettings.properties.h
Labels: area-PipsPager, auto merge, team-Controls

#3760 add missing PipsPager generatd file
  dev/Generated/PipsPager.properties.cpp
  dev/Generated/PipsPager.properties.h
  dev/Generated/PipsPagerAutomationPeer.properties.cpp
  dev/Generated/PipsPagerTemplateSettings.properties.cpp
  dev/Generated/PipsPagerTemplateSettings.properties.h
Labels: auto merge, needs-triage

#3765 Anawish/website security updates
  about.html
  css/landing-page.css
  index.html
Labels: needs-triage

#3757 Update UpdateAppxFilesInNupkg.ps1
  build/FrameworkPackage/UpdateAppxFilesInNupkg.ps1
Labels: area-DevInternal, team-Controls

#3754 Updates to localization strings
  dev/RatingControl/Strings/bg-BG/Resources.resw
  dev/RatingControl/Strings/cs-CZ/Resources.resw
  dev/RatingControl/Strings/de-DE/Resources.resw
  dev/RatingControl/Strings/ka-GE/Resources.resw
  dev/RatingControl/Strings/sk-SK/Resources.resw
  dev/RatingControl/Strings/th-TH/Resources.resw
  dev/RatingControl/Strings/tr-TR/Resources.resw
  dev/RatingControl/Strings/vi-VN/Resources.resw
  dev/RatingControl/Strings/zh-TW/Resources.resw
Labels: area-NugetPackage

#3703 TeachingTip: Fix tip being included in tab order
  dev/TeachingTip/APITests/TeachingTipTests.cs
  dev/TeachingTip/InteractionTests/TeachingTipFocusTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTestPageElements.cs
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/InteractionTests/TeachingTip_InteractionTests.projitems
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TeachingTipAutomationPeer.cpp
  dev/TeachingTip/TeachingTipAutomationPeer.h
  dev/TeachingTip/TeachingTipClosedEventArgs.cpp
  dev/TeachingTip/TeachingTipClosedEventArgs.h
  dev/TeachingTip/TeachingTipClosingEventArgs.cpp
  dev/TeachingTip/TeachingTipClosingEventArgs.h
  dev/TeachingTip/TeachingTipTestHooks.cpp
  dev/TeachingTip/TeachingTipTestHooks.h
  dev/TeachingTip/TeachingTip_rs1_themeresources.xaml
  dev/TeachingTip/TeachingTip_rs2_themeresources.xaml
  dev/TeachingTip/TestUI/TeachingTipCaseBundle.xaml
  dev/TeachingTip/TestUI/TeachingTipCaseBundle.xaml.cs
  dev/TeachingTip/TestUI/TeachingTipFocusPage.xaml
  dev/TeachingTip/TestUI/TeachingTipFocusPage.xaml.cs
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
  dev/TeachingTip/TestUI/TeachingTip_TestUI.projitems
Labels: area-TeachingTip, team-Controls

#3788 Fixing incremental build after changing XAML files (take 2)
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: area-DevInternal, team-Controls

#3699 ItemsRepeater: Fix bug where inserting at front would result in unrendered items
  dev/Repeater/APITests/FlowLayoutCollectionChangeTests.cs
  dev/Repeater/ElementManager.cpp
  dev/Repeater/InteractionTests/RepeaterTests.cs
  dev/Repeater/TestUI/Samples/BasicDemo.xaml
  dev/Repeater/TestUI/Samples/BasicDemo.xaml.cs
Labels: area-ItemsRepeater, team-Controls

#3201 Progressbar: Fix issue with color changing when updating value while error state
  dev/CommonStyles/CommonStyles.vcxitems
  dev/ProgressBar/InteractionTests/ProgressBarTests.cs
  dev/ProgressBar/ProgressBar.cpp
  dev/ProgressBar/ProgressBar.h
  dev/ProgressBar/ProgressBar.vcxitems
  dev/ProgressBar/ProgressBar.xaml
  dev/ProgressBar/ProgressBar_themeresources.xaml
Labels: area-Progress, team-Controls

#3799 Switch to ESRP signing for Release builds
  build/AzurePipelinesTemplates/MUX-CreateNugetPackage-Job.yml
  build/FrameworkPackageSignConfig.xml
  build/MUX-Release.yml
  build/NuGetSignConfig.xml
  build/NuGetSignConfigFinalRelease.xml
  build/SignConfig.xml
Labels: area-DevInternal, team-Controls

#3756 Fix RadioButtons colouring bug
  dev/CommonStyles/RadioButton_themeresources.xaml
Labels: area-RadioButtons, team-Controls

#3768 Slider Visual Update
  dev/Slider/Slider_themeresources.xaml
Labels: area-Slider, team-Controls
