Repository microsoft/microsoft-ui-xaml, pull requests merged in 2020-01, with the labels that each got.

#1802 Fix bug with UniformGridLayout MaximumRowsOrColumns and requested size
  dev/Repeater/APITests/FlowLayoutTests.cs
  dev/Repeater/UniformGridLayout.cpp
Labels: area-ItemsRepeater, team-Controls

#1608 ProgressRing Initial Commit
  FeatureAreas.props
  InnerLoopAreas.props
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/Generated/ProgressRing.properties.cpp
  dev/Generated/ProgressRing.properties.h
  dev/ProgressBar/ProgressBar.xaml
  dev/ProgressRing/InteractionTests/ProgressRingTests.cs
  dev/ProgressRing/InteractionTests/ProgressRing_InteractionTests.projitems
  dev/ProgressRing/InteractionTests/ProgressRing_InteractionTests.shproj
  dev/ProgressRing/ProgressRing.cpp
  dev/ProgressRing/ProgressRing.h
  dev/ProgressRing/ProgressRing.idl
  dev/ProgressRing/ProgressRing.vcxitems
  dev/ProgressRing/ProgressRing.xaml
  dev/ProgressRing/ProgressRing_themeresources.xaml
  dev/ProgressRing/TestUI/ProgressRingPage.xaml
  dev/ProgressRing/TestUI/ProgressRingPage.xaml.cs
  dev/ProgressRing/TestUI/ProgressRing_TestUI.projitems
  dev/ProgressRing/TestUI/ProgressRing_TestUI.shproj
  dev/Telemetry/RuntimeProfiler.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/inc/CppWinRTIncludes.h
  test/MUXControls.Test/MUXControls.Test.Shared.targets
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: area-Progress, feature proposal, release note, team-Controls

#1799 Fix TreeView single selection
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TestUI/TreeViewPage.xaml
  dev/TreeView/TestUI/TreeViewPage.xaml.cs
  dev/TreeView/TreeView.cpp
  dev/TreeView/TreeView.h
  dev/TreeView/TreeViewItem.cpp
Labels: area-TreeView

#1663 Improve theming of TabView in High Contrast mode
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.xaml
  dev/TabView/TabView_themeresources.xaml
  dev/TabView/TestUI/TabViewPage.xaml
  dev/TabView/TestUI/TabViewPage.xaml.cs
Labels: area-TabView, release note, team-Controls

#1816 Disable unreliable test
  dev/Repeater/APITests/RepeaterTests.cs
Labels: area-ItemsRepeater, auto merge, team-Controls

#1822 Update to use new SpanningRects API instead of DisplayRegions.
  dev/TwoPaneView/DisplayRegionHelper.cpp
  dev/TwoPaneView/DisplayRegionHelper.h
  dev/TwoPaneView/TwoPaneView.cpp
  dev/TwoPaneView/TwoPaneView.h
  dev/TwoPaneView/TwoPaneView.idl
  dev/dll/SharedHelpers.cpp
  dev/dll/pch.h
  dev/inc/SharedHelpers.h
Labels: area-TwoPaneView, team-Controls

#1800 Fix bug where NavViewItem would report wrong type for UIA
  dev/NavigationView/NavigationViewItemAutomationPeer.cpp
  dev/NavigationView/NavigationViewItemAutomationPeer.h
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
Labels: area-NavigationView, auto merge, team-Controls

#1788 Fix bug where transition from LeftMinimal/LeftCompact to LeftCompact opens pane of NavigationView
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
Labels: area-NavigationView, team-Controls

#1831 RadialGradientBrush initial commit
  FeatureAreas.props
  InnerLoopAreas.props
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/Generated/RadialGradientBrush.properties.cpp
  dev/Generated/RadialGradientBrush.properties.h
  dev/RadialGradientBrush/InteractionTests/RadialGradientBrushTests.cs
  dev/RadialGradientBrush/InteractionTests/RadialGradientBrush_InteractionTests.projitems
  dev/RadialGradientBrush/InteractionTests/RadialGradientBrush_InteractionTests.shproj
  dev/RadialGradientBrush/RadialGradientBrush.cpp
  dev/RadialGradientBrush/RadialGradientBrush.h
  dev/RadialGradientBrush/RadialGradientBrush.idl
  dev/RadialGradientBrush/RadialGradientBrush.vcxitems
  dev/RadialGradientBrush/TestUI/RadialGradientBrushPage.xaml
  dev/RadialGradientBrush/TestUI/RadialGradientBrushPage.xaml.cs
  dev/RadialGradientBrush/TestUI/RadialGradientBrush_TestUI.projitems
  dev/RadialGradientBrush/TestUI/RadialGradientBrush_TestUI.shproj
  dev/Telemetry/RuntimeProfiler.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/SharedHelpers.cpp
  dev/inc/CppWinRTIncludes.h
  dev/inc/SharedHelpers.h
  test/MUXControls.Test/MUXControls.Test.Shared.targets
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: feature proposal, needs-triage, release note, team-Rendering

#1843 fix new project script and update feature area props file.
  FeatureAreas.props
  test/MUXControls.Test/MUXControls.Test.Shared.targets
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
  tools/GenerateNewControlProject.ps1
Labels: needs-triage

#1845 Make TabItems as content property of TabView
  dev/TabView/TabView.idl
  dev/TabView/TestUI/TabViewPage.xaml
Labels: needs-triage

#1864 Fix broken link
  docs/code_style_and_conventions.md
Labels: needs-triage

#1759 ProgressBar Indeterminate Animation Update
  dev/CommonStyles/ProgressBar_themeresources.xaml
  dev/Generated/ProgressBarTemplateSettings.properties.cpp
  dev/Generated/ProgressBarTemplateSettings.properties.h
  dev/Generated/ProgressRing.properties.cpp
  dev/ProgressBar/InteractionTests/ProgressBarTests.cs
  dev/ProgressBar/ProgressBar.cpp
  dev/ProgressBar/ProgressBar.h
  dev/ProgressBar/ProgressBar.idl
  dev/ProgressBar/ProgressBar.xaml
  dev/ProgressBar/TestUI/ProgressBarPage.xaml
  dev/ProgressBar/TestUI/ProgressBarPage.xaml.cs
Labels: area-Progress, needs-cherrypicktorelease, team-Controls

#1878 CppWinRT workaround for compiler issue in latest VS 16.4.3
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  dev/inc/CppWinRTIncludes.h
Labels: area-DevInternal, team-Controls

#1886 Fix issue with multiple resets causing a crash due to duplicate keys.
  dev/Repeater/APITests/InspectingDataSourceTests.cs
  dev/Repeater/UniqueIdElementPool.h
  dev/Repeater/ViewManager.cpp
Labels: area-ItemsRepeater, team-Controls

#1911 Re-enable RS3 test pass
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
Labels: needs-triage

#1917 Update TreeViewNode expand state when ItemsSource changes
  dev/TreeView/InteractionTests/TreeViewTests.cs
  dev/TreeView/TestUI/TreeViewPage.xaml
  dev/TreeView/TestUI/TreeViewPage.xaml.cs
  dev/TreeView/TreeViewItem.cpp
Labels: area-TreeView
