Repository microsoft/microsoft-ui-xaml, pull requests merged in 2021-08, with the labels that each got.

#5558 NavigationView TopNav: fix insertion bug and improve top nav performance/fix flyout positioning
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/SplitDataSourceBase.h
Labels: area-NavigationView, team-Controls

#5532 Basic Infobadge.
  FeatureAreas.props
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/Generated/InfoBadge.properties.cpp
  dev/Generated/InfoBadge.properties.h
  dev/Generated/InfoBadgeTemplateSettings.properties.cpp
  dev/Generated/InfoBadgeTemplateSettings.properties.h
  dev/IconSource/IconSource.cpp
  dev/InfoBadge/APITests/InfoBadgeTests.cs
  dev/InfoBadge/APITests/InfoBadge_APITests.projitems
  dev/InfoBadge/APITests/InfoBadge_APITests.shproj
  dev/InfoBadge/InfoBadge.cpp
  dev/InfoBadge/InfoBadge.h
  dev/InfoBadge/InfoBadge.idl
  dev/InfoBadge/InfoBadge.vcxitems
  dev/InfoBadge/InfoBadge.xaml
  dev/InfoBadge/InfoBadgeTemplateSettings.cpp
  dev/InfoBadge/InfoBadgeTemplateSettings.h
  dev/InfoBadge/InfoBadge_themeresources.xaml
  dev/InfoBadge/InteractionTests/InfoBadge_InteractionTests.projitems
  dev/InfoBadge/InteractionTests/InfoBadge_InteractionTests.shproj
  dev/InfoBadge/TestUI/InfoBadgePage.xaml
  dev/InfoBadge/TestUI/InfoBadgePage.xaml.cs
  dev/InfoBadge/TestUI/InfoBadge_TestUI.projitems
  dev/InfoBadge/TestUI/InfoBadge_TestUI.shproj
  dev/Telemetry/RuntimeProfiler.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControls.Test/MUXControls.Test.Shared.targets
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: area-InfoBadge, team-Controls

#5609 Fix yml pool name conditional
  build/MUX-CI.yml
  build/MUX-PGOInstrument.yml
  build/MUX-PR.yml
  build/MUX-Release.yml
  build/MUX-SimpleBuildAndTest.yml
Labels: area-DevInternal

#5588 Fix Time Picker's place holder content not showing in high contrast mode
  dev/CommonStyles/TimePicker_themeresources.xaml
Labels: needs-cherrypicktorelease, needs-triage

#5595 add NavViewContentMinimalMargin + adjust PaneContent cornerRadius
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
Labels: area-NavigationView, team-Controls

#5618 Stop using Package ES pools
  build/AzurePipelinesTemplates/MUX-PushCBSVpack-Job.yml
  build/MUX-LocalizationHandoff.yml
Labels: area-DevInternal, team-Controls

#3426 TabViewItem: Fix header not being used when set to null or the empty string
  MUXControlsInnerLoop.sln
  dev/TabView/APITests/TabViewTests.cs
  dev/TabView/TabView.xaml
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
  dev/TabView/TabView_v1.xaml
Labels: area-TabView, team-Controls

#5628 Fix Misplaced 3rd Party IME Popup for AutoSuggestBox
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/AutoSuggestBox/AutoSuggestBox_themeresources_v1.xaml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
Labels: needs-cherrypicktorelease, needs-triage, team-Controls, area-AutoSuggestBox

#5359 [UniformGridLayout] Fix bug where controls would not know their limitations when being evaluated for layouting
  dev/Repeater/APITests/Common/AspectRatioRespectingControl.cs
  dev/Repeater/APITests/FlowLayoutTests.cs
  dev/Repeater/APITests/Repeater_APITests.projitems
  dev/Repeater/TestUI/Samples/ItemsSourceSamples/ElementsInItemsSourcePage.xaml
  dev/Repeater/TestUI/Samples/UniformGridLayoutDemo.cs
  dev/Repeater/TestUI/Samples/UniformGridLayoutDemo.xaml
  dev/Repeater/UniformGridLayoutState.cpp
  dev/Repeater/UniformGridLayoutState.h
Labels: area-ItemsRepeater, needs-cherrypicktorelease, team-Controls

#5648 Fix toggle switch off pressed border color.
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
Labels: team-Controls, area-ToggleSwitch

#5631 Add 8px Padding to Left and Right Caret
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView_themeresources.xaml
Labels: area-NavigationView, area-UIDesign, team-Controls

#5649 Update patch version to 2.6.2
  version.props
Labels: needs-triage

#5619 TopNavView OverFlow Items Incorrect Foreground Colour Fix
  dev/NavigationView/NavigationView.xaml
Labels: area-NavigationView, team-Controls

#5663 loc update
  dev/NavigationView/Strings/ar-SA/Resources.resw
Labels: needs-triage

#5669 Fix source indexing to enable source debugging for official builds.
  build/SourceIndexing/IndexPdbs.ps1
  tools/InternalWindowsSDKNuget/SetUpInternalWindowsSDK.cmd
Labels: needs-triage

#5671 Fix link to WinUI 3 feature roadmap
  docs/roadmap.md
Labels: documentation, product-winui3

#5693 Add 21H1 to bug report list
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: area-DevInternal

#5681 Fixing SwipeControl mem leaks
  dev/SwipeControl/SwipeControl.cpp
  dev/SwipeControl/SwipeControl.h
  dev/SwipeControl/SwipeControl.vcxitems
  dev/SwipeControl/SwipeControlInteractionTrackerOwner.cpp
  dev/SwipeControl/SwipeControlInteractionTrackerOwner.h
  dev/SwipeControl/SwipeControl_TestUI/SwipeControlPage.xaml
  dev/SwipeControl/SwipeControl_TestUI/SwipeControlPage.xaml.cs
Labels: area-SwipeControl, needs-cherrypicktorelease, A11yHighimpact

#5453 Add ColorPicker Orientation spec
  specs/ColorPicker/ColorPicker.Orientation.md
  specs/ColorPicker/images/ColorPicker_HorizontalMode.png
  specs/ColorPicker/images/ColorPicker_VerticalMode.png
Labels: area-ColorPicker, team-Controls

#5687 Override SourceLink to always point at GitHub
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: area-NugetPackage, area-DevInternal

#5701 Update Version Number to 2.7.0!
  build/NuSpecs/MUXControls-Nuget-FrameworkPackage.props
  dev/inc/BuildMacros.h
  version.props
Labels: area-NugetPackage, team-Controls

#5711 Run build for MUXControlsReleaseTest on WinDevPool-S instead of windows-2019
  build/AzurePipelinesTemplates/MUX-NugetReleaseTest-Job.yml
Labels: needs-triage

#5754 Fix ARM build break from WebView2 changes
  test/MUXControlsReleaseTest/LibraryThatUsesMUX/LibraryThatUsesMUX.csproj
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.vcxproj
  test/TestAppCX/MainPage.xaml.cpp
  test/TestAppCX/TestAppCX.vcxproj
Labels: needs-triage
