Repository microsoft/microsoft-ui-xaml, pull requests merged in 2021-07, with the labels that each got.

#5329 Breadcrumb: make ellipsis inaccessible by Accessibility tools when it's hidden
  dev/Breadcrumb/BreadcrumbBar.cpp
  dev/Breadcrumb/InteractionTests/BreadcrumbBarTests.cs
Labels: area-Breadcrumb, team-Controls

#5331 NumberBox SpinButton Inline Overlap Fix
  dev/CommonStyles/TestUI/BorderThicknessPage.xaml
  dev/NumberBox/NumberBox.cpp
  dev/NumberBox/NumberBox.h
  dev/NumberBox/NumberBox.xaml
  dev/NumberBox/NumberBox_themeresources.xaml
Labels: area-NumberBox, team-Controls

#5349 Fix initial flow direction not being applied to Animated Icon.
  dev/AnimatedIcon/AnimatedIcon.cpp
  dev/AnimatedIcon/TestUI/AnimatedIconPage.xaml
Labels: area-AnimatedIcon, team-Controls

#5351 Updates SurfaceStrokeColorDefault color value
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/CommonStyles/ContentDialog_themeresources.xaml
Labels: area-Styling

#5352 [ContentDialog] Make min/max width/height resource ThemeResources, use ThemeResource binding
  dev/CommonStyles/ContentDialog_themeresources.xaml
Labels: area-Dialogs, team-Controls

#5353 Slider: fix thumb cut off and wrong colored patch of color
  dev/CommonStyles/Slider_themeresources.xaml
Labels: area-Slider, needs-triage, team-Controls

#5379 Fixing WinUI 2.6 store certification error
  build/NuSpecs/MUXControls-Nuget-Common.targets
Labels: area-DevInternal, team-Controls

#5382 update version.props to 2.6.1
  version.props
Labels: area-NugetPackage, team-Controls

#5383 Fix for crash in BackdropMaterialState event callback
  dev/Materials/Backdrop/BackdropMaterial.cpp
Labels: needs-triage

#5376 ProgressBar: fix Error color persistence after showError has been toggled
  dev/ProgressBar/ProgressBar.xaml
Labels: area-Progress, team-Controls

#5323 Revert MenuFlyoutItem placeholder margin to ThemeResource in Version2 styles
  dev/CommonStyles/MenuFlyout_themeresources.xaml
Labels: area-Menus, team-Controls

#5347 Avoid CommandBarFlyoutCommandBar clipping after dynamic command bar element change
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/CommandBarFlyout.h
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.h
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml.cs
Labels: area-Commanding, team-Controls

#5389 Changing labels in design toolkit bug template
  .github/ISSUE_TEMPLATE/winui-toolkit-bug-report.md
Labels: documentation

#5378 Allow Command Bar Flyout to change sizes based on input device used
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
  test/MUXControlsTestApp/Themes/DisableAnimationsStylesOutsideStore_rs2.xaml
Labels: area-Commanding, team-Controls

#5321 Move object default properties into the constructor
  dev/CommonStyles/TestUI/CommandBarPage.xaml
  dev/Generated/FontIconSource.properties.cpp
  dev/IconSource/FontIconSource.cpp
  dev/IconSource/IconSource.idl
Labels: area-DevInternal, team-Controls

#5401 Updating link in README
  README.md
Labels: documentation

#5432 Slider: give focus rect rounded corners
  dev/CommonStyles/Slider_themeresources.xaml
Labels: area-Slider, needs-triage, team-Controls

#5433 Fix issue where CommandbarFlyout's overflow items are too small with mouse.
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
Labels: area-Commanding, team-Controls

#5430 [NuGet] Ensure the buildTransitive folder is in sync with the build folder.
  build/NuSpecs/MUXControls.nuspec
Labels: needs-triage

#5431 Merge SplitView_themeresources.xaml files
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/Deprecated_themeresources_any.xaml
  dev/CommonStyles/SplitView_themeresources.xaml
  dev/SplitView/SplitView_themeresources.xaml
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: area-NavigationView, team-Controls

#5447 InkToolBar: add missing visual states to CustomToggleButton
  dev/CommonStyles/InkToolbar_themeresources.xaml
Labels: area-InkToolBar, needs-triage, team-Controls

#5458 CalendarView control: Allow longer week day labels without wrapping
  dev/CommonStyles/CalendarView_themeresources_21h1.xaml
  dev/CommonStyles/TestUI/CalendarViewPage.xaml
  dev/CommonStyles/TestUI/CalendarViewPage.xaml.cs
Labels: area-DateTimePickers, team-Controls

#5415 Fix CommandBarFlyout crashing down level
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  test/MUXControlsTestApp/Themes/DisableAnimationsStylesOutsideStore_rs2.xaml
Labels: area-Commanding, team-Controls

#5469 Fix CommandBarFlyout flashing in high contrast
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
Labels: accessibility, area-Commanding, team-Controls

#5467 Fix NavigationView Flash in Compact Dark Theme
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-5.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-6.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
Labels: area-NavigationView, team-Controls

#5485 ScrollBar: fix hover/pressed hc color for arrow buttons.
  dev/CommonStyles/ScrollBar_themeresources.xaml
Labels: area-ScrollBar, area-UIDesign, needs-triage

#5496 Move to 1ES Build Pool
  build/MUX-CI.yml
  build/MUX-PR.yml
  build/MUX-Release.yml
  build/MUX-SimpleBuildAndTest.yml
Labels: needs-triage

#5494 Add backplate to CommandBarFlyout in high contrast.
  MUXControls.sln
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
Labels: area-Commanding, area-Styling, team-Controls

#5471 Fix a couple compiler warnings
  dev/dll/SharedHelpers.cpp
  dev/dll/XamlMember.h
  dev/dll/XamlType.cpp
Labels: area-DevInternal, team-Controls

#5509 Update API spec discussions docs to point to the correct repo
  CONTRIBUTING.md
Labels: documentation

#5145 Make tab corner overlays update colors
  dev/TabView/TabView.xaml
  dev/TabView/TabView_v1.xaml
Labels: area-TabView, team-Controls

#5098 Fix ring ColorSpectrum border
  dev/ColorPicker/ColorSpectrum.xaml
  dev/ColorPicker/ColorSpectrum_v1.xaml
Labels: area-ColorPicker, area-UIDesign, team-Controls

#4856 API spec template
  specs/api_spec_template.md
Labels: documentation

#5512 More localization updates
  dev/RatingControl/Strings/uz-Latn-UZ/Resources.resw
  dev/TabView/Strings/uz-Latn-UZ/Resources.resw
Labels: needs-triage

#5527 Website: updating code to get latest header/footer
  about.html
  index.html
  index.js
Labels: needs-triage

#5524 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, team-Controls

#5517 Feature roadmap updates
  docs/roadmap.md
Labels: documentation, product-winui3

#5564 Pipeline Failure Workaround: Exclude WpfApp.Package.WapProj
  test/MUXControlsReleaseTest/MUXControlsReleaseTest.sln
Labels: area-DevInternal, needs-triage

#5562 Window::get_SystemBackdrop null ref exception workaround
  dev/Materials/Backdrop/MicaController.cpp
Labels: needs-triage

#5531 NavView Minimal Pane Sometimes Transparent OnLoad / OnWindowResize
  dev/NavigationView/NavigationView.cpp
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
Labels: area-NavigationView, team-Controls

#5526 Add null check for top pane title
  dev/NavigationView/NavigationView.cpp
Labels: area-NavigationView, team-Controls

#5565 InkToolbar: update custom pen button style
  dev/CommonStyles/InkToolbar_themeresources.xaml
Labels: area-InkToolBar, team-Controls

#5594 Switch Helix pool for PGO Pipeline
  build/AzurePipelinesTemplates/MUX-BuildAndPublishPGONuGet-Job.yml
  build/MUX-PGOInstrument.yml
Labels: needs-triage
