Repository microsoft/microsoft-ui-xaml, pull requests merged in 2021-11, with the labels that each got.

#6032 Add ExpanderToggleButton Children to Peer
  MUXControls.sln
  dev/Expander/APITests/ExpanderTests.cs
  dev/Expander/APITests/Expander_APITests.projitems
  dev/Expander/APITests/Expander_APITests.shproj
  dev/Expander/APITests/Expander_APITests.testsettings
  dev/Expander/ExpanderAutomationPeer.cpp
  dev/Expander/Expander_themeresources.xaml
  dev/Expander/InteractionTests/ExpanderTests.cs
  dev/Expander/TestUI/ExpanderPage.xaml
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: team-Controls, area-Expander

#6221 Adding more lightweight styling to AppBarButton
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/CommonStyles/AppBarButton_themeresources.xaml
Labels: area-Commanding, team-Controls

#6226 Add WACK testing for Windows Application Packaging Project with FullTrustProcess
  build/AzurePipelinesTemplates/MUX-WACKTests-Job.yml
  test/MUXControlsReleaseTest/MUXControlsReleaseTest.sln
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/FullTrustProcess/App.config
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/FullTrustProcess/FullTrustProcess.csproj
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/FullTrustProcess/Program.cs
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/FullTrustProcess/Properties/AssemblyInfo.cs
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/App.xaml
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/App.xaml.cs
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/Assets/Unused_Square150x150Logo.scale-200.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/Assets/Unused_Square44x44Logo.scale-200.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/Assets/Unused_Square44x44Logo.targetsize-24_altform-unplated.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/Assets/Unused_StoreLogo.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/MainPage.xaml
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/MainPage.xaml.cs
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/Package.appxmanifest
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/Properties/AssemblyInfo.cs
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/Properties/Default.rd.xml
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess.csproj
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/Assets/LockScreenLogo.scale-200.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/Assets/SplashScreen.scale-200.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/Assets/Square150x150Logo.scale-200.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/Assets/Square44x44Logo.scale-200.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/Assets/StoreLogo.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/Assets/Wide310x150Logo.scale-200.png
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/Package.appxmanifest
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess_package/UwpAppWithFullTrustProcess_package.wapproj
Labels: area-DevInternal, team-Controls

#6228 [ Calendar DatePicker ] [ HC ] Style updates (remainder x2)
  dev/CommonStyles/CalendarDatePicker_themeresources.xaml
  dev/CommonStyles/DatePicker_themeresources.xaml
  dev/CommonStyles/DateTimePickerFlyout_themeresources.xaml
  dev/CommonStyles/TimePicker_themeresources.xaml
Labels: area-Styling, area-DateTimePickers, team-Controls

#6227 NavView IsPaneVisible Fix
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationViewItemPresenter.cpp
  dev/NavigationView/NavigationView_InteractionTests/PaneBehaviorTests.cs
Labels: area-NavigationView, team-Controls

#6240 Fix NavigationViewCrash with the attached revokers object pattern during cleanup.
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
Labels: area-NavigationView, team-Controls

#6145 NumberBox to Announce Min/Max Values
  dev/NumberBox/APITests/NumberBoxTests.cs
  dev/NumberBox/NumberBox.cpp
  dev/NumberBox/Strings/en-US/Resources.resw
  dev/ResourceHelper/ResourceAccessor.h
Labels: area-NumberBox, team-Controls, area-Accessibility

#6044 Exclude MoreButton if Not using PrimaryCommands
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml.cs
Labels: area-Commanding, team-Controls

#6266 [ContentDialog] Update background smoke for HC
  dev/CommonStyles/ContentDialog_themeresources.xaml
Labels: needs-triage

#6265 MUX Experimental: Remove hard-coded package version from GetLocalizedStringResourceFromWinUI
  build/CopyFilesToStagingDir.ps1
  dev/ResourceHelper/ResourceAccessor.cpp
Labels: needs-triage

#6274 Localization Update
  dev/NumberBox/Strings/af-ZA/Resources.resw
  dev/NumberBox/Strings/am-ET/Resources.resw
  dev/NumberBox/Strings/ar-SA/Resources.resw
  dev/NumberBox/Strings/az-Latn-AZ/Resources.resw
  dev/NumberBox/Strings/bg-BG/Resources.resw
  dev/NumberBox/Strings/bs-Latn-BA/Resources.resw
  dev/NumberBox/Strings/ca-ES/Resources.resw
  dev/NumberBox/Strings/da-DK/Resources.resw
  dev/NumberBox/Strings/el-GR/Resources.resw
  dev/NumberBox/Strings/en-GB/Resources.resw
  dev/NumberBox/Strings/es-ES/Resources.resw
  dev/NumberBox/Strings/es-MX/Resources.resw
  dev/NumberBox/Strings/eu-ES/Resources.resw
  dev/NumberBox/Strings/fa-IR/Resources.resw
  dev/NumberBox/Strings/fi-FI/Resources.resw
  dev/NumberBox/Strings/hr-HR/Resources.resw
  dev/NumberBox/Strings/hu-HU/Resources.resw
  dev/NumberBox/Strings/id-ID/Resources.resw
  dev/NumberBox/Strings/ja-JP/Resources.resw
  dev/NumberBox/Strings/ka-GE/Resources.resw
  dev/NumberBox/Strings/kk-KZ/Resources.resw
  dev/NumberBox/Strings/km-KH/Resources.resw
  dev/NumberBox/Strings/ko-KR/Resources.resw
  dev/NumberBox/Strings/lo-LA/Resources.resw
  dev/NumberBox/Strings/lt-LT/Resources.resw
  dev/NumberBox/Strings/lv-LV/Resources.resw
  dev/NumberBox/Strings/mk-MK/Resources.resw
  dev/NumberBox/Strings/ml-IN/Resources.resw
  dev/NumberBox/Strings/ms-MY/Resources.resw
  dev/NumberBox/Strings/nl-NL/Resources.resw
  dev/NumberBox/Strings/nn-NO/Resources.resw
  dev/NumberBox/Strings/pl-PL/Resources.resw
  dev/NumberBox/Strings/pt-BR/Resources.resw
  dev/NumberBox/Strings/ro-RO/Resources.resw
  dev/NumberBox/Strings/ru-RU/Resources.resw
  dev/NumberBox/Strings/sq-AL/Resources.resw
  dev/NumberBox/Strings/sr-Latn-RS/Resources.resw
  dev/NumberBox/Strings/th-TH/Resources.resw
  dev/NumberBox/Strings/uz-Latn-UZ/Resources.resw
  dev/NumberBox/Strings/vi-VN/Resources.resw
  dev/NumberBox/Strings/zh-CN/Resources.resw
  dev/NumberBox/Strings/zh-TW/Resources.resw
Labels: needs-triage

#6243 Rename appbar button chevron font size resource.
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/CommonStyles/AppBarButton_themeresources.xaml
Labels: area-Commanding, area-Styling, team-Controls

#6211 TeachingTip F6 focus in xaml island fix.
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
Labels: area-TeachingTip, team-Controls

#5219 Tweaks to Rainbow Backgrounds on CommandBarFlyout and MenuFlyout TestUI pages
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
  dev/CommonStyles/TestUI/CommandBarPage.xaml
  dev/CommonStyles/TestUI/MenuFlyoutPage.xaml
Labels: area-TestInfrastructure, area-Commanding, team-Controls

#5736 [ContentDialog] Add missing visibility setter for V2 style
  dev/CommonStyles/ContentDialog_themeresources.xaml
  test/MUXControlsTestApp/verification/ContentDialog-5.xml
  test/MUXControlsTestApp/verification/ContentDialog-6.xml
  test/MUXControlsTestApp/verification/ContentDialog-7.xml
  test/MUXControlsTestApp/verification/ContentDialog-8.xml
Labels: area-Dialogs, team-Controls

#6164 Fix WebView2 navigation with non-ascii URIs
  build/ShouldSkipPRBuild.ps1
  dev/WebView2/InteractionTests/WebView2Tests.cs
  dev/WebView2/TestUI/WebView2BasicPage.xaml
  dev/WebView2/TestUI/WebView2BasicPage.xaml.cs
  dev/WebView2/WebView2.cpp
  test/MUXControlsTestApp/Assets/SimplePageWithNonÅscií.html
Labels: area-WebView, team-Rendering

#6296 WebView2 hides cursor if it stops getting input
  dev/WebView2/WebView2.cpp
Labels: needs-triage

#6298 localization update
  dev/NumberBox/Strings/cs-CZ/Resources.resw
  dev/NumberBox/Strings/de-DE/Resources.resw
  dev/NumberBox/Strings/et-EE/Resources.resw
  dev/NumberBox/Strings/fil-PH/Resources.resw
  dev/NumberBox/Strings/fr-CA/Resources.resw
  dev/NumberBox/Strings/fr-FR/Resources.resw
  dev/NumberBox/Strings/gl-ES/Resources.resw
  dev/NumberBox/Strings/he-IL/Resources.resw
  dev/NumberBox/Strings/hi-IN/Resources.resw
  dev/NumberBox/Strings/is-IS/Resources.resw
  dev/NumberBox/Strings/it-IT/Resources.resw
  dev/NumberBox/Strings/kn-IN/Resources.resw
  dev/NumberBox/Strings/nb-NO/Resources.resw
  dev/NumberBox/Strings/pt-PT/Resources.resw
  dev/NumberBox/Strings/sk-SK/Resources.resw
  dev/NumberBox/Strings/sl-SI/Resources.resw
  dev/NumberBox/Strings/sv-SE/Resources.resw
  dev/NumberBox/Strings/ta-IN/Resources.resw
  dev/NumberBox/Strings/te-IN/Resources.resw
  dev/NumberBox/Strings/tr-TR/Resources.resw
  dev/NumberBox/Strings/uk-UA/Resources.resw
Labels: area-DevInternal, team-Controls

#6288 [Mica] Fix crash accessing BaseWindowHandler::m_capabilities from Capabilities::Changed handler
  dev/Materials/Backdrop/MicaController.cpp
  dev/Materials/Backdrop/MicaController.h
  dev/Materials/Backdrop/SystemBackdropWindowHandler.cpp
  dev/Materials/Backdrop/SystemBackdropWindowHandler.h
Labels: area-Materials, team-Rendering

#6317 Fix NavigationViewItem attempting to go to a non existant reveal state.
  dev/NavigationView/NavigationViewItem.cpp
Labels: area-NavigationView, team-Controls

#6326 [Experimental TitleBar] Collapse TitleText when empty
  dev/TitleBar/TitleBar.cpp
  dev/TitleBar/TitleBar.h
  dev/TitleBar/TitleBar.idl
  dev/TitleBar/TitleBar.xaml
Labels: needs-triage

#6282 TabViewItem: Make background of the selected tab all one path
  dev/Generated/TabViewItemTemplateSettings.properties.cpp
  dev/Generated/TabViewItemTemplateSettings.properties.h
  dev/TabView/TabView.idl
  dev/TabView/TabView.xaml
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
Labels: area-TabView, team-Controls

#6332 TabView: Separate border lines into being everywhere except the selected tab
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TabView.h
  dev/TabView/TabView.xaml
  dev/TabView/TabViewListView.cpp
  dev/TabView/TabViewListView.h
  dev/TabView/TabView_themeresources.xaml
  dev/TabView/TestUI/TabViewPage.xaml
  dev/TabView/TestUI/TabViewPage.xaml.cs
Labels: needs-triage

#6287 Update debugging_crashes.md
  docs/debugging_crashes.md
Labels: auto merge, needs-triage

#6348 Add code of conduct to readme.
  README.md
Labels: team-Controls

#6356 Bug report template is missing WinAppSDK 1.0
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: needs-triage

#6373 Always return true for API version checks originating from the CBS package.
  dev/dll/SharedHelpers.cpp
Labels: area-DevInternal, team-Controls
