Repository microsoft/microsoft-ui-xaml, pull requests merged in 2021-02, with the labels that each got.

#3938 Combobox visual updates
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommonStyles/TestUI/CommonStylesPage.xaml.cs
  dev/dll/DensityStyles/Compact.xaml
  test/MUXControlsTestApp/verification/ComboBox-4.xml
  test/MUXControlsTestApp/verification/ComboBox-5.xml
  test/MUXControlsTestApp/verification/ComboBox-6.xml
  test/MUXControlsTestApp/verification/ComboBox-7.xml
  test/MUXControlsTestApp/verification/ComboBox-8.xml
Labels: area-ComboBox, team-Controls

#4073 Change the default used ComboBoxItem style
  dev/Materials/Reveal/RevealBrush_rs2_themeresources.xaml
Labels: area-ComboBox, team-Controls

#4060 PipsPager control visual updates
  dev/PipsPager/PipsPager_themeresources.xaml
  dev/PipsPager/TestUI/PipsPagerExamples.xaml
Labels: area-PipsPager, team-Controls

#4077 Tooltip visual updates
  dev/ToolTip/ToolTip_rs5_themeresources.xaml
Labels: needs-triage

#4031 Fix Scroll Bar thumb hit area
  dev/ScrollBar/ScrollBar_themeresources.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
  test/MUXControlsTestApp/verification/TreeView-4.xml
  test/MUXControlsTestApp/verification/TreeView-7.xml
Labels: area-ScrollBar, team-Controls

#4076 Flyout padding fix
  dev/CommonStyles/FlyoutPresenter_themeresources.xaml
  dev/CommonStyles/TestUI/CommonStylesPage.xaml
  dev/ContentDialog/ContentDialog_themeresources.xaml
  dev/ContentDialog/TestUI/ContentDialogPage.xaml
  dev/Expander/Expander.xaml
  dev/MenuFlyout/MenuFlyout_themeresources.xaml
Labels: area-Flyouts, area-Styling, area-UIDesign, team-Controls

#4084 Update feature roadmap
  docs/images/winui-roadmap.jpg
  docs/roadmap.md
Labels: needs-triage

#4081 Adding ability to run MUX-CI.yml with internal pipeline & Windows SDK
  SdkVersion.props
  build/AzurePipelinesTemplates/MUX-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-InstallWindowsSDK-Steps.yml
  tools/InternalWindowsSDKNuget/MergeNupkgParts.cmd
  tools/InternalWindowsSDKNuget/NuSpecs/BuildNupkgs.cmd
  tools/InternalWindowsSDKNuget/NuSpecs/InternalWindowsSDK-part1.nuspec
  tools/InternalWindowsSDKNuget/NuSpecs/InternalWindowsSDK-part2.nuspec
  tools/InternalWindowsSDKNuget/NuSpecs/PublishNupkgs.cmd
  tools/InternalWindowsSDKNuget/SetUpInternalWindowsSDK.cmd
Labels: area-DevInternal, needs-triage

#4080 Fix solution file entries
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/PipsPager/TestUI/PipsPager_TestUI.projitems
  test/MUXControls.Test/MUXControls.Test.Shared.targets
Labels: area-DevInternal

#4091 Update accent line under TextBox controls
  dev/CommonStyles/TextBox_themeresources.xaml
Labels: area-Styling, area-TextBox, area-UIDesign, team-Controls

#4101 Update UWP row in feature roadmap
  docs/roadmap.md
Labels: needs-triage

#4115 Disable PackageES DFS in Pipelines
  build/MUX-LocalizationHandoff.yml
  build/MUX-Release.yml
Labels: area-DevInternal, team-Controls

#4063 Add October 2020 Update to OS matrix
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, team-Controls

#4117 Revert "Disable PackageES DFS in Pipelines"
  build/MUX-LocalizationHandoff.yml
  build/MUX-Release.yml
Labels: area-DevInternal, team-Controls

#4104 Update Common and Expander theme resources to always use latest
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/Common_themeresources.xaml
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/Expander/Expander.vcxitems
  dev/Expander/Expander_themeresources_v2.5.xaml
Labels: area-NugetPackage, area-Resources, team-Controls

#4132 Update roadmap.md
  docs/roadmap.md
Labels: needs-triage

#4072 Consolidate to one nuget feed.
  build/AzurePipelinesTemplates/MUX-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-NugetReleaseTest-Job.yml
  build/Localization/NuGet.Config
  build/MUX-CI.yml
  build/MUX-NugetReleaseTest.yml
  build/MUX-PGOInstrument.yml
  build/MUX-PR.yml
  build/MUX-Release.yml
  dev/Microsoft.UI.Xaml.FrameworkPackagePRI/Microsoft.UI.Xaml.FrameworkPackagePRI.csproj
  nuget.config
  test/MUXControlsReleaseTest/build/SpkgDefs/MUXControls.ReleaseTest.pkg.xml
  test/MUXControlsReleaseTest/build/TRexDefs/amd64/ci_TrexConfig.xml
  test/MUXControlsReleaseTest/build/TRexDefs/x86/ci_TrexConfig.xml
  test/MUXControlsReleaseTest/localpackages/readme.md
  test/MUXControlsReleaseTest/nuget.config
  tools/PublishPackageToArcade/PublishPackageToArcade.yml
  tools/PublishPackageToArcade/PublishPackagesToArcade.csproj
  tools/PublishPackageToArcade/PublishPackagesToArcade.sln
  tools/PublishPackageToArcade/nuget.config
  tools/PublishPackageToArcade/packages.config
Labels: area-NugetPackage, team-Controls

#4130 Disable DFS - take two!
  build/MUX-LocalizationHandoff.yml
  build/MUX-Release.yml
  tools/PublishSymbols/PublishSymbols.ps1
  tools/PublishSymbols/pdb_index_template.ini
Labels: needs-triage

#4131 Restore deteled SingleSTateSegmentLookup doc file.
  dev/AnimatedIcon/Docs/SingleStateSegmentLookup.md
Labels: area-AnimatedIcon, documentation, team-Controls

#4134 ScrollBar: Update delay before collapsing
  dev/ScrollBar/ScrollBar_themeresources.xaml
Labels: area-ScrollBar, team-Controls

#4142 RuntimeProfiler: catch the exception in case application instance is null
  dev/Telemetry/RuntimeProfiler.cpp
Labels: area-DevInternal, team-Controls

#4128 Adding HyperlinkUnderlineVisible resource for Hyperlink(Button)
  dev/CommonStyles/Hyperlink_themeresources.xaml
  dev/CommonStyles/ListViewItem_themeresources_21h1.xaml
  dev/CommonStyles/TestUI/CommonStylesPage.xaml
Labels: area-HyperlinkButton, team-Controls

#4089 Fix various command bar issues.
  dev/CommonStyles/AppBarButton_themeresources.xaml
  dev/CommonStyles/AppBarSeparator_themeresources.xaml
  dev/CommonStyles/AppBarToggleButton_themeresources.xaml
  dev/CommonStyles/CommandBar_themeresources.xaml
Labels: area-Commanding, area-Styling, area-UIDesign, team-Controls

#4148 Expander: Move to public
  dev/Expander/Expander.idl
Labels: area-Expander, team-Controls

#4155 Adding Preview 4 links
  about.html
  index.html
Labels: needs-triage

#4154 Anawish/preview4 updates
  docs/preview_upgrade_instructions.md
Labels: needs-triage

#4157 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#4162 BackgroundSizign audit
  dev/CalendarView/CalendarView_themeresources.xaml
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
  dev/DatePicker/DateTimePickerFlyout_themeresources.xaml
Labels: area-Styling, team-Controls

#4178 Updating upgrade instructions with correct nuget package #
  docs/preview_upgrade_instructions.md
Labels: needs-triage

#3430 NavigationViewItem: Empty tooltip no longer shown
  dev/NavigationView/NavigationViewItem.cpp
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
Labels: area-NavigationView, team-Controls

#4079 Update ContentDialog ThemeResources - Fixing transition visual artifact
  dev/ContentDialog/ContentDialog_themeresources.xaml
Labels: area-ContentDialog, team-Controls

#3824 NavigationView: Update template docs
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/docs/rendering.md
Labels: area-NavigationView, documentation, team-Controls

#4103 Moving UWP support row in feature roadmap
  docs/roadmap.md
Labels: documentation

#4159 Expander visual update [2/2]
  dev/Expander/Expander.cpp
  dev/Expander/Expander.h
  dev/Expander/Expander.idl
  dev/Expander/Expander.vcxitems
  dev/Expander/Expander.xaml
  dev/Expander/ExpanderTemplateSettings.cpp
  dev/Expander/ExpanderTemplateSettings.h
  dev/Expander/Expander_themeresources.xaml
  dev/Expander/TestUI/ExpanderPage.xaml
  dev/Generated/Expander.properties.cpp
  dev/Generated/Expander.properties.h
  dev/Generated/ExpanderTemplateSettings.properties.cpp
  dev/Generated/ExpanderTemplateSettings.properties.h
Labels: area-Expander, area-Styling, team-Controls

#4129 Use fluent icons new codepoints for datepicker, timepicker, flipview, scrollbar, pipspage
  dev/CalendarView/CalendarView.vcxitems
  dev/CalendarView/CalendarView_21h1_themeresources.xaml
  dev/CalendarView/CalendarView_themeresources.xaml
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/Common_21h1_themeresources.xaml
  dev/CommonStyles/Common_themeresources.xaml
  dev/FlipView/FlipView_themeresources.xaml
  dev/PipsPager/PipsPager.vcxitems
  dev/PipsPager/PipsPager_21h1_themeresources.xaml
  dev/ScrollBar/ScrollBar_themeresources.xaml
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: area-Styling, area-UIDesign, team-Controls

#4211 Updating README to say "Preview 4"
  README.md
Labels: documentation

#4094 Fix issue with pagercontrol suffix label incorrect
  dev/ResourceHelper/ResourceAccessor.h
Labels: area-Pager, team-Controls

#4170 PipsPager: API Update
  dev/Generated/PipsPager.properties.cpp
  dev/Generated/PipsPager.properties.h
  dev/Generated/PipsPagerTemplateSettings.properties.cpp
  dev/Generated/PipsPagerTemplateSettings.properties.h
  dev/PipsPager/APITests/PipsPagerTests.cs
  dev/PipsPager/InteractionTests/PipsPagerTestBase.cs
  dev/PipsPager/InteractionTests/PipsPagerTests.cs
  dev/PipsPager/PipsPager.cpp
  dev/PipsPager/PipsPager.h
  dev/PipsPager/PipsPager.idl
  dev/PipsPager/PipsPager.vcxitems
  dev/PipsPager/PipsPager.xaml
  dev/PipsPager/PipsPagerTemplateSettings.h
  dev/PipsPager/PipsPager_themeresources.xaml
  dev/PipsPager/PipsPager_themeresources_v2.5.xaml
  dev/PipsPager/PipsPager_v2.5.xaml
  dev/PipsPager/TestUI/PipsPagerExamples.xaml
  dev/PipsPager/TestUI/PipsPagerExamples.xaml.cs
  dev/PipsPager/TestUI/PipsPagerPage.xaml
  dev/PipsPager/TestUI/PipsPagerPage.xaml.cs
Labels: area-PipsPager, team-Controls

#4227 fix colors regressed from old styles
  dev/CommonStyles/Common_themeresources.xaml
  dev/CommonStyles/Common_themeresources_any.xaml
Labels: needs-triage

#4141 Add null check to ItemsRepeater.GetOrCreateElement
  dev/Repeater/APITests/RepeaterTests.cs
  dev/Repeater/ItemsRepeater.cpp
Labels: area-ItemsRepeater, team-Controls

#4210 Adding documentation on APIs no longer supported in Desktop
  docs/winrt-apis-for-desktop.md
Labels: documentation, preview4, winui3preview

#4168 Color values update
  dev/CommonStyles/Common_themeresources_any.xaml
  test/MUXControlsTestApp/verification/CalendarView-4.xml
  test/MUXControlsTestApp/verification/CalendarView-5.xml
  test/MUXControlsTestApp/verification/CalendarView-6.xml
  test/MUXControlsTestApp/verification/CalendarView-7.xml
  test/MUXControlsTestApp/verification/CalendarView-8.xml
Labels: area-Styling

#4231 PipsPager: add new themeresources to vcxitems
  dev/PipsPager/PipsPager.vcxitems
Labels: area-PipsPager, team-Controls

#4158 Progress bar visual update
  dev/ProgressBar/InteractionTests/ProgressBarTests.cs
  dev/ProgressBar/ProgressBar.xaml
  dev/ProgressBar/ProgressBar_themeresources.xaml
  dev/ProgressBar/TestUI/ProgressBarPage.xaml
  dev/ProgressBar/TestUI/ProgressBarPage.xaml.cs
  dev/ProgressBar/TestUI/ProgressBarReTemplatePage.xaml
  dev/ProgressBar/TestUI/ProgressBarReTemplatePage.xaml.cs
Labels: area-Progress, team-Controls

#4245 Small change to WinRT API doc
  docs/winrt-apis-for-desktop.md
Labels: documentation

#4108 Add new TextBlock styles
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/TestUI/CommonStyles_TestUI.projitems
  dev/CommonStyles/TestUI/TextControlsPage.xaml
  dev/CommonStyles/TestUI/TextControlsPage.xaml.cs
  dev/CommonStyles/TextBlock_themeresources.xaml
  dev/CommonStyles/TextBlock_themeresources_v2.5.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-5.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-6.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
Labels: area-TextBlocks, team-Controls

#4250 Update elevation strokes
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
Labels: area-UIDesign, team-Controls

#3966 TabView: Add scrolling into view on selection
  dev/TabView/TabViewItem.cpp
Labels: area-TabView, team-Controls

#4259 Adding more to WinRT API changes doc
  docs/winrt-apis-for-desktop.md
Labels: documentation, winui3preview

#4281 Move ImageIcon and ImageIconSource out of preview.
  dev/IconSource/IconSource.idl
  dev/ImageIcon/ImageIcon.idl
Labels: area-ImageIcon, team-Controls

#4090 [Breadcrumb] Update Breadcrumb API, design and interaction tests
  dev/Breadcrumb/APITests/BreadcrumbTests.cs
  dev/Breadcrumb/Breadcrumb.cpp
  dev/Breadcrumb/Breadcrumb.h
  dev/Breadcrumb/Breadcrumb.idl
  dev/Breadcrumb/Breadcrumb.vcxitems
  dev/Breadcrumb/Breadcrumb.xaml
  dev/Breadcrumb/BreadcrumbAutomationPeer.idl
  dev/Breadcrumb/BreadcrumbDropDownElementFactory.cpp
  dev/Breadcrumb/BreadcrumbDropDownElementFactory.h
  dev/Breadcrumb/BreadcrumbDropDownItem.cpp
  dev/Breadcrumb/BreadcrumbDropDownItem.h
  dev/Breadcrumb/BreadcrumbDropDownItemAutomationPeer.cpp
  dev/Breadcrumb/BreadcrumbDropDownItemAutomationPeer.h
  dev/Breadcrumb/BreadcrumbElementFactory.cpp
  dev/Breadcrumb/BreadcrumbItem.cpp
  dev/Breadcrumb/BreadcrumbItem.h
  dev/Breadcrumb/BreadcrumbItemAutomationPeer.cpp
  dev/Breadcrumb/BreadcrumbItemAutomationPeer.h
  dev/Breadcrumb/BreadcrumbItemClickedEventArgs.cpp
  dev/Breadcrumb/BreadcrumbItemClickedEventArgs.h
  dev/Breadcrumb/BreadcrumbIterable.cpp
  dev/Breadcrumb/BreadcrumbIterator.cpp
  dev/Breadcrumb/BreadcrumbLayout.cpp
  dev/Breadcrumb/BreadcrumbLayout.h
  dev/Breadcrumb/Breadcrumb_themeresources.xaml
  dev/Breadcrumb/InteractionTests/BreadcrumbTests.cs
  dev/Breadcrumb/Strings/en-us/Resources.resw
  dev/Breadcrumb/TestUI/BreadcrumbPage.xaml
  dev/Breadcrumb/TestUI/BreadcrumbPage.xaml.cs
  dev/Breadcrumb/TestUI/TreeStructure.cs
  dev/Generated/Breadcrumb.properties.cpp
  dev/Generated/Breadcrumb.properties.h
  dev/Generated/BreadcrumbDropDownItem.properties.cpp
  dev/Generated/BreadcrumbDropDownItemAutomationPeer.properties.cpp
  dev/Generated/BreadcrumbItemAutomationPeer.properties.cpp
  dev/ResourceHelper/ResourceAccessor.h
  dev/Telemetry/RuntimeProfiler.h
Labels: area-Breadcrumb, team-Controls

#4267 Improve helix failure resilience with API call retries
  build/Helix/AzurePipelinesHelperScripts.ps1
  build/Helix/OutputTestResults.ps1
  build/Helix/ProcessHelixFiles.ps1
  build/Helix/UpdateUnreliableTests.ps1
Labels: area-TestInfrastructure, team-Controls

#3996 PipsPager: Update focus behavior so that the selected item will be focused when tabbing in pips area
  dev/PipsPager/InteractionTests/PipsPagerElements.cs
  dev/PipsPager/InteractionTests/PipsPagerTestBase.cs
  dev/PipsPager/InteractionTests/PipsPagerTests.cs
  dev/PipsPager/PipsPager.cpp
  dev/PipsPager/PipsPager.h
  dev/PipsPager/TestUI/PipsPagerPage.xaml
  dev/PipsPager/TestUI/PipsPagerPage.xaml.cs
Labels: area-PipsPager, team-Controls

#4263 Layer color resource update
  dev/CommonStyles/Common_themeresources_any.xaml
Labels: area-UIDesign, team-Controls

#4312 User/almedina ms/bc remove ap
  dev/Breadcrumb/Breadcrumb_themeresources.xaml
Labels: needs-triage

#4309 [Breadcrumb] Merge AutomationProperties and fix flyout crash
  dev/Breadcrumb/Breadcrumb.vcxitems
  dev/Breadcrumb/BreadcrumbItem.cpp
  dev/Breadcrumb/BreadcrumbItem.h
  dev/Breadcrumb/EllipsisItemsSource.cpp
  dev/Breadcrumb/EllipsisItemsSource.h
Labels: needs-triage

#4261 Remove tilt animations
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  dev/CommonStyles/ListViewItem_themeresources.xaml
  dev/CommonStyles/ListViewItem_themeresources_21h1.xaml
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
  dev/DropDownButton/DropDownButton_rs1.xaml
  dev/MenuFlyout/MenuFlyout_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs1_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs2_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs4_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs5_themeresources.xaml
  dev/TabView/TabView.xaml
Labels: area-UIDesign, team-Controls

#4319 Add tests
  dev/Breadcrumb/InteractionTests/BreadcrumbTests.cs
Labels: needs-triage

#4324 Remove ellipsis itemsSource flyout fix
  dev/Breadcrumb/Breadcrumb.vcxitems
  dev/Breadcrumb/BreadcrumbItem.cpp
  dev/Breadcrumb/BreadcrumbItem.h
  dev/Breadcrumb/EllipsisItemsSource.cpp
  dev/Breadcrumb/EllipsisItemsSource.h
  dev/Breadcrumb/InteractionTests/BreadcrumbTests.cs
Labels: needs-triage

#4310 Unification of BreadcrumbItem and BreadcrumbDropDownItem
  dev/Breadcrumb/APITests/BreadcrumbTests.cs
  dev/Breadcrumb/Breadcrumb.cpp
  dev/Breadcrumb/Breadcrumb.h
  dev/Breadcrumb/Breadcrumb.idl
  dev/Breadcrumb/Breadcrumb.vcxitems
  dev/Breadcrumb/Breadcrumb.xaml
  dev/Breadcrumb/BreadcrumbAutomationPeer.idl
  dev/Breadcrumb/BreadcrumbDropDownElementFactory.cpp
  dev/Breadcrumb/BreadcrumbDropDownElementFactory.h
  dev/Breadcrumb/BreadcrumbDropDownItem.cpp
  dev/Breadcrumb/BreadcrumbDropDownItem.h
  dev/Breadcrumb/BreadcrumbDropDownItemAutomationPeer.cpp
  dev/Breadcrumb/BreadcrumbDropDownItemAutomationPeer.h
  dev/Breadcrumb/BreadcrumbElementFactory.cpp
  dev/Breadcrumb/BreadcrumbItem.cpp
  dev/Breadcrumb/BreadcrumbItem.h
  dev/Breadcrumb/Breadcrumb_themeresources.xaml
  dev/Breadcrumb/InteractionTests/BreadcrumbTests.cs
  dev/Breadcrumb/TestUI/BreadcrumbPage.xaml
  dev/Breadcrumb/TestUI/BreadcrumbPage.xaml.cs
  dev/Generated/Breadcrumb.properties.cpp
  dev/Generated/Breadcrumb.properties.h
Labels: area-Breadcrumb, team-Controls

#4326 Fix Expander's tab order
  dev/Expander/Expander.xaml
  dev/Expander/TestUI/ExpanderPage.xaml
Labels: area-Expander, team-Controls

#4294 Updates to animation timing and easing
  dev/CalendarView/CalendarView_themeresources.xaml
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommandBarFlyout/CommandBarFlyout.xaml
  dev/CommonStyles/AppBarButton_themeresources.xaml
  dev/CommonStyles/AppBarToggleButton_themeresources.xaml
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/CommonStyles/RadioButton_themeresources.xaml
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
  dev/ContentDialog/ContentDialog_themeresources.xaml
  dev/DropDownButton/DropDownButton.xaml
  dev/Slider/Slider_themeresources.xaml
Labels: area-UIDesign, team-Controls

#4330 changes for drop shadows
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
Labels: area-Shadows, team-Controls

#4217 Add contract attributes to enable stable ABI versioning
  idl/Microsoft.UI.Xaml.idl
Labels: area-NugetPackage, team-Controls

#4315 Move MUX Effects to private namespace
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/ColorPicker/SpectrumBrush.cpp
  dev/ColorPicker/SpectrumBrush.h
  dev/Effects/Microsoft.UI.Private.Composition.Effects.vcxitems
  dev/Effects/microsoft.ui.private.composition.effects.idl
  dev/Effects/microsoft.ui.private.composition.effects_impl.h
  dev/Lights/RevealBorderLight.cpp
  dev/Lights/RevealHoverLight.cpp
  dev/Lights/XamlAmbientLight.cpp
  dev/Materials/Acrylic/AcrylicBrush.cpp
  dev/Materials/Acrylic/AcrylicBrush.h
  dev/Materials/Reveal/RevealBrush.cpp
  dev/dll/CppWinRTFilterTypes.tt
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/inc/CppWinRTIncludes.h
  idl/Effects.idl
  tools/CheckCompatibility.ps1
Labels: area-DevInternal, team-Controls

#4340 ListViewItem contentAlignment update
  dev/CommonStyles/ListViewItem_themeresources_21h1.xaml
Labels: area-Lists, needs-triage, team-Controls

#4311 Removing reveal from controls
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
  dev/TabView/TabView.xaml
  dev/TreeView/TreeViewItem.xaml
  test/MUXControlsTestApp/verification/TreeView-4.xml
  test/MUXControlsTestApp/verification/TreeView-7.xml
Labels: area-UIDesign, team-Controls

#4313 Add Version and StylesVersion back
  dev/Generated/XamlControlsResources.properties.cpp
  dev/Generated/XamlControlsResources.properties.h
  dev/dll/XamlControlsResources.cpp
  idl/Microsoft.UI.Xaml.idl
Labels: area-Styling, team-Controls

#4336 Add guidelines for contributing feature requests, ideas, and other feedback
  CONTRIBUTING_feedback_and_requests.md
Labels: documentation

#4348 Mark expander automation peer public
  dev/Expander/ExpanderAutomationPeer.idl
Labels: area-Expander, team-Controls

#4323 Tweaks to TextBox and CommandBar
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/CommonStyles/Common_themeresources.xaml
  dev/CommonStyles/PasswordBox_themeresources.xaml
  dev/CommonStyles/RichEditBox_themeresources.xaml
  dev/CommonStyles/TestUI/CommandBarPage.xaml
  dev/CommonStyles/TestUI/CommonStylesPage.xaml.cs
  dev/CommonStyles/TextBox_themeresources.xaml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
Labels: area-Commanding, area-Styling, area-TextBlocks, area-TextBox, team-Controls

#4344 update breadcrumb api naming
  MUXControls.sln
  dev/Breadcrumb/APITests/BreadcrumbBar_APITests.shproj
  dev/Breadcrumb/APITests/BreadcrumbTests.cs
  dev/Breadcrumb/Breadcrumb.vcxitems
  dev/Breadcrumb/BreadcrumbAutomationPeer.idl
  dev/Breadcrumb/BreadcrumbBar.cpp
  dev/Breadcrumb/BreadcrumbBar.h
  dev/Breadcrumb/BreadcrumbBar.idl
  dev/Breadcrumb/BreadcrumbBar.xaml
  dev/Breadcrumb/BreadcrumbBarAutomationPeer.idl
  dev/Breadcrumb/BreadcrumbBarElementFactory.cpp
  dev/Breadcrumb/BreadcrumbBarElementFactory.h
  dev/Breadcrumb/BreadcrumbBarItem.cpp
  dev/Breadcrumb/BreadcrumbBarItem.h
  dev/Breadcrumb/BreadcrumbBarItemAutomationPeer.cpp
  dev/Breadcrumb/BreadcrumbBarItemAutomationPeer.h
  dev/Breadcrumb/BreadcrumbBarItemClickedEventArgs.cpp
  dev/Breadcrumb/BreadcrumbBarItemClickedEventArgs.h
  dev/Breadcrumb/BreadcrumbBar_themeresources.xaml
  dev/Breadcrumb/BreadcrumbItemAutomationPeer.cpp
  dev/Breadcrumb/BreadcrumbItemClickedEventArgs.cpp
  dev/Breadcrumb/BreadcrumbLayout.cpp
  dev/Breadcrumb/BreadcrumbLayout.h
  dev/Breadcrumb/Breadcrumb_themeresources.xaml
  dev/Breadcrumb/InteractionTests/BreadcrumbBarTests.cs
  dev/Breadcrumb/InteractionTests/BreadcrumbBar_InteractionTests.shproj
  dev/Breadcrumb/InteractionTests/Breadcrumb_InteractionTests.projitems
  dev/Breadcrumb/Strings/en-us/Resources.resw
  dev/Breadcrumb/TestUI/BreadcrumbBarPage.xaml
  dev/Breadcrumb/TestUI/BreadcrumbBarPage.xaml.cs
  dev/Breadcrumb/TestUI/BreadcrumbBar_TestUI.shproj
  dev/Breadcrumb/TestUI/Breadcrumb_TestUI.projitems
  dev/Generated/Breadcrumb.properties.cpp
  dev/Generated/BreadcrumbBar.properties.cpp
  dev/Generated/BreadcrumbBar.properties.h
  dev/Generated/BreadcrumbBarItem.properties.cpp
  dev/Generated/BreadcrumbBarItemAutomationPeer.properties.cpp
  dev/ResourceHelper/ResourceAccessor.h
  dev/Telemetry/RuntimeProfiler.h
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
Labels: area-Breadcrumb, team-Controls

#4349 Make pips pager automation peer public
  dev/PipsPager/PipsPagerAutomationPeer.idl
Labels: area-PipsPager, team-Controls

#4271 Add InApp acrylic brush resources
  dev/Materials/Acrylic/AcrylicBrush_19h1_themeresources.xaml
  dev/Materials/Acrylic/AcrylicBrush_rs1_themeresources.xaml
  dev/Materials/Acrylic/AcrylicBrush_rs2_themeresources.xaml
  dev/dll/XamlControlsResources.cpp
Labels: area-Materials, team-Controls

#4295 Add CreateIconElement to IconSource
  dev/AnimatedIcon/AnimatedIcon.cpp
  dev/IconSource/AnimatedIconSource.cpp
  dev/IconSource/AnimatedIconSource.h
  dev/IconSource/BitmapIconSource.cpp
  dev/IconSource/BitmapIconSource.h
  dev/IconSource/FontIconSource.cpp
  dev/IconSource/FontIconSource.h
  dev/IconSource/IconSource.cpp
  dev/IconSource/IconSource.h
  dev/IconSource/IconSource.idl
  dev/IconSource/ImageIconSource.cpp
  dev/IconSource/ImageIconSource.h
  dev/IconSource/PathIconSource.cpp
  dev/IconSource/PathIconSource.h
  dev/IconSource/SymbolIconSource.cpp
  dev/IconSource/SymbolIconSource.h
  dev/InfoBar/InfoBar.cpp
  dev/SwipeControl/SwipeItem.cpp
  dev/TabView/TabViewItem.cpp
  dev/TeachingTip/TeachingTip.cpp
  dev/dll/CommandingHelpers.cpp
  dev/dll/SharedHelpers.cpp
  dev/inc/SharedHelpers.h
Labels: area-Icon, team-Controls

#4342 PipsPager style tweaks
  dev/PipsPager/PipsPager_themeresources.xaml
Labels: area-PipsPager, area-Styling, area-UIDesign, team-Controls

#4355 Update NavigationView TemplateSettings API Names
  dev/Generated/NavigationViewItemPresenterTemplateSettings.properties.cpp
  dev/Generated/NavigationViewItemPresenterTemplateSettings.properties.h
  dev/Generated/NavigationViewTemplateSettings.properties.cpp
  dev/Generated/NavigationViewTemplateSettings.properties.h
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.idl
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationViewItemPresenter.cpp
  dev/NavigationView/NavigationViewItemPresenter.idl
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/NavigationView/NavigationView_rs1_themeresources_v1.xaml
  dev/NavigationView/NavigationView_v1.xaml
Labels: area-NavigationView, team-Controls

#4359 Adding DefaultGridViewItemStyle for pre-21H1 OS versions
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/GridViewItem_themeresources.xaml
  dev/CommonStyles/TestUI/CommonStylesPage.xaml
Labels: area-Lists, team-Controls

#4317 RadioMenuFlyoutItem update
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem.vcxitems
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs2_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs4_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs5_themeresources.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_themeresources.xaml
Labels: area-UIDesign, team-Controls

#4354 Remove MUXIgnoredByCodeGenAttribute from Microsoft.UI.Xaml
  idl/Microsoft.UI.Xaml.idl
Labels: area-DevInternal, team-Controls

#4357 update the animated icon slider scenario to use a more appropriate AnimatedVisual
  dev/AnimatedIcon/TestUI/AnimatedIconPage.xaml
  dev/AnimatedIcon/TestUI/AnimatedIcon_TestUI.projitems
  dev/AnimatedIcon/TestUI/BrightnessSun.cs
Labels: area-AnimatedIcon, team-Controls

#4361 Add AnimatedIcon to SplitButton
  dev/SplitButton/SplitButton.xaml
Labels: area-Styling, team-Controls

#4365 Updating roadmap image to Preview 4
  docs/images/winui-roadmap.jpg
Labels: needs-triage

#4345 Removing of AnimationRoot and TiltContainer
  dev/CommonStyles/ListViewItem_themeresources.xaml
  dev/CommonStyles/ListViewItem_themeresources_21h1.xaml
  dev/MenuFlyout/MenuFlyout_themeresources.xaml
Labels: area-Lists, area-Menus, area-UIDesign, team-Controls

#4358 [Breadcrumb] Add and modify style for ellipsis item flyout
  dev/Breadcrumb/BreadcrumbBar.xaml
  dev/Breadcrumb/BreadcrumbBarItem.cpp
  dev/Breadcrumb/BreadcrumbBar_themeresources.xaml
Labels: area-Breadcrumb, area-UIDesign, team-Controls

#3770 Innerloop: Add missing TabView API test project
  MUXControlsInnerLoop.sln
Labels: area-DevInternal, area-TabView, team-Controls

#4372 Color value fix
  dev/CommonStyles/Common_themeresources_any.xaml
Labels: area-Styling

#4279 Update the nuget readme with instructions of how to do app level overrides of Winui2 resources.
  build/NuSpecs/readme.txt
Labels: documentation, team-Controls
