Repository microsoft/microsoft-ui-xaml, pull requests merged in 2021-03, with the labels that each got.

#4381 Updating README with a link to new contribution guidelines
  README.md
Labels: needs-triage

#4387 Don't package compact themeresources to framework package
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: needs-triage

#4343 Updating TabView to consume DropShadows
  dev/TabView/TabView.cpp
  dev/TabView/TabViewItem.cpp
Labels: area-Shadows, area-TabView, area-UIDesign, team-Controls

#4392 Remove the rd.xml work around
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/Properties/Default.rd.xml
  test/MUXControlsReleaseTest/NugetPackageTestApp/Properties/Default.rd.xml
Labels: area-AnimatedIcon, team-Controls

#4406 Updated Localization Key Handling
  build/Localization/LocalizationAutomation.proj
  build/MUX-LocalizationHandoff.yml
  tools/VSTSRunLocWorkflow.cmd
Labels: area-DevInternal, team-Controls

#4400 Remove rs2-19h1 theme resources from CBS package
  build/FrameworkPackage/MakeFrameworkPackage.ps1
  build/FrameworkPackage/cbspriconfig.xml
Labels: area-NugetPackage

#4404 Update CommandBarOpen Background to InApp Acrylic
  dev/CommonStyles/CommandBar_themeresources.xaml
Labels: area-Commanding, area-UIDesign, team-Controls

#4429 Upgrading internal Windows SDK from version 10.0.21307 to 10.0.21330
  SdkVersion.props
  tools/InternalWindowsSDKNuget/MergeNupkgParts.cmd
  tools/InternalWindowsSDKNuget/NuSpecs/InternalWindowsSDK-part1.nuspec
  tools/InternalWindowsSDKNuget/NuSpecs/InternalWindowsSDK-part2.nuspec
  tools/InternalWindowsSDKNuget/SetUpInternalWindowsSDK.cmd
Labels: area-DevInternal, team-Controls

#4435 Updates flyout border color resource
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/Breadcrumb/BreadcrumbBar_themeresources.xaml
  dev/CommonStyles/FlyoutPresenter_themeresources.xaml
  dev/DatePicker/DatePicker_themeresources.xaml
  dev/MenuFlyout/MenuFlyout_themeresources.xaml
  dev/NumberBox/NumberBox_themeresources.xaml
  dev/TimePicker/TimePicker_themeresources.xaml
  dev/ToolTip/ToolTip_rs1_themeresources.xaml
  dev/ToolTip/ToolTip_rs5_themeresources.xaml
Labels: area-Styling

#4432 Remove absolute file path from mux vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj
Labels: area-DevInternal, needs-triage, team-Controls

#4433 Add contract checks for a few properties in commandbar that are causing crashes in rs4 and below
  dev/CommonStyles/CommandBar_themeresources.xaml
Labels: area-Commanding, team-Controls

#4452 Fixing List/GridViewItem focus visuals
  dev/CommonStyles/GridViewItem_themeresources_21h1.xaml
  dev/CommonStyles/ListViewItem_themeresources_21h1.xaml
Labels: area-Lists, team-Controls

#4449 Change expander glyph size
  dev/Expander/Expander_themeresources.xaml
Labels: area-Expander, area-UIDesign, team-Controls

#4107 PipsPager: Make navigation buttons visible on focus
  dev/PipsPager/APITests/PipsPagerTests.cs
  dev/PipsPager/PipsPager.cpp
  dev/PipsPager/PipsPager.h
  dev/PipsPager/PipsPager.xaml
  dev/PipsPager/Strings/en-us/Resources.resw
  dev/PipsPager/TestUI/PipsPagerPage.xaml.cs
Labels: area-PipsPager, team-Controls

#3356 Fix issue with left right arrow key navigation of colorspectrum
  dev/ColorPicker/ColorSpectrum.cpp
  dev/ColorPicker/InteractionTests/ColorPickerTests.cs
Labels: area-ColorPicker, team-Controls

#4398 InfoBar theme updates
  dev/InfoBar/InfoBar.xaml
  dev/InfoBar/InfoBar_themeresources.xaml
  dev/InfoBar/TestUI/InfoBarPage.xaml
Labels: area-InfoBar, area-Styling, team-Controls

#4424 fix last breadcrumb item showing empty flyout issue
  dev/Breadcrumb/APITests/BreadcrumbTests.cs
  dev/Breadcrumb/BreadcrumbBar.xaml
  dev/Breadcrumb/BreadcrumbBarItem.cpp
  dev/Breadcrumb/BreadcrumbBarItem.h
Labels: area-Breadcrumb, team-Controls

#4451 Update color values to POR
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/Materials/Acrylic/AcrylicBrush_19h1_themeresources.xaml
  dev/Materials/Acrylic/AcrylicBrush_rs2_themeresources.xaml
  dev/dll/XamlControlsResources.cpp
  test/MUXControlsTestApp/verification/CalendarView-4.xml
  test/MUXControlsTestApp/verification/CalendarView-5.xml
  test/MUXControlsTestApp/verification/CalendarView-6.xml
  test/MUXControlsTestApp/verification/CalendarView-7.xml
  test/MUXControlsTestApp/verification/CalendarView-8.xml
Labels: area-Styling

#4322 Ensure we update the ClosedCompact visual state for NavigationViewItemPresenter when it applies its template.
  dev/NavigationView/NavigationViewItem.cpp
  dev/NavigationView/NavigationViewItem.h
  dev/NavigationView/NavigationView_ApiTests/NavigationViewTests.cs
Labels: area-NavigationView, team-Controls

#4471 Text/RichEditBox: Fix binding issue with foreground
  dev/CommonStyles/RichEditBox_themeresources.xaml
  dev/CommonStyles/RichEditBox_themeresources_v1.xaml
  dev/CommonStyles/TestUI/TextControlsPage.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
  dev/CommonStyles/TextBox_themeresources_v1.xaml
Labels: area-TextBlocks, area-TextBox

#4431 Add borderthickness binding to untargeted TeachingTip
  dev/TeachingTip/TeachingTip.xaml
Labels: area-TeachingTip, team-Controls

#4477 Update repo docs with latest WinUI 3 version
  README.md
  docs/roadmap.md
Labels: needs-triage

#4478 Updating website for Project Reunion 0.5 Preview
  WinUICommunityCall.ics
  about.html
  css/landing-page.css
  index.html
Labels: needs-triage

#4485 Add reunion release to the bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, needs-triage

#4476 Update to latest CppWinRT
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/packages.config
  test/testinfra/AppTestAutomationHelpers/AppTestAutomationHelpers.vcxproj
  test/testinfra/AppTestAutomationHelpers/packages.config
Labels: area-DevInternal, team-Controls

#4465 Visual fixes for a handful of controls
  dev/CommonStyles/ContentDialog_themeresources.xaml
  dev/CommonStyles/RadioButton_themeresources.xaml
Labels: area-Styling, team-Controls

#4464 Update AnimatedVisualSources
  dev/AnimatedIcon/AnimatedVisuals/AnimatedAcceptVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedAcceptVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedAcceptVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedBackVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedBackVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedBackVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronRightDownSmallVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronRightDownSmallVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronRightDownSmallVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronUpDownSmallVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronUpDownSmallVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronUpDownSmallVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedFindVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedFindVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedFindVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedGlobalNavigationButtonVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedGlobalNavigationButtonVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedGlobalNavigationButtonVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedSettingsVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedSettingsVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedSettingsVisualSource.idl
  dev/AnimatedIcon/TestUI/AnimatedIconPage.xaml
  dev/Effects/microsoft.ui.private.composition.effects_impl.h
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
  dev/dll/pch.h
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
Labels: area-AnimatedIcon, area-Styling, team-Controls

#4403 MediaTransportElement Background Fix
  FeatureAreas.props
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
  dev/CommonStyles/TestUI/CommonStyles_TestUI.projitems
  dev/CommonStyles/TestUI/MediaTransportControlsPage.xaml
  dev/CommonStyles/TestUI/MediaTransportControlsPage.xaml.cs
  test/MUXControlsTestApp/Assets/ladybug.wmv
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
Labels: area-MediaPlayerElement, team-Controls

#4475 Update ControlStroke brushes in dark mode
  dev/CommonStyles/Common_themeresources_any.xaml
Labels: area-UIDesign, team-Controls

#4469 NumberBox: Add property propagation
  dev/NumberBox/NumberBox.xaml
  dev/NumberBox/TestUI/NumberBoxPage.xaml
Labels: area-NumberBox, team-Controls

#4467 Adding system inktoolbar styles to winui
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/InkToolbar_themeresources.xaml
  dev/CommonStyles/InteractionTests/CommonStylesTests.cs
  dev/CommonStyles/TestUI/CommonStyles_TestUI.projitems
  dev/CommonStyles/TestUI/InkToolbarPage.xaml
  dev/CommonStyles/TestUI/InkToolbarPage.xaml.cs
Labels: area-Styling, team-Controls, team-Ink

#4502 Updating preview upgrade instructions
  docs/preview_upgrade_instructions.md
Labels: needs-triage

#3393 UniformGridLayout (FlowLayout): Fix issue with scrolling up creating gaps in layout
  dev/Repeater/FlowLayoutAlgorithm.cpp
  dev/Repeater/InteractionTests/RepeaterTests.cs
  dev/Repeater/TestUI/RepeaterTestUIPage.xaml
  dev/Repeater/TestUI/RepeaterTestUIPage.xaml.cs
  dev/Repeater/TestUI/Repeater_TestUI.projitems
  dev/Repeater/TestUI/Samples/UniformGridLayoutDemo.cs
  dev/Repeater/TestUI/Samples/UniformGridLayoutDemo.xaml
Labels: area-ItemsRepeater, team-Controls

#3397 TeachingTip: Fix bug where empty title/subtitle was not respected in ApplyTemplate leading to gap
  dev/TeachingTip/APITests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.xaml
Labels: area-TeachingTip, team-Controls

#4506 Removing use of ScrollViewerScrollBarMargin in test markup
  test/MUXControlsTestApp/App.xaml
  test/MUXControlsTestApp/Themes/DisableAnimationsStyles.xaml
Labels: area-ScrollBar, needs-triage, team-Controls

#4218 Fix WACK certification error for transitive WinUI references
  build/AzurePipelinesTemplates/MUX-NugetReleaseTest-Job.yml
  build/AzurePipelinesTemplates/MUX-WACKTests-Job.yml
  build/NuSpecs/MUXControls-Nuget-Common.targets
  build/NuSpecs/MUXControls-Nuget-FrameworkPackage.props
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/AppThatUsesMUXIndirectly.csproj
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/MainPage.xaml
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/MainPage.xaml.cs
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/MUXCInterfaceImplementation.cpp
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/MUXCInterfaceImplementation.h
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/MUXCInterfaceImplementation.idl
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/PropertySheet.props
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.def
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.native.targets
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.nuspec
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.sln
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.targets
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.vcxproj
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.vcxproj.filters
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX_TemporaryKey.pfx
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/packages.config
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/pch.cpp
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/pch.h
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/readme.txt
Labels: area-NugetPackage, auto merge, team-Controls

#4376 Updating ScrollViewer, FlipView, CalendarView, PipsPager to use carets
  dev/CommonStyles/CalendarView_21h1_themeresources.xaml
  dev/CommonStyles/CalendarView_themeresources.xaml
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/Common_21h1_themeresources.xaml
  dev/CommonStyles/Common_themeresources.xaml
  dev/CommonStyles/FlipView_themeresources.xaml
  dev/CommonStyles/ScrollBar_themeresources.xaml
  dev/PipsPager/PipsPager.vcxitems
  dev/PipsPager/PipsPager_21h1_themeresources.xaml
  dev/PipsPager/PipsPager_themeresources.xaml
  test/MUXControlsTestApp/verification/CalendarView-4.xml
  test/MUXControlsTestApp/verification/CalendarView-6.xml
  test/MUXControlsTestApp/verification/CalendarView-7.xml
Labels: area-UIDesign, team-Controls

#4488 Revert an unneeded project file change.
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
Labels: area-DevInternal, team-Controls

#4529 Fix MUXControls.ReleaseTest tests regression
  dev/CommonStyles/ScrollViewer_themeresources_v1.xaml
  test/MUXControlsTestApp/App.xaml
  test/MUXControlsTestApp/Themes/DisableAnimationsStyles.xaml
Labels: area-Scrolling, team-Controls

#4530 User/regisb/fix mux release pipeline fragility5
  tools/InternalWindowsSDKNuget/MergeNupkgParts.cmd
Labels: area-DevInternal, team-Controls

#4417 Add an example of how to use use animated icon within a content control that is not the direct (logical) child.
  dev/AnimatedIcon/TestUI/AnimatedIconPage.xaml
Labels: area-AnimatedIcon, team-Controls

#3988 Fix TabView selection
  dev/TabView/TabView.cpp
Labels: area-TabView, needs-author-feedback, team-Controls

#4539 Add down level corner rounding to checkboxes with the new style.
  dev/CommonStyles/CheckBox_themeresources.xaml
Labels: area-UIDesign, needs-triage, team-Controls

#4538 Removing unnecessary line from upgrade instructions
  docs/preview_upgrade_instructions.md
Labels: documentation, winui3preview

#4558 [CalendarDatePicker] Update Visual Style for Entry Point
  dev/CommonStyles/CalendarDatePicker_themeresources.xaml
Labels: area-DateTimePickers, area-Styling, team-Controls

#4524 Update AnimatedVisualSources with adjustments from design.
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronUpDownSmallVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronUpDownSmallVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronUpDownSmallVisualSource.idl
  dev/AnimatedIcon/AnimatedVisuals/AnimatedSettingsVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedSettingsVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedSettingsVisualSource.idl
Labels: area-AnimatedIcon, team-Controls

#4556 Fix issue where animated icon without a source set wouldn't show fallback icon.
  dev/AnimatedIcon/AnimatedIcon.cpp
  dev/AnimatedIcon/TestUI/AnimatedIconPage.xaml
Labels: area-AnimatedIcon, team-Controls

#4577 Disable unreliable test.
  dev/RadioButtons/InteractionTests/RadioButtonsTests.cs
Labels: area-TestInfrastructure, team-Controls

#4575 Fix for CommandBarFlyout foreground color
  dev/CommandBarFlyout/CommandBarFlyout.xaml
  dev/CommandBarFlyout/CommandBarFlyout_v1.xaml
Labels: area-Commanding, area-UIDesign, team-Controls

#4541 [FlipView] Update Visual Style
  dev/CommonStyles/FlipView_themeresources.xaml
Labels: area-UIDesign, team-Controls

#4589 Skip TDBuild artifact upload
  build/Localization/LocalizationAutomation.proj
Labels: area-DevInternal, team-Controls

#4588 Add ThemeResource to turn on drop shadows
  dev/CommonStyles/Common_themeresources.xaml
Labels: area-Shadows, team-Controls

#3776 TabView: Update padding binding
  dev/TabView/TabView.xaml
Labels: area-TabView, team-Controls

#4543 Update winrt-apis-for-desktop.md
  docs/winrt-apis-for-desktop.md
Labels: documentation

#3431 Fix misalign of NumberBox and AutoSuggestBox stretch
  dev/AutoSuggestBox/APITests/AutoSuggestBoxTests.cs
  dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml
  dev/NumberBox/NumberBox.xaml
  dev/NumberBox/NumberBox_v1.xaml
  dev/NumberBox/TestUI/NumberBoxPage.xaml
Labels: area-NumberBox, team-Controls

#4592 PipsPager scrolling fix event bubble up
  dev/PipsPager/PipsPager.cpp
  dev/PipsPager/PipsPager.h
Labels: area-PipsPager, needs-triage, team-Controls

#4615 Adjust commandbar margins and button sizing
  dev/CommonStyles/AppBarButton_themeresources.xaml
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/CommonStyles/TestUI/CommandBarPage.xaml
Labels: area-Commanding, team-Controls

#4586 Fix MUX CommandBar style not being applied to TextControl flyouts.
  dev/CommonStyles/Common_themeresources.xaml
Labels: area-Commanding, area-Styling, team-Controls

#4521 Update SystemFillColorAttentionBrush
  dev/CommonStyles/Common_themeresources_any.xaml
Labels: area-Styling, team-Controls

#4623 ListViewItem style tweaks for 21H1
  dev/CommonStyles/ListViewItem_themeresources_21h1.xaml
Labels: area-Lists, area-UIDesign, team-Controls

#4569 Update ToggleSwitch padding
  dev/CommonStyles/TestUI/CommonStylesPage.xaml.cs
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
Labels: area-Styling, area-ToggleSwitch, team-Controls

#4624 Fix tooltip jumping on NavigationView when mouse is over the boundary of NavigationView
  dev/NavigationView/NavigationViewItem.cpp
Labels: area-NavigationView, area-ToolTip, auto merge, team-Controls

#4620 Add default fallback styles for old versions
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/GridViewItem_themeresources_v1.xaml
Labels: area-DevInternal, team-Controls

#4590 [Website] Add a11y labels for feature table
  about.html
Labels: accessibility, documentation

#4415 Allow AniamtedIcon.State to be set on any ancestor.
  dev/AnimatedIcon/APITests/AnimatedIconTests.cs
  dev/AnimatedIcon/AnimatedIcon.cpp
  dev/AnimatedIcon/AnimatedIcon.h
  dev/AnimatedIcon/TestUI/AnimatedIconPage.xaml
Labels: area-AnimatedIcon, team-Controls

#4532 Add AlwaysExpanded property to CommandBarFlyout
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/CommandBarFlyout.h
  dev/CommandBarFlyout/CommandBarFlyout.idl
  dev/CommandBarFlyout/CommandBarFlyout.xaml
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml.cs
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/CommonStyles/TestUI/CommandBarPage.xaml
Labels: area-Commanding, team-Controls

#4563 Change IconSource.CreateIconElement to a "dynamic" factory.
  dev/AnimatedIcon/AnimatedIcon.cpp
  dev/AnimatedIcon/TestUI/AnimatedIconHost.cs
  dev/AnimatedIcon/TestUI/AnimatedIconPage.xaml
  dev/AnimatedIcon/TestUI/AnimatedIconPage.xaml.cs
  dev/CommonStyles/CheckBox_themeresources.xaml
  dev/DropDownButton/DropDownButton.xaml
  dev/Generated/AnimatedIconSource.properties.cpp
  dev/Generated/AnimatedIconSource.properties.h
  dev/Generated/BitmapIconSource.properties.cpp
  dev/Generated/BitmapIconSource.properties.h
  dev/Generated/FontIconSource.properties.cpp
  dev/Generated/FontIconSource.properties.h
  dev/Generated/IconSource.properties.cpp
  dev/Generated/IconSource.properties.h
  dev/Generated/ImageIconSource.properties.cpp
  dev/Generated/ImageIconSource.properties.h
  dev/Generated/PathIconSource.properties.cpp
  dev/Generated/PathIconSource.properties.h
  dev/Generated/SymbolIconSource.properties.cpp
  dev/Generated/SymbolIconSource.properties.h
  dev/IconSource/APITests/IconSourceApiTests.cs
  dev/IconSource/AnimatedIconSource.cpp
  dev/IconSource/AnimatedIconSource.h
  dev/IconSource/BitmapIconSource.cpp
  dev/IconSource/BitmapIconSource.h
  dev/IconSource/FontIconSource.cpp
  dev/IconSource/FontIconSource.h
  dev/IconSource/IconSource.cpp
  dev/IconSource/IconSource.h
  dev/IconSource/IconSource.idl
  dev/IconSource/ImageIconSource.cpp
  dev/IconSource/ImageIconSource.h
  dev/IconSource/PathIconSource.cpp
  dev/IconSource/PathIconSource.h
  dev/IconSource/SymbolIconSource.cpp
  dev/IconSource/SymbolIconSource.h
  dev/InfoBar/InfoBar.cpp
  dev/NavigationView/NavigationBackButton.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/SwipeControl/SwipeItem.cpp
  dev/TabView/TabViewItem.cpp
  dev/TeachingTip/TeachingTip.cpp
  dev/dll/CommandingHelpers.cpp
  dev/dll/SharedHelpers.cpp
  dev/inc/SharedHelpers.h
Labels: area-AnimatedIcon, team-Controls

#4637 allow right aligned action button in infobar when in layout is horizontal
  dev/InfoBar/InfoBarPanel.cpp
  dev/InfoBar/TestUI/InfoBarPage.xaml
  dev/InfoBar/TestUI/InfoBarPage.xaml.cs
Labels: area-InfoBar, team-Controls

#4583 Color Picker slider updates
  dev/ColorPicker/ColorPicker.xaml
  dev/ColorPicker/ColorPicker_themeresources.xaml
Labels: area-ColorPicker, area-UIDesign, team-Controls

#4573 Navigation View Visual Bugs
  dev/Generated/NavigationViewTemplateSettings.properties.cpp
  dev/Generated/NavigationViewTemplateSettings.properties.h
  dev/NavigationView/NavigationBackButton.xaml
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.idl
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/NavigationView/TestUI/Common/NavigationViewPage.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-5.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-6.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
  test/MUXControlsTestApp/verification/VerifyVerifyHeaderContentMarginOnMinimalNav-4.xml
  test/MUXControlsTestApp/verification/VerifyVerifyHeaderContentMarginOnMinimalNav-5.xml
  test/MUXControlsTestApp/verification/VerifyVerifyHeaderContentMarginOnMinimalNav-6.xml
  test/MUXControlsTestApp/verification/VerifyVerifyHeaderContentMarginOnMinimalNav-7.xml
  test/MUXControlsTestApp/verification/VerifyVerifyHeaderContentMarginOnMinimalNav-8.xml
Labels: area-NavigationView, area-UIDesign, team-Controls

#4468 [Breadcrumb] Fix focus visual margin
  dev/Breadcrumb/BreadcrumbBar.xaml
  dev/Breadcrumb/BreadcrumbBar_themeresources.xaml
Labels: area-Breadcrumb, team-Controls

#4656 ToggleButton: Add themeresource for BackgroundSizing
  dev/CommonStyles/ToggleButton_themeresources.xaml
Labels: area-UIDesign, team-Controls

#4625 SplitButton Visual updates and flyout fix
  dev/SplitButton/SplitButton.cpp
  dev/SplitButton/SplitButton.xaml
  dev/SplitButton/SplitButton_themeresources.xaml
Labels: area-SplitButton, team-Controls

#4641 CommandBarFlyout style updates
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
Labels: area-Commanding, area-UIDesign, team-Controls

#4587 Fix issue where icon on RadioMenuFlyout and ToggleMenuFlyout was not being displayed
  dev/CommonStyles/MenuFlyout_themeresources.xaml
  dev/CommonStyles/TestUI/MenuFlyoutPage.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_themeresources.xaml
  dev/RadioMenuFlyoutItem/TestUI/RadioMenuFlyoutItemPage.xaml
  dev/RadioMenuFlyoutItem/TestUI/RadioMenuFlyoutItemPage.xaml.cs
Labels: area-Flyouts, team-Controls

#4394 Expander Fixes
  dev/Expander/Expander.cpp
  dev/Expander/Expander.xaml
  dev/Expander/Expander_themeresources.xaml
  dev/Expander/TestUI/ExpanderPage.xaml
Labels: area-Expander, team-Controls

#4542 MenuBar Visual Updates
  dev/MenuBar/MenuBarItem.cpp
  dev/MenuBar/MenuBarItem.xaml
  dev/MenuBar/MenuBar_InteractionTests/MenuBarTests.cs
  dev/MenuBar/MenuBar_themeresources.xaml
Labels: area-Menus, area-UIDesign, team-Controls

#4628 Update color resource names
  dev/ColorPicker/ColorPicker_themeresources.xaml
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  dev/CommonStyles/AppBarToggleButton_themeresources.xaml
  dev/CommonStyles/Button_themeresources.xaml
  dev/CommonStyles/CalendarView_themeresources.xaml
  dev/CommonStyles/CheckBox_themeresources.xaml
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/CommonStyles/DatePicker_themeresources.xaml
  dev/CommonStyles/FlipView_themeresources.xaml
  dev/CommonStyles/GridViewItem_themeresources.xaml
  dev/CommonStyles/GridViewItem_themeresources_21h1.xaml
  dev/CommonStyles/ListViewItem_themeresources.xaml
  dev/CommonStyles/ListViewItem_themeresources_21h1.xaml
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
  dev/CommonStyles/RadioButton_themeresources.xaml
  dev/CommonStyles/ScrollBar_themeresources.xaml
  dev/CommonStyles/Slider_themeresources.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
  dev/CommonStyles/TimePicker_themeresources.xaml
  dev/CommonStyles/ToggleButton_themeresources.xaml
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_rs1_themeresources.xaml
  dev/Materials/Reveal/RevealBrush_rs2_themeresources.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  dev/PagerControl/PagerControl_themeresources.xaml
  dev/PipsPager/PipsPager_themeresources.xaml
  dev/ProgressBar/ProgressBar_themeresources.xaml
  dev/ProgressRing/ProgressRing_themeresources.xaml
  dev/RatingControl/RatingControl_themeresources.xaml
  dev/SplitButton/SplitButton_themeresources.xaml
  dev/SwipeControl/SwipeControl_themeresources.xaml
  dev/TabView/TabView_themeresources.xaml
Labels: area-Styling

#4680 Anawish/website updates for reunion0.5 ga
  WinUICommunityCall.ics
  about.html
  css/landing-page.css
  index.html
Labels: needs-triage

#4681 Updating repo docs for WinUI 3 release
  README.md
  docs/images/winui-roadmap.jpg
  docs/roadmap.md
Labels: needs-triage

#4460 [DatePicker | TimePicker] Update visual styles
  dev/CommonStyles/Common_themeresources.xaml
  dev/CommonStyles/DatePicker_themeresources.xaml
  dev/CommonStyles/DateTimePickerFlyout_themeresources.xaml
  dev/CommonStyles/InteractionTests/CommonStylesTests.cs
  dev/CommonStyles/TimePicker_themeresources.xaml
Labels: area-DateTimePickers, team-Controls

#4684 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#4657 CommandBar changes for DropShadows
  dev/CommonStyles/CommandBar_themeresources.xaml
Labels: area-Commanding, area-Shadows, team-Controls

#4683 Adding a few features to InfoBar test page
  dev/InfoBar/TestUI/InfoBarPage.xaml
  dev/InfoBar/TestUI/InfoBarPage.xaml.cs
Labels: area-InfoBar

#4634 [Testing] Add test to verify no keys are removed or missing
  dev/ComboBox/ComboBox_themeresources.xaml
  dev/CommonStyles/APITests/BaselineResources2dot5stable.cs
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/CommonStyles/APITests/CommonStyles_APITests.projitems
  dev/CommonStyles/AppBarToggleButton_themeresources.xaml
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/CommonStyles/Deprecated_themeresources.xaml
  dev/CommonStyles/Deprecated_themeresources_any.xaml
  dev/CommonStyles/TextBox_themeresources.xaml
  dev/ProgressBar/ProgressBar.xaml
  dev/ProgressBar/ProgressBar_themeresources.xaml
  dev/ProgressBar/ProgressBar_themeresources_v1.xaml
  dev/ProgressBar/TestUI/ProgressBarPage.xaml
  dev/ProgressBar/TestUI/ProgressBarPage.xaml.cs
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator.sln
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/App.xaml
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/App.xaml.cs
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Assets/LockScreenLogo.scale-200.png
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Assets/SplashScreen.scale-200.png
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Assets/Square150x150Logo.scale-200.png
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Assets/Square44x44Logo.scale-200.png
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Assets/StoreLogo.png
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Assets/Wide310x150Logo.scale-200.png
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator.csproj
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/MainPage.xaml
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/MainPage.xaml.cs
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Package.appxmanifest
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Properties/AssemblyInfo.cs
  tools/MUXBaselineResourcesGenerator/MUXBaselineResourcesGenerator/Properties/Default.rd.xml
Labels: area-Styling, auto merge, team-Controls

#4629 Fix teaching tip top highlight not respecting corner radius.
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
Labels: area-TeachingTip, team-Controls

#4695 Update some controls to have rounded focus rects.
  dev/ColorPicker/ColorPicker.xaml
  dev/CommonStyles/CalendarView_themeresources.xaml
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
  dev/CommonStyles/RadioButton_themeresources.xaml
  dev/CommonStyles/Slider_themeresources.xaml
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
  dev/PagerControl/PagerControl_themeresources.xaml
  dev/PipsPager/PipsPager_themeresources.xaml
  test/MUXControlsTestApp/verification/CalendarView-4.xml
  test/MUXControlsTestApp/verification/CalendarView-6.xml
  test/MUXControlsTestApp/verification/CalendarView-7.xml
Labels: area-Styling, team-Controls

#4700 Fix MTC backplate issue with 2.6 styles
  dev/CommonStyles/MediaTransportControls_themeresources.xaml
Labels: area-MediaPlayerElement, area-UIDesign, team-Controls

#3947 DatePicker and TimePicker flyout visual updates
  FeatureAreas.props
  MUXControls.sln
  MUXControlsInnerLoop.sln
  dev/CommonStyles/Common_themeresources.xaml
  dev/CommonStyles/DatePicker_themeresources.xaml
  dev/CommonStyles/DateTimePickerFlyout_themeresources.xaml
  dev/CommonStyles/InteractionTests/CommonStylesTests.cs
  dev/CommonStyles/TimePicker_themeresources.xaml
  dev/Generated/MonochromaticOverlayPresenter.properties.cpp
  dev/Generated/MonochromaticOverlayPresenter.properties.h
  dev/Generated/XRayOverlayControl.properties.cpp
  dev/Generated/XRayOverlayControl.properties.h
  dev/MonochromaticOverlayPresenter/MonochromaticOverlayPresenter.cpp
  dev/MonochromaticOverlayPresenter/MonochromaticOverlayPresenter.h
  dev/MonochromaticOverlayPresenter/MonochromaticOverlayPresenter.idl
  dev/MonochromaticOverlayPresenter/MonochromaticOverlayPresenter.vcxitems
  dev/MonochromaticOverlayPresenter/TestUI/MonochromaticOverlayPresenterPage.xaml
  dev/MonochromaticOverlayPresenter/TestUI/MonochromaticOverlayPresenterPage.xaml.cs
  dev/MonochromaticOverlayPresenter/TestUI/MonochromaticOverlayPresenter_TestUI.projitems
  dev/MonochromaticOverlayPresenter/TestUI/MonochromaticOverlayPresenter_TestUI.shproj
  dev/dll/Microsoft.UI.Xaml.vcxproj
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.targets
Labels: area-DateTimePickers, team-Controls

#4507 InkToolbar Style updates
  dev/CommonStyles/InkToolbar_themeresources.xaml
  dev/CommonStyles/InteractionTests/CommonStylesTests.cs
  dev/CommonStyles/TestUI/InkToolbarPage.xaml
Labels: area-Styling, needs-triage, team-Controls, team-Ink

#3516 Add check for UIObject circles resulting in infinite loops
  test/testinfra/MUXTestInfra/Common/FindElement.cs
Labels: area-DevInternal, team-Controls
