Repository microsoft/microsoft-ui-xaml, pull requests merged in 2021-04, with the labels that each got.

#4706 [Resource Keys] Remove extra keys
  dev/CommonStyles/DatePicker_themeresources.xaml
  dev/CommonStyles/TimePicker_themeresources.xaml
Labels: area-DevInternal, team-Controls

#4607 PipsPager: apply different pip sizes for different orientations
  dev/PipsPager/InteractionTests/PipsPagerElements.cs
  dev/PipsPager/InteractionTests/PipsPagerTests.cs
  dev/PipsPager/PipsPager.cpp
  dev/PipsPager/PipsPager.h
  dev/PipsPager/PipsPager.xaml
  dev/PipsPager/PipsPagerAutomationPeer.cpp
  dev/PipsPager/PipsPagerAutomationPeer.h
  dev/PipsPager/PipsPagerSelectedIndexChangedEventArgs.h
  dev/PipsPager/PipsPager_themeresources.xaml
  dev/PipsPager/TestUI/PipsPagerPage.xaml
  dev/PipsPager/TestUI/PipsPagerPage.xaml.cs
Labels: area-PipsPager, team-Controls

#4593 Adding styles for the system XAML CommandBarFlyoutCommandBar
  dev/CommandBarFlyout/CommandBarFlyout.vcxitems
  dev/CommandBarFlyout/CommandBarFlyout.xaml
  dev/CommandBarFlyout/CommandBarFlyoutOS_themeresources.xaml
  dev/CommandBarFlyout/CommandBarFlyoutOS_themeresources_v1.xaml
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  dev/CommandBarFlyout/CommandBarFlyout_themeresources_v1.xaml
  dev/CommandBarFlyout/CommandBarFlyout_v1.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml.cs
  test/MUXControlsTestApp/Themes/DisableAnimationsStylesOutsideStore_rs2.xaml
Labels: area-Commanding, team-Controls

#4707 Add Opaque Background to NavigationView ContentGrid
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-5.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-6.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
Labels: area-NavigationView, team-Controls

#4635 Update high contrast colors
  dev/CommonStyles/Button_themeresources.xaml
  dev/CommonStyles/Button_themeresources_v1.xaml
  dev/CommonStyles/CheckBox_themeresources.xaml
  dev/CommonStyles/CheckBox_themeresources_v1.xaml
  dev/CommonStyles/Common_themeresources.xaml
  dev/CommonStyles/RadioButton_themeresources.xaml
  dev/CommonStyles/RadioButton_themeresources_v1.xaml
  dev/CommonStyles/ToggleButton_themeresources.xaml
  dev/CommonStyles/ToggleButton_themeresources_v1.xaml
  dev/CommonStyles/ToggleSwitch_themeresources.xaml
  dev/CommonStyles/ToggleSwitch_themeresources_v1.xaml
  dev/SplitButton/SplitButton.xaml
  dev/SplitButton/SplitButton_themeresources.xaml
  dev/SplitButton/SplitButton_themeresources_v1.xaml
Labels: accessibility, area-Styling, team-Controls

#4720 MenuFlyoutItem size fix for mouse and touch.
  dev/CommonStyles/MenuFlyout_themeresources.xaml
Labels: area-Menus, team-Controls

#4728 HighContrastAdjustment default state
  test/MUXControlsTestApp/MainPage.xaml.cs
Labels: area-Tooling

#4659 Add New NavView VisualStateGroup
  dev/CommonStyles/CommonStyles.vcxitems
  dev/CommonStyles/SplitView_themeresources.xaml
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_InteractionTests/PaneBehaviorTests.cs
  dev/NavigationView/TestUI/Common/NavigationViewPage.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-5.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-6.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
Labels: area-NavigationView, team-Controls

#4726 Update accent fill colors
  dev/CommonStyles/Common_themeresources_any.xaml
  test/MUXControlsTestApp/verification/CalendarView-4.xml
  test/MUXControlsTestApp/verification/CalendarView-6.xml
  test/MUXControlsTestApp/verification/CalendarView-7.xml
Labels: area-Styling

#4747 Menuflyout Item mouse/touch invocation sizing regression test
  dev/CommonStyles/InteractionTests/CommonStylesTests.cs
  dev/CommonStyles/TestUI/MenuFlyoutPage.xaml
  dev/CommonStyles/TestUI/MenuFlyoutPage.xaml.cs
Labels: area-Menus, team-Controls, test issue

#4754 TabView: update brushes
  dev/TabView/TabView_themeresources.xaml
Labels: area-TabView, area-UIDesign, team-Controls

#3955 TabView: Fix all tabs squeezed into viewport when last tab is closed
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TestUI/TabViewTabClosingBehaviorPage.xaml
  dev/TabView/TestUI/TabViewTabClosingBehaviorPage.xaml.cs
Labels: area-TabView, team-Controls

#4749 Binding CornerRadius to CommandBar.CornerRadius
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/CommonStyles/CommandBar_themeresources.xaml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-7.xml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-8.xml
Labels: area-Commanding, area-UIDesign, team-Controls

#4193 NavigationView: Fix issue where disabling settings would still show gap
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  dev/NavigationView/NavigationView.xaml
  dev/NavigationView/NavigationView_InteractionTests/PaneBehaviorTests.cs
  dev/NavigationView/TestUI/Footer/PaneLayoutTestPage.xaml
  dev/NavigationView/TestUI/Footer/PaneLayoutTestPage.xaml.cs
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-5.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-6.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
Labels: area-NavigationView, team-Controls

#4753 update hyperlinkbutton foreground on HC mode
  dev/InfoBar/InfoBar_themeresources.xaml
Labels: area-Accessibility, area-HyperlinkButton, team-Controls

#4689 Update localization process to use ADO Task instead of TDClient
  MUXControls.sln
  build/Localization/CopyBackLocalizedFiles.ps1
  build/Localization/LocalizationAutomation.proj
  build/Localization/NuGet.Config
  build/Localization/PrepLocFilesForUpload.ps1
  build/Localization/RunLocWorkflow.cmd
  build/Localization/RunLocWorkflow.ps1
  build/Localization/Settings/LocConfig.xml
  build/Localization/Settings/TdBuildTeamIds_master.xml
  build/Localization/Settings/packages.config
  build/Localization/readme.md
  build/MUX-LocalizationHandoff.yml
  tools/VSTSRunLocWorkflow.cmd
Labels: area-DevInternal, team-Controls

#4727 [BreadcrumbBar] Add theme resource keys for customizing Chevron padding and font weight
  dev/Breadcrumb/BreadcrumbBar.cpp
  dev/Breadcrumb/BreadcrumbBar.h
  dev/Breadcrumb/BreadcrumbBar.xaml
  dev/Breadcrumb/BreadcrumbBarItem.cpp
  dev/Breadcrumb/BreadcrumbBarItem.h
  dev/Breadcrumb/BreadcrumbBarItemAutomationPeer.cpp
  dev/Breadcrumb/BreadcrumbBarItemAutomationPeer.h
  dev/Breadcrumb/BreadcrumbBar_themeresources.xaml
  dev/Breadcrumb/InteractionTests/BreadcrumbBarTests.cs
  dev/Breadcrumb/Strings/en-us/Resources.resw
  dev/ResourceHelper/ResourceAccessor.h
Labels: area-Breadcrumb, team-Controls

#4715 Move margin to the right place.
  dev/CommonStyles/CommandBar_themeresources.xaml
Labels: area-Commanding, team-Controls

#4778 Secondary foreground color
  dev/CommonStyles/Common_themeresources_any.xaml
  test/MUXControlsTestApp/verification/ComboBox-4.xml
  test/MUXControlsTestApp/verification/ComboBox-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTop-8.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewTopPaneContent-8.xml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-8.xml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius.xml
Labels: area-Styling

#4801 Fix app bar buttons showing flyout chevrons in command bars where they aren't supposed to.
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  dev/CommandBarFlyout/CommandBarFlyout_themeresources_v1.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
  dev/CommonStyles/AppBarButton_themeresources.xaml
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/CommonStyles/TestUI/CommandBarPage.xaml
Labels: area-Commanding, area-UIDesign, team-Controls

#4820 Fixing WACK failure on store submission
  build/NuSpecs/MUXControls-Nuget-Common.targets
Labels: area-DevInternal, team-Controls

#4819 TeachingTip: update solid background bursh
  dev/TeachingTip/TeachingTip_rs1_themeresources.xaml
Labels: area-TeachingTip, area-UIDesign, team-Controls

#4743 CommandBarFlyout changes for drop shadows
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/CommandBarFlyout.h
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.h
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
Labels: area-Commanding, area-Shadows, area-UIDesign, team-Controls

#4818 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#4809 [ContentDialog] Fix title margin & fontweight and corners
  dev/CommonStyles/ContentDialog_themeresources.xaml
Labels: area-Dialogs, area-UIDesign, team-Controls

#4817 Add SplitButton style for CommandBar
  dev/CommonStyles/CommandBar_themeresources.xaml
  dev/CommonStyles/TestUI/CommandBarPage.xaml
  dev/SplitButton/SplitButton_themeresources.xaml
Labels: area-Commanding, team-Controls

#4678 Refactor WinUI Helix functionality into reusable WinUI.Helix nuget package
  build/AzurePipelinesTemplates/MUX-CreateHelixProjFile-Steps.yml
  build/AzurePipelinesTemplates/MUX-ProcessTestResults-Job.yml
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/Helix/AzurePipelinesHelperScripts.ps1
  build/Helix/ConvertWttLogToXUnit.ps1
  build/Helix/CopyPGOFiles.ps1
  build/Helix/EnsureMachineState.ps1
  build/Helix/GenerateTestProjFile.ps1
  build/Helix/HelixTestHelpers.cs
  build/Helix/OutputFailedTestQuery.ps1
  build/Helix/OutputSubResultsJsonFiles.ps1
  build/Helix/OutputTestResults.ps1
  build/Helix/PrepareHelixPayload.ps1
  build/Helix/ProcessHelixFiles.ps1
  build/Helix/RunTestsInHelix.proj
  build/Helix/UpdateUnreliableTests.ps1
  build/Helix/packages.config
  build/Helix/runtests.cmd
  build/Helix/scripts/CopyVisualTreeVerificationFiles.ps1
  build/Helix/scripts/InstallTestAppDependencies.ps1
  build/Helix/scripts/TestPass-EnsureMachineState.ps1
  build/Helix/scripts/TestPass-PostRun.ps1
  build/Helix/scripts/TestPass-PreRun.ps1
  test/IXMPTestApp/WaitForDebugger.cs
  test/MUXControls.Test/TestAssembly.cs
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/ReleaseTestEnvironment.cs
  test/MUXControlsTestApp/WaitForDebugger.cs
Labels: area-TestInfrastructure, team-Controls

#4857 MenuFlyout: blurry stroke
  dev/CommonStyles/MenuFlyout_themeresources.xaml
Labels: area-Flyouts, area-Menus, team-Controls

#4771 TeachingTip: close button update
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TeachingTip_rs1_themeresources.xaml
Labels: area-TeachingTip, area-UIDesign, team-Controls

#4862 Font ramp update
  dev/CommonStyles/TextBlock_themeresources.xaml
  dev/CommonStyles/TextBlock_themeresources_v2.5.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
Labels: area-UIDesign, needs-triage

#4846 TeachingTip: update beak placement and remove top highlight
  dev/TeachingTip/APITests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TeachingTip_rs1_themeresources.xaml
Labels: area-TeachingTip, area-UIDesign, team-Controls

#4867 Base acrylic update
  dev/Materials/Acrylic/AcrylicBrush_19h1_themeresources.xaml
  dev/Materials/Acrylic/AcrylicBrush_rs2_themeresources.xaml
  dev/dll/XamlControlsResources.cpp
Labels: area-Styling

#4578 Update InfoBar narrator behavior
  dev/InfoBar/InfoBar.cpp
  dev/InfoBar/InfoBar.h
  dev/InfoBar/InfoBar.xaml
  dev/InfoBar/InfoBar_v1.xaml
  dev/InfoBar/InteractionTests/InfoBarTests.cs
  dev/InfoBar/Strings/en-us/Resources.resw
  dev/ResourceHelper/ResourceAccessor.h
Labels: accessibility, area-InfoBar, team-Controls

#4880 Enable WACK testing
  build/AzurePipelinesTemplates/MUX-WACKTests-Job.yml
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/Assets/LockScreenLogo.scale-200.png
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/Assets/SplashScreen.scale-200.png
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/Assets/Square150x150Logo.scale-200.png
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/Assets/Square44x44Logo.scale-200.png
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/Assets/StoreLogo.png
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/Assets/Wide310x150Logo.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestApp/Assets/LockScreenLogo.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestApp/Assets/SplashScreen.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestApp/Assets/Square150x150Logo.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestApp/Assets/Square44x44Logo.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestApp/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  test/MUXControlsReleaseTest/NugetPackageTestApp/Assets/StoreLogo.png
  test/MUXControlsReleaseTest/NugetPackageTestApp/Assets/Wide310x150Logo.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/Assets/LockScreenLogo.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/Assets/SplashScreen.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/Assets/Square150x150Logo.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/Assets/Square44x44Logo.scale-200.png
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/Assets/Square44x44Logo.targetsize-24_altform-unplated.png
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/Assets/StoreLogo.png
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/Assets/Wide310x150Logo.scale-200.png
Labels: needs-triage

#4876 Website: Updating the date of the next community call
  WinUICommunityCall.ics
  index.html
Labels: documentation

#4882 ProgressRing: Add Height setter to template
  dev/ProgressRing/ProgressRing.xaml
  dev/ProgressRing/TestUI/ProgressRingPage.xaml
Labels: area-Progress, team-Controls

#4888 Updating roadmap
  build/AzurePipelinesTemplates/MUX-ProcessTestResults-Job.yml
  docs/images/winui-roadmap.jpg
  docs/roadmap.md
Labels: documentation

#4902 Update bug report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: needs-triage

#4901 Updates to Radio Button Group spacing of header and list items.
  dev/RadioButtons/RadioButtons_themeresources.xaml
Labels: area-RadioButtons

#4903 Upgrading version of internal Windows SDK to
  SdkVersion.props
  build/AzurePipelinesTemplates/MUX-InstallWindowsSDK-Steps.yml
  tools/InternalWindowsSDKNuget/MergeNupkgParts.cmd
  tools/InternalWindowsSDKNuget/NuSpecs/InternalWindowsSDK-part1.nuspec
  tools/InternalWindowsSDKNuget/NuSpecs/InternalWindowsSDK-part2.nuspec
  tools/InternalWindowsSDKNuget/SetUpInternalWindowsSDK.cmd
Labels: area-DevInternal, needs-triage

#4911 DatePicker/TimePicker: use old style when < 19H1
  dev/CommonStyles/DatePicker_themeresources.xaml
  dev/CommonStyles/TimePicker_themeresources.xaml
Labels: area-DateTimePickers, needs-triage, team-Controls

#4919 Fixes to enable CI and Release Pipelines to work reliably
  build/AzurePipelinesTemplates/MUX-NugetReleaseTest-Job.yml
  build/MUX-CI.yml
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/NugetTestsCX.cs
  test/MUXControlsReleaseTest/XamlIslandsTestApp/WpfApp/WpfApp.Package.wapproj
Labels: needs-triage

#4864 Roadmap broken link
  docs/roadmap.md
Labels: documentation

#4910 Updating cookie banner on WinUI website
  index.js
Labels: documentation, website

#4923 MenuFlyout items: Fixed icon color on press
  dev/CommonStyles/MenuFlyout_themeresources.xaml
Labels: needs-triage

#4889 [Scrollbar] Fix carat spacing to edges
  dev/CommonStyles/ScrollBar_themeresources.xaml
  test/MUXControlsTestApp/verification/NavigationViewAuto-4.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-5.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-6.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-7.xml
  test/MUXControlsTestApp/verification/NavigationViewAuto-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftCompact-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftMinimal-8.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-4.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-5.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-6.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-7.xml
  test/MUXControlsTestApp/verification/NavigationViewLeftPaneContent-8.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-4.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-5.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-6.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-7.xml
  test/MUXControlsTestApp/verification/NavigationViewScrolling-8.xml
Labels: area-ScrollBar, area-UIDesign, team-Controls

#4925 Update references from 'master' branch to 'main' branch
  .github/ISSUE_TEMPLATE/feature_proposal.md
  CONTRIBUTING_feedback_and_requests.md
  README.md
  build/Helix/readme.md
  build/Localization/readme.md
  build/MUX-CreateUnreliableTestReport.yml
  dev/Expander/ExpanderAutomationPeer.cpp
  docs/code_style_and_conventions.md
  docs/contribution_workflow.md
  docs/developer_guide.md
  docs/feature_proposal_process.md
  tools/BuildMachineUtils.psm1
  tools/CreateUnreliableTestReport.ps1
  tools/MUXPGODatabase/config.ps1
  tools/MUXPGODatabase/readme.md
Labels: team-Controls

#4918 [AppBarSeparator] Update margins for AppBarSeparator
  dev/CommonStyles/AppBarSeparator_themeresources.xaml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-7.xml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-8.xml
Labels: area-Commanding, area-Styling, team-Controls

#4921 Make Padding settable for AppBarSeparator
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/CommonStyles/AppBarSeparator_themeresources.xaml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-7.xml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-8.xml
Labels: needs-triage

#4928 Fix InkToolbar pen flyout crash on RS4
  dev/CommonStyles/InkToolbar_themeresources.xaml
Labels: area-UIDesign, team-Ink

#4924 PipsPager: update navigation buttons tooltip placement
  dev/PipsPager/PipsPager.xaml
Labels: area-PipsPager, needs-triage, team-Controls

#4941 Update master files for VerifyVisualTreeForCommandBarCornerRadius
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-7.xml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForCommandBarCornerRadius-8.xml
Labels: needs-triage

#4865 Add RadioMenuFlyoutSubItemStyle
  dev/Generated/RadioMenuFlyoutItem.properties.cpp
  dev/Generated/RadioMenuFlyoutItem.properties.h
  dev/RadioMenuFlyoutItem/InteractionTests/RadioMenuFlyoutItemTests.cs
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem.cpp
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem.h
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem.idl
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_themeresources.xaml
  dev/RadioMenuFlyoutItem/TestUI/RadioMenuFlyoutItemPage.xaml
  dev/RadioMenuFlyoutItem/TestUI/RadioMenuFlyoutItemPage.xaml.cs
Labels: area-Flyouts, area-UIDesign, team-Controls
