Repository microsoft/microsoft-ui-xaml, pull requests merged in 2022-09, with the labels that each got.

#7714 Cherry-Pick: WinUI Vpack: Include re-merged winmd
  build/CreateCBSVPack.ps1
Labels: needs-triage

#7605 New api spec : Window.AppWindow api
  specs/appwindow-spec.md
Labels: team-Reach

#7752 Bug template updates for 1.1.5, 1.2-preview1, 1.2-exp2
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation

#7753 WinUI website accuracy & accessibility updates
  about.html
  index.html
  package.json
Labels: website
