Repository microsoft/microsoft-ui-xaml, pull requests merged in 2022-01, with the labels that each got.

#6486 Update test code from .net core 2.1 to 3.1
  build/AzurePipelinesTemplates/MUX-BuildProject-Steps.yml
  build/CopyFilesToStagingDir.ps1
  build/Helix/PrepareHelixPayload.ps1
  build/Helix/packages.config
  test/MUXControls.Test/MSTest/MUXControls.Test.csproj
  test/MUXControls.Test/TAEF/MUXControls.Test.TAEF.csproj
  test/MUXControls.Test/TAEF/MUXControlsTestApp.dependencies.txt
  test/MUXControls.Test/TAEF/NonRazzleIncludes.props
  test/MUXControls.Test/TAEF/RazzleIncludes.props
  test/MUXControls.Test/TAEF/product.pbxproj
  test/MUXControls.Test/TestAssembly.cs
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/MSTest/MUXControls.ReleaseTest.csproj
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/ReleaseTestEnvironment.cs
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/TAEF/MUXControls.ReleaseTest.TAEF.csproj
  test/MUXControlsReleaseTest/tools/GenerateAppxDependenciesXML_ReleaseTest.cmd
  test/MUXControlsReleaseTest/tools/GenerateAppxDependenciesXML_ReleaseTest.ps1
  test/MUXControlsReleaseTest/tools/PkgGen_ReleaseTest.cmd
  test/MUXControlsReleaseTest/tools/PostBuildWrapper_ReleaseTest.cmd
  test/MUXControlsReleaseTest/tools/PostBuild_ReleaseTest.cmd
  test/MUXControlsReleaseTest/tools/packages.pkggen.config
  test/MUXExperimentalTest/MUXExperimental.Test/MSTest/MUXExperimental.Test.csproj
  test/MUXExperimentalTest/MUXExperimental.Test/MUXExperimentalTestEnvironment.cs
  test/MUXExperimentalTest/MUXExperimental.Test/TAEF/MUXExperimental.Test.TAEF.csproj
  test/testinfra/MUXTestInfra/MSTest/MUXTestInfra.MSTest.csproj
  test/testinfra/MUXTestInfra/TAEF/MUXTestInfra.TAEF.csproj
  tools/PkgGen.cmd
Labels: needs-triage

#6276 [InkToolBar] Disable text scaling for inktoolbar buttons
  dev/CommonStyles/InkToolbar_themeresources.xaml
Labels: team-Controls, team-Ink, area-InkToolBar

#6552 Revert #5872
  dev/CommonStyles/ContentDialog_themeresources.xaml
  dev/CommonStyles/ContentDialog_themeresources_v1.xaml
  test/MUXControlsTestApp/verification/CalendarView-4.xml
  test/MUXControlsTestApp/verification/CalendarView-6.xml
  test/MUXControlsTestApp/verification/CalendarView-7.xml
  test/MUXControlsTestApp/verification/ContentDialog-4.xml
  test/MUXControlsTestApp/verification/ContentDialog-5.xml
  test/MUXControlsTestApp/verification/ContentDialog-6.xml
  test/MUXControlsTestApp/verification/ContentDialog-7.xml
  test/MUXControlsTestApp/verification/ContentDialog-8.xml
Labels: area-Dialogs, team-Controls

#6343 Revert `WidthExpansionDelta`
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
Labels: needs-triage

#6629 Experimental package: Fix native targets reference
  build/NuSpecs/Microsoft.Experimental.UI.Xaml.nuspec
Labels: needs-triage

#6598 TabView Miscellaneous Fixes
  dev/TabView/TabView.cpp
  dev/TabView/TabView.xaml
Labels: needs-triage

#6492 Misc cleanup: Delete unused scripts and build logic
  Build.cmd
  CustomInlineTasks.targets
  Directory.Build.props
  MUXControls.sln
  build/FrameworkPackage/UpdateAppxFilesInNupkg.ps1
  dev/Effects/Microsoft.UI.Private.Composition.Effects.vcxitems
  dev/Microsoft.UI.Xaml.Design/Microsoft.UI.Xaml.Design.csproj
  dev/Repeater/Repeater.vcxitems
  dev/dll/product.pbxproj
  mux.controls.props
  test/IXMPTestApp/IXMPTestApp.Shared.projitems
  test/IXMPTestApp/MSTest/IXMPTestApp.csproj
  test/IXMPTestApp/TAEF/IXMPTestApp.TAEF.csproj
  test/IXMPTestApp/TAEF/RazzleIncludes.props
  test/MUXControls.Test/MUXControls.Test.Shared.projitems
  test/MUXControls.Test/TAEF/MUXControls.Test.TAEF.csproj
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/AppThatUsesMUXIndirectly.csproj
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/MUXControls.ReleaseTest.Shared.projitems
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/TAEF/MUXControls.ReleaseTest.TAEF.csproj
  test/MUXControlsReleaseTest/NugetPackageTestApp/NugetPackageTestApp.csproj
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/NugetPackageTestAppCX.vcxproj
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.vcxproj
  test/MUXControlsReleaseTest/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess/UwpAppWithFullTrustProcess.csproj
  test/MUXControlsTestApp.ApiTests/product.pbxproj
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
  test/MUXControlsTestApp/TAEF/MUXControlsTestApp.TAEF.csproj
  test/MUXExperimentalTest/MUXExperimental.Test/TAEF/MUXExperimental.Test.TAEF.csproj
  test/TestAppCX/TestAppCX.vcxproj
  tools/AdalAuth.ps1
  tools/BuildMachineUtils.psm1
  tools/ExtractControls.ps1
  tools/GenerateAppxDependenciesXML.cmd
  tools/GenerateAppxDependenciesXML.ps1
  tools/GenerateSystemDllImageResources.ps1
  tools/GenerateSystemDllStringResources.ps1
  tools/InstallTestApp.Desktop.cmd
  tools/InstallTestApp.Phone.cmd
  tools/PerformFullOSBuilds.ps1
  tools/PostBuild.cmd
  tools/PostBuildWrapper.cmd
  tools/PostTestsWrapper.cmd
  tools/ProcessTextTemplate.ps1
  tools/PublishChunk.cmd
  tools/PublishPostBuild.cmd
  tools/PublishPostBuildWrapper.cmd
  tools/RebootBuildMachine.ps1
  tools/ReleaseHelper.ps1
  tools/UpdateBuildMachineGitInstalls.ps1
  tools/UpdateBuildMachineSDKs.ps1
  tools/UpdateBuildMachineVSInstalls.ps1
  tools/packages.pkggen.config
Labels: needs-triage

#6269 Added new AVP::AnimationOptimization property
  dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp
  dev/AnimatedVisualPlayer/AnimatedVisualPlayer.h
  dev/AnimatedVisualPlayer/AnimatedVisualPlayer.idl
  dev/AnimatedVisualPlayer/InteractionTests/AnimatedVisualPlayerTests.cs
  dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml
  dev/AnimatedVisualPlayer/TestUI/AnimatedVisualPlayerPage.xaml.cs
  dev/AnimatedVisualPlayer/TestUI/LottieLogo.cs
  dev/Generated/AnimatedVisualPlayer.properties.cpp
  dev/Generated/AnimatedVisualPlayer.properties.h
Labels: area-AnimatedVisualPlayer, needs-triage, team-CompInput

#6573 TabView Colours Update
  dev/CommonStyles/Common_themeresources_any.xaml
  dev/TabView/TabView.xaml
  dev/TabView/TabView_themeresources.xaml
  dev/TabView/TestUI/TabViewPage.xaml
Labels: area-Styling, area-TabView, team-Controls

#6641 Update WinUI to use HybridCRT
  HybridCRT.props
  dev/dll/Microsoft.UI.Xaml.Common.props
  dev/dll/Microsoft.UI.Xaml.Common.targets
  test/IXMPTestApp/TAEF/IXMPTestApp.TAEF.csproj
Labels: needs-triage

#6632 TabView fixes
  dev/TabView/TabView.cpp
  dev/TabView/TabView.h
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
Labels: needs-triage

#6650 Stop using Helix queues that are about to be disabled.
  build/AzurePipelinesTemplates/MUX-ProcessTestResults-Job.yml
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/MUX-CI.yml
  build/MUX-PR.yml
  dev/CommonStyles/APITests/CalendarViewTests.cs
  dev/Materials/Reveal/InteractionTests/Reveal_InteractionTests/RevealBrushTests.cs
  dev/PullToRefresh/RefreshContainer/InteractionTests/RefreshContainerTests.cs
Labels: needs-triage
