Repository microsoft/microsoft-ui-xaml, pull requests merged in 2022-04, with the labels that each got.

#6918 Fixing SplitButtonAutomationPeer's Invoke implementation
  dev/SplitButton/InteractionTests/SplitButtonTests.cs
  dev/SplitButton/SplitButton.cpp
  dev/SplitButton/SplitButton.h
  dev/SplitButton/SplitButtonAutomationPeer.cpp
Labels: needs-triage

#6897 [Accessibility] Fix teaching tip name property in buttons
  dev/TeachingTip/InteractionTests/TeachingTipTests.cs
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml
Labels: area-TeachingTip, team-Controls

#6889 Ensure `BringIntoView` request is not skipped for direct content of `ScrollView`
  dev/ScrollPresenter/APITests/ScrollPresenterBringIntoViewTests.cs
  dev/ScrollPresenter/ScrollPresenter.cpp
Labels: area-Scrolling, team-Controls

#6930 Update community call in WinUI website
  index.html
Labels: needs-triage

#6929 Fixing CommandBarFlyout lifetime crashing bug
  dev/CommandBarFlyout/CommandBarFlyout.cpp
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.cpp
  dev/CommandBarFlyout/CommandBarFlyoutCommandBar.h
  dev/CommandBarFlyout/InteractionTests/CommandBarFlyoutTests.cs
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml
  dev/CommandBarFlyout/TestUI/CommandBarFlyoutPage.xaml.cs
Labels: needs-triage, area-CommandBarFlyout

#6917 Move to PackageES SDL Pipeline template for security and compliance
  .config/tsaoptions.json
  build/AzurePipelinesTemplates/MUX-ComplianceChecks-Job.yml
  build/AzurePipelinesTemplates/MUX-PushCBSVpack-Job.yml
  build/CreateCBSVPack.ps1
  build/MUX-Release.yml
  test/MUXExperimentalTest/MUXExperimentalTestApp/MUXExperimentalTestApp.csproj
  test/TestAppCX/TestAppCX.vcxproj
  test/testinfra/AppTestAutomationHelpers/AppTestAutomationHelpers.vcxproj
Labels: needs-triage

#6933 Fixing AppBarButton visual state overlap
  dev/CommonStyles/APITests/CommonStylesTests.cs
  dev/CommonStyles/AppBarButton_themeresources.xaml
  test/MUXControlsTestApp/verification/AppBarButton-7.xml
  test/MUXControlsTestApp/verification/AppBarButton.xml
  test/MUXControlsTestApp/verification/CommandBarOverflowMenu-7.xml
  test/MUXControlsTestApp/verification/CommandBarOverflowMenu.xml
  test/MUXControlsTestApp/verification/VerifyVisualTreeForAppBarAndAppBarToggleButton-7.xml
Labels: area-Commanding, team-Controls

#6936 Reverting product change made for 'TabView gap between active tab and active content fix #6644'
  dev/TabView/TabViewItem.cpp
Labels: area-TabView, needs-triage

#6941 Fixing ProgressRing pattern reporting
  dev/ProgressRing/InteractionTests/ProgressRingTests.cs
  dev/ProgressRing/ProgressRingAutomationPeer.cpp
Labels: needs-triage

#6947 Fixing NavigationView UIA set logic
  dev/NavigationView/NavigationViewItemAutomationPeer.cpp
  dev/NavigationView/NavigationViewItemAutomationPeer.h
  dev/NavigationView/NavigationView_InteractionTests/CommonTests.cs
  dev/NavigationView/NavigationView_InteractionTests/FocusBehaviorTests.cs
  dev/NavigationView/TestUI/Common/NavigationViewPage.xaml
Labels: area-NavigationView, team-Controls

#6835 Update Sample to include MenuFlyout Invocation at Cursor Position
  dev/CommonStyles/TestUI/MenuFlyoutPage.xaml
  dev/CommonStyles/TestUI/MenuFlyoutPage.xaml.cs
Labels: area-Menus, team-Controls

#6953 MenuBar Keyboard Accessibility Fixes
  dev/MenuBar/MenuBarItem.cpp
  dev/MenuBar/MenuBarItem.h
  dev/MenuBar/MenuBar_InteractionTests/MenuBarTests.cs
Labels: needs-triage

#6954 TabView continuous expansions fix
  dev/TabView/TabView.cpp
  dev/TabView/TabView.h
  dev/TabView/TabView.vcxitems
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
  dev/TabView/TabViewTrace.h
  dev/TabView/TestUI/TabViewPage.xaml
  dev/Telemetry/TraceLogging.h
  dev/TestHooks/MUXControlsTestHooks.cpp
Labels: area-TabView, team-Controls

#6982 Update TeachingTip high contrast system
  dev/TeachingTip/TeachingTip_rs1_themeresources.xaml
Labels: area-TeachingTip, team-Controls

#6987 Fixing TabView null ref crash
  dev/TabView/TabView.cpp
Labels: area-TabView, team-Controls

#6998 Another set of localization updates
  dev/Breadcrumb/Strings/mt-MT/Resources.resw
  dev/ColorPicker/Strings/mt-MT/Resources.resw
  dev/CommandBarFlyout/Strings/mt-MT/Resources.resw
  dev/InfoBar/Strings/mt-MT/Resources.resw
  dev/NavigationView/Strings/mt-MT/Resources.resw
  dev/NumberBox/Strings/mt-MT/Resources.resw
  dev/PersonPicture/Strings/mt-MT/Resources.resw
  dev/ProgressBar/Strings/mt-MT/Resources.resw
  dev/TabView/Strings/mt-MT/Resources.resw
  dev/TeachingTip/Strings/mt-MT/Resources.resw
  dev/TreeView/Strings/mt-MT/Resources.resw
Labels: team-Controls

#7010 Update Windows SDK retrieval link
  build/Install-WindowsSdkISO.ps1
Labels: area-DevInternal, team-Controls

#6912 Minor edits and reformatting to repo docs
  .github/ISSUE_TEMPLATE/bug_report.yaml
  README.md
  docs/roadmap.md
Labels: documentation

#7027 2022 WinUI Website Accessibility Fixes
  about.html
  css/landing-page.css
  index.html
Labels: needs-triage
