Repository microsoft/microsoft-ui-xaml, pull requests merged in 2022-06, with the labels that each got.

#7177 Explicitly revoke event handlers on WebView2 Close()
  dev/WebView2/WebView2.cpp
  dev/WebView2/WebView2.h
Labels: area-WebView, team-Rendering

#7174 Fixing TabViewItem sub-pixel bugs
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
Labels: area-TabView, team-Controls

#7195 Update min supported version to RS5
  README.md
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/FrameworkPackage/FrameworkPackageContents/AppxManifest.xml
  build/Helix/scripts/TestPass-PreRun.ps1
  build/NuSpecs/MUXControls-Nuget-Common.targets
  dev/InfoBadge/APITests/InfoBadgeTests.cs
  dev/Microsoft.UI.Xaml.FrameworkPackagePRI/Microsoft.UI.Xaml.FrameworkPackagePRI.csproj
  dev/dll/Microsoft.UI.Xaml.Common.props
  test/IXMPTestApp/IXMPTestApp.Shared.projitems
  test/IXMPTestApp/Package.appxmanifest
  test/IXMPTestApp/TAEF/project.json
  test/MUXControlsReleaseTest/AppThatUsesMUXIndirectly/AppThatUsesMUXIndirectly.csproj
  test/MUXControlsReleaseTest/LibraryThatUsesMUX/LibraryThatUsesMUX.csproj
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/MUXControls.ReleaseTest.Shared.projitems
  test/MUXControlsReleaseTest/NugetPackageTestApp/NugetPackageTestApp.csproj
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/NugetPackageTestAppCX.vcxproj
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.nuspec
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.vcxproj
  test/MUXControlsTestApp/MUXControlsTestApp.Shared.projitems
  test/MUXControlsTestApp/TAEF/project.json
  test/MUXExperimentalTest/MUXExperimental.Test/MUXExperimental.Test.Shared.projitems
  test/MUXExperimentalTest/MUXExperimentalTestApp/MUXExperimentalTestApp.csproj
  test/TestAppCX/TestAppCX.vcxproj
  test/testinfra/AppTestAutomationHelpers/AppTestAutomationHelpers.vcxproj
Labels: needs-triage

#7210 Fix for WACK tests after change from appx to msix
  build/AzurePipelinesTemplates/MUX-WACKTests-Job.yml
Labels: needs-triage

#7215 June website update for call
  index.html
Labels: needs-triage

#7205 [ TabView ] High contrast scroll buttons fix
  dev/TabView/TabView.xaml
  dev/TabView/TabView_themeresources.xaml
Labels: needs-triage

#7217 colorpicker localization updates
  dev/ColorPicker/Strings/af-ZA/Resources.resw
  dev/ColorPicker/Strings/az-Latn-AZ/Resources.resw
  dev/ColorPicker/Strings/bg-BG/Resources.resw
  dev/ColorPicker/Strings/bs-Latn-BA/Resources.resw
  dev/ColorPicker/Strings/cs-CZ/Resources.resw
  dev/ColorPicker/Strings/cy-GB/Resources.resw
  dev/ColorPicker/Strings/de-DE/Resources.resw
  dev/ColorPicker/Strings/es-MX/Resources.resw
  dev/ColorPicker/Strings/et-EE/Resources.resw
  dev/ColorPicker/Strings/eu-ES/Resources.resw
  dev/ColorPicker/Strings/fa-IR/Resources.resw
  dev/ColorPicker/Strings/fi-FI/Resources.resw
  dev/ColorPicker/Strings/fr-CA/Resources.resw
  dev/ColorPicker/Strings/gl-ES/Resources.resw
  dev/ColorPicker/Strings/hi-IN/Resources.resw
  dev/ColorPicker/Strings/hr-HR/Resources.resw
  dev/ColorPicker/Strings/id-ID/Resources.resw
  dev/ColorPicker/Strings/ka-GE/Resources.resw
  dev/ColorPicker/Strings/kk-KZ/Resources.resw
  dev/ColorPicker/Strings/lt-LT/Resources.resw
  dev/ColorPicker/Strings/lv-LV/Resources.resw
  dev/ColorPicker/Strings/ms-MY/Resources.resw
  dev/ColorPicker/Strings/nb-NO/Resources.resw
  dev/ColorPicker/Strings/nl-NL/Resources.resw
  dev/ColorPicker/Strings/nn-NO/Resources.resw
  dev/ColorPicker/Strings/pt-PT/Resources.resw
  dev/ColorPicker/Strings/ro-RO/Resources.resw
  dev/ColorPicker/Strings/ru-RU/Resources.resw
  dev/ColorPicker/Strings/sl-SI/Resources.resw
  dev/ColorPicker/Strings/sr-Cyrl-RS/Resources.resw
  dev/ColorPicker/Strings/sr-Latn-RS/Resources.resw
  dev/ColorPicker/Strings/th-TH/Resources.resw
  dev/ColorPicker/Strings/vi-VN/Resources.resw
  dev/ColorPicker/Strings/zh-TW/Resources.resw
Labels: team-Controls

#7214 Enable Velocity in CBS branch
  MUXControls.sln
  build/AzurePipelinesTemplates/MUX-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-InstallNuget-Steps.yml
  dev/Effects/microsoft.ui.private.composition.effects_impl.h
  dev/TabView/TabView.cpp
  dev/dll/Microsoft.UI.Xaml.Common.props
  dev/dll/Microsoft.UI.Xaml.Common.targets
  dev/dll/packages.config
  dev/inc/ErrorHandling.h
  dev/inc/velocity.h
  nuget-pgo.config
  nuget.config
  tools/GenerateNewProperty.ps1
  tools/MUXPGODatabase/restore-pgodb.ps1
Labels: area-DevInternal, team-Controls

#7220 Update JavaScript in WebView2 tests
  dev/WebView2/TestUI/WebView2BasicPage.xaml.cs
  test/MUXControlsTestApp/Assets/SimpleInputPage.html
  test/MUXControlsTestApp/Assets/SimplePage.html
  test/MUXControlsTestApp/Assets/SimplePageForFocus.html
  test/MUXControlsTestApp/Assets/SimplePageWithButton.html
  test/MUXControlsTestApp/Assets/SimplePageWithImage.html
  test/MUXControlsTestApp/Assets/SimplePageWithManyButtons.html
  test/MUXControlsTestApp/Assets/SimplePageWithNonÅscií.html
  test/MUXControlsTestApp/Assets/SimplePageWithScrollableColoredBlocks.html
  test/MUXControlsTestApp/Assets/SimplePageWithText.html
Labels: area-WebView

#7272 Update Newtonsoft.Json to 13.0.1
  test/MUXControls.Test/MSTest/MUXControls.Test.csproj
Labels: needs-triage

#7273 WebView2 should destroy its temporary hwnd if there is no CoreWindow
  dev/WebView2/WebView2.cpp
  dev/WebView2/WebView2.h
Labels: area-WebView

#7274 NavView: Navigation does not work when using Narrator in Scan Mode
  dev/NavigationView/NavigationViewItemAutomationPeer.cpp
  dev/NavigationView/NavigationView_InteractionTests/SelectionTests.cs
Labels: needs-triage

#6970 Fix HyperlinkButton height
  dev/CommonStyles/HyperlinkButton_themeresources.xaml
Labels: team-Controls, area-HyperlinkButton
