Repository microsoft/microsoft-ui-xaml, pull requests merged in 2022-11, with the labels that each got.

#7880 Skip PR Build on bug template changes
  build/ShouldSkipPRBuild.ps1
Labels: auto merge

#7607 Update bug template to 2.8.1 tag
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: area-DevInternal

#7784 Update bug report template to WinAppSDK 1.2-p2
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation, auto merge

#7868 Update bug_report.yaml
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation, auto merge

#7913 Add WinAppSDK 1.2 to bug template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: needs-triage

#7912 Disable WebView2Tests.EdgeProcessFailedTest and ColorPickerTests.ValidateFractionalWidthDoesNotCrash
  dev/ColorPicker/APITests/ColorPickerTests.cs
  dev/WebView2/InteractionTests/WebView2Tests.cs
Labels: needs-triage

#7813 Instrument ReferenceTracker cleanup to try to catch double delete crashes
  dev/inc/DispatcherHelper.h
  dev/inc/RuntimeClassHelpers.h
Labels: needs-triage

#7934 Update bug report template for 1.2.1
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation

#7352 NavigationViewTemplateSettings.OpenPaneLength API Spec
  specs/NavigationViewTemplateSettings-OpenPaneLength.md
  specs/images/nav-pane-closed.jpg
  specs/images/nav-pane-open.jpg
Labels: documentation, area-NavigationView, team-Controls

#6801 Update SingleStateSegmentLookup.md
  dev/AnimatedIcon/Docs/SingleStateSegmentLookup.md
Labels: documentation, team-Controls, area-AnimatedIcon

#6268 Add AnimatedVisualPlayer Improvements Spec
  specs/AnimatedVisualPlayer Spec.md
Labels: area-AnimatedVisualPlayer, team-Controls, SpecInReview

#4518 Spec: Adding a FooterMenuItemTemplate property to NavigationView
  specs/FooterMenuItemTemplate-spec.md
  specs/images/footermenu-example.png
Labels: area-NavigationView, spec issue, team-Controls

#4914 Adding spec for InfoBadge control
  specs/InfoBadge/InfoBadge-spec.md
  specs/InfoBadge/images/asterisk-badge-icon.png
  specs/InfoBadge/images/caution-badge-icon.png
  specs/InfoBadge/images/checkmark-badge-icon.png
  specs/InfoBadge/images/color-breakdown.PNG
  specs/InfoBadge/images/error-badge-icon.png
  specs/InfoBadge/images/infobadge-example1.png
  specs/InfoBadge/images/infobadge-example2.png
  specs/InfoBadge/images/informational-badge-icon.png
  specs/InfoBadge/images/navview-example1.png
  specs/InfoBadge/images/navview-example2.png
  specs/InfoBadge/images/navview-example3.png
  specs/InfoBadge/images/navview-example4.png
  specs/InfoBadge/images/navview-example5.png
  specs/InfoBadge/images/navview-example6.png
Labels: documentation, team-Controls, SpecInReview, area-InfoBadge

#7977 Adjust apiset fallback for user32 dependencies in WebView2
  dev/WebView2/WebView2.cpp
Labels: needs-triage
