Repository microsoft/microsoft-ui-xaml, pull requests merged in 2022-07, with the labels that each got.

#7277 Revoke the items source view changed event if there is one irrespective of the oldValue
  dev/Repeater/ItemsRepeater.cpp
Labels: needs-triage

#7337 Delete Discussion and Question Issue templates
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/question.md
Labels: needs-triage

#7179 WinUI Vpack: Include re-merged winmd
  build/CreateCBSVPack.ps1
Labels: area-DevInternal, team-Controls

#7341 NavigationViewTemplateSettings.OpenPaneLength Update
  dev/Generated/NavigationViewTemplateSettings.properties.cpp
  dev/Generated/NavigationViewTemplateSettings.properties.h
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  dev/NavigationView/NavigationView.idl
  dev/NavigationView/NavigationView.xaml
Labels: area-NavigationView, team-Controls

#7329 Update WebView2 SDK to 1.0.1264.42
  build/CopyFilesToStagingDir.ps1
  build/NuSpecs/MUXControls.nuspec
  build/NuSpecs/MUXControlsFrameworkPackage.nuspec
  dev/WebView2/InteractionTests/WebView2Tests.cs
  dev/WebView2/WebView2.cpp
  dev/WebView2/WebView2.idl
  dev/dll/Microsoft.UI.Xaml.Common.targets
  dev/dll/packages.config
  test/MUXControls.Test/MSTest/MUXControls.Test.csproj
  test/MUXControls.Test/TAEF/MUXControls.Test.TAEF.csproj
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.vcxproj
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/packages.config
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
  test/MUXControlsTestApp/TAEF/project.json
  test/TestAppCX/TestAppCX.vcxproj
  test/TestAppCX/packages.config
Labels: area-WebView

#7345 Fix WebView2 accessibility crash in ProviderWrapper::GetRuntimeId
  dev/WebView2/WebView2AutomationPeer.cpp
Labels: area-WebView, needs-triage

#7353 Update PhoneId in MUX Framework Package appxmanifest
  build/FrameworkPackage/FrameworkPackageContents/AppxManifest.xml
Labels: area-NugetPackage, team-Controls

#7351 Sync WebView2 code with WinUI 3
  dev/WebView2/InteractionTests/WebView2Tests.cs
  dev/WebView2/TestUI/WebView2BasicPage.xaml.cs
  dev/WebView2/WebView2.cpp
  dev/WebView2/WebView2.h
Labels: needs-triage

#7363 Update all usage of Newtonsoft.Json to 13.0.1
  test/IXMPTestApp/MSTest/IXMPTestApp.csproj
  test/IXMPTestApp/TAEF/project.json
  test/MUXControls.Test/TAEF/MUXControls.Test.TAEF.csproj
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
  test/MUXControlsTestApp/TAEF/project.json
Labels: needs-triage

#7370 Update license.txt
  build/NuSpecs/license.txt
Labels: needs-triage

#7379 Update PhoneProductId
  build/FrameworkPackage/FrameworkPackageContents/AppxManifest.xml
Labels: needs-triage

#7380 localization update
  dev/ColorPicker/Strings/af-ZA/Resources.resw
  dev/ColorPicker/Strings/az-Latn-AZ/Resources.resw
  dev/ColorPicker/Strings/bg-BG/Resources.resw
  dev/ColorPicker/Strings/bs-Latn-BA/Resources.resw
  dev/ColorPicker/Strings/ca-ES/Resources.resw
  dev/ColorPicker/Strings/de-DE/Resources.resw
  dev/ColorPicker/Strings/el-GR/Resources.resw
  dev/ColorPicker/Strings/es-MX/Resources.resw
  dev/ColorPicker/Strings/fa-IR/Resources.resw
  dev/ColorPicker/Strings/fr-CA/Resources.resw
  dev/ColorPicker/Strings/fr-FR/Resources.resw
  dev/ColorPicker/Strings/ja-JP/Resources.resw
  dev/ColorPicker/Strings/ka-GE/Resources.resw
  dev/ColorPicker/Strings/lt-LT/Resources.resw
  dev/ColorPicker/Strings/nb-NO/Resources.resw
  dev/ColorPicker/Strings/nn-NO/Resources.resw
  dev/ColorPicker/Strings/pt-PT/Resources.resw
  dev/ColorPicker/Strings/sk-SK/Resources.resw
  dev/ColorPicker/Strings/sl-SI/Resources.resw
  dev/ColorPicker/Strings/sv-SE/Resources.resw
  dev/ColorPicker/Strings/th-TH/Resources.resw
  dev/ColorPicker/Strings/vi-VN/Resources.resw
Labels: team-Controls

#7378 Update website to August 22 call
  index.html
Labels: documentation

#7403 Update bug report tag to 1.1.3
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: needs-triage

#7407 Update PhoneIdentity for 2.7
  build/FrameworkPackage/FrameworkPackageContents/AppxManifest.xml
Labels: needs-triage

#7520 Update 0.8.11 tag in bug report
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: needs-triage

#7396 Updating TabView keyboarding to make close buttons reachable
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TabView.h
  dev/TabView/TabViewItem.cpp
  dev/TabView/TabViewItem.h
Labels: area-TabView, team-Controls

#7539 Set IsTabStop=False on scroll buttons in TabView
  dev/TabView/TabView.xaml
Labels: needs-triage
