Repository microsoft/microsoft-ui-xaml, pull requests merged in 2022-02, with the labels that each got.

#6665 Update IsAPIContractVxAvailable to be multi thread safe.
  dev/dll/SharedHelpers.cpp
Labels: needs-triage

#6669 Fix typo in helix queue name
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
Labels: needs-triage

#6667 Fix occasional WebView2 Crash when restoring minimized app (0x80070057)
  dev/WebView2/WebView2.cpp
  dev/WebView2/WebView2.h
Labels: needs-triage

#6607 Fix issue where pips pagers crash when the next or previous arrow button is clicked in RTL flow direction
  dev/PipsPager/InteractionTests/PipsPagerTests.cs
  dev/PipsPager/PipsPager_themeresources.xaml
  dev/RatingControl/InteractionTests/RatingControlTests.cs
  test/TestAppUtils/TestFrame.cs
  test/TestAppUtils/Themes/Generic.xaml
  test/testinfra/MUXTestInfra/Infra/TestHelpers.cs
Labels: team-Controls, area-PipsPager

#6679 Tabview bottom right inverted contour fix
  dev/TabView/TabView.xaml
Labels: needs-triage

#6687 TabView HC Brush Updates
  dev/CommonStyles/Common_themeresources_any.xaml
Labels: needs-triage

#6675 Update roadmap.md
  docs/roadmap.md
Labels: documentation, product-winui3

#6694 Adding MicaController RuntimeProfiler recording
  dev/CommonStyles/TestUI/CalendarViewPage.xaml.cs
  dev/Materials/Backdrop/MicaController.cpp
  dev/Materials/Backdrop/MicaController.h
  dev/Telemetry/RuntimeProfiler.h
  test/MUXControlsTestApp/MainPage.xaml
  test/TestAppUtils/TestFrame.cs
  test/TestAppUtils/Themes/Generic.xaml
Labels: needs-triage

#6677 Add new WebView2 tests, add focus logging to WebView2 tests, avoid potential flicker when removing
  dev/WebView2/InteractionTests/WebView2Tests.cs
  dev/WebView2/TestUI/WebView2BasicPage.xaml
  dev/WebView2/TestUI/WebView2BasicPage.xaml.cs
  dev/WebView2/WebView2.cpp
  test/MUXControlsTestApp/Assets/SimpleInputPage.html
  test/MUXControlsTestApp/Assets/SimplePage.html
  test/MUXControlsTestApp/Assets/SimplePageForFocus.html
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
Labels: area-WebView, team-Rendering

#6693 TabView bottom border gap fix
  dev/TabView/TabViewListView.cpp
  dev/TabView/TabViewListView.h
Labels: needs-triage

#6718 Enable Software Bill of Materials task in Release build
  build/AzurePipelinesTemplates/MUX-BuildDevProject-Steps.yml
  build/MUX-Release.yml
Labels: needs-triage

#6691 Update ProgressRing Lottie File
  dev/ProgressRing/AnimatedVisuals/ProgressRingDeterminate.cpp
  dev/ProgressRing/AnimatedVisuals/ProgressRingDeterminate.h
  dev/ProgressRing/ProgressRing.vcxitems.filters
  dev/ProgressRing/TestUI/ProgressRingPage.xaml
Labels: needs-triage

#6311 Update WebView2 nupkg dependency to latest
  build/NuSpecs/MUXControls.nuspec
  build/NuSpecs/MUXControlsFrameworkPackage.nuspec
  dev/dll/Microsoft.UI.Xaml.Common.targets
  dev/dll/packages.config
  test/MUXControls.Test/MSTest/MUXControls.Test.csproj
  test/MUXControls.Test/TAEF/MUXControls.Test.TAEF.csproj
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/RuntimeComponentThatUsesMUX.vcxproj
  test/MUXControlsReleaseTest/RuntimeComponentThatUsesMUX/packages.config
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
  test/MUXControlsTestApp/TAEF/project.json
  test/TestAppCX/TestAppCX.vcxproj
  test/TestAppCX/packages.config
Labels: area-WebView, needs-triage, team-Rendering

#6730 [ MenuBar ] In high contrast, the focus visual overlaps the button border and is barely (or not at all) visible
  dev/MenuBar/MenuBarItem.xaml
Labels: needs-triage

#6372 put newest nuget pkg versions at the top of the bug template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: needs-triage

#6739 [ NavigationView ] Chevron does not meet contrast requirements in Aquatic High Contrast theme
  dev/NavigationView/NavigationView_rs1_themeresources.xaml
Labels: needs-triage

#6744 Add comments to help investigate crashes in UpdateSource when UpdateAcrylicBrushesDarkTheme
  dev/dll/XamlControlsResources.cpp
Labels: needs-triage

#6747 Avoid layout cycle changing SelectedBackgroundPath Path size within TabViewItem::OnSizeChanged
  dev/TabView/TabViewItem.cpp
Labels: area-TabView, needs-triage

#6736 [ CalendarDatePicker ] Remove unnessessary focus state
  dev/CommonStyles/CalendarDatePicker_themeresources.xaml
Labels: needs-triage

#6374 link to VS2022 version of Project System Tools ext
  docs/debugging_buildfailures.md
Labels: documentation

#6731 Update PGO queue
  build/MUX-PGOInstrument.yml
Labels: needs-triage

#6706 Update AnimatedChevronDownSmallVisualSource with updated design
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.cpp
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.h
  dev/AnimatedIcon/AnimatedVisuals/AnimatedChevronDownSmallVisualSource.idl
Labels: area-UIDesign, team-Controls, area-AnimatedIcon

#6541 Fix TeachingTip getting stuck closed
  dev/TeachingTip/TeachingTip.cpp
  dev/TeachingTip/TeachingTip.h
Labels: area-TeachingTip, team-Controls

#6772 Change all tabs to spaces
  Build.cmd
  CustomInlineTasks.targets
  Directory.Build.props
  InnerLoopAreas.props
  SdkVersion.props
  build/FrameworkPackage/MakeFrameworkPackage.cmd
  build/NuSpecs/MakeAllAppx.cmd
  dev/AnimatedIcon/Docs/AnimatedIconDevDesign.md
  dev/AnimatedIcon/Docs/MultiStateSegmentLookupProposal.md
  dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp
  dev/CommonStyles/TextBox_themeresources.xaml
  dev/CommonStyles/TextBox_themeresources_v1.xaml
  dev/ImageIcon/APITests/ImageIconTests.cs
  dev/Microsoft.UI.Xaml.FrameworkPackagePRI/Properties/Microsoft.UI.Xaml.rd.xml
  dev/NavigationView/NavigationView_rs1_themeresources_v1.xaml
  dev/PullToRefresh/RefreshVisualizer/RefreshVisualizer.h
  dev/Repeater/InspectingDataSource.h
  dev/ScrollPresenter/SnapPointWrapper.h
  dev/TeachingTip/TeachingTip.xaml
  dev/TeachingTip/TestUI/TeachingTipPage.xaml.cs
  dev/dll/WinRtType.tt
  docs/communitycalls/WinUICommunityCall.ics
  docs/contribution_workflow.md
  mux.controls.props
  test/MUXControlsReleaseTest/LibraryThatUsesMUX/Properties/LibraryThatUsesMUX.rd.xml
  test/MUXControlsReleaseTest/MUXControls.ReleaseTest/Properties/MUXControls.ReleaseTest.rd.xml
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/App.xaml.h
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/MainPage.xaml.cpp
  test/MUXExperimentalTest/MUXExperimental.Test/Properties/MUXExperimental.Test.rd.xml
  test/TestAppCX/BackdropMaterialTestPage.xaml.cpp
  test/TestAppCX/BackdropMaterialTestPage.xaml.h
  test/TestAppCX/CornerRadiusTestPage.xaml.cpp
  test/TestAppCX/CornerRadiusTestPage.xaml.h
  test/TestAppCX/MenuBarTestPage.xaml.cpp
  test/TestAppCX/MenuBarTestPage.xaml.h
  test/TestAppCX/TreeViewTestPage.xaml.h
  test/TestAppCX/WebView2TestPage.xaml.cpp
  test/TestAppCX/WebView2TestPage.xaml.h
  test/testinfra/MUXTestInfra/Infra/TestHelpers.cs
  tools/GenerateNewControlProject.ps1
  tools/GenerateVisualVerificationUpdates.ps1
  tools/MakeAppxHelper.cmd
Labels: needs-triage

#6766 Add PackageES Security and Compliance task to build
  build/AzurePipelinesTemplates/MUX-BuildDevProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-ComplianceChecks-Job.yml
  build/MUX-Release.yml
  dev/GeneratedExperimental/TitleBar.properties.cpp
  dev/GeneratedExperimental/TitleBar.properties.h
  dev/dll/Microsoft.UI.Xaml.Common.targets
  dev/dll/Microsoft.UI.Xaml.vcxproj
  dev/dll/Microsoft.UI.Xaml.vcxproj.filters
Labels: area-DevInternal, team-Controls

#6724 Fixed Corner Radius Issue with InkToolbar Custom Tool Button
  dev/CommonStyles/InkToolbar_themeresources.xaml
Labels: needs-triage

#6676 [AnimatedIcon] Fix issue where setting source property would not resize AnimatedIcon properly
  dev/AnimatedIcon/APITests/AnimatedIconTests.cs
  dev/AnimatedIcon/AnimatedIcon.cpp
Labels: team-Controls, area-AnimatedIcon

#6673 Update Bug Report template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation, needs-triage

#6391 Validate doc links in PR/CI
  .github/workflows/docs.yml
  docs/.unbroken_exclusions
  docs/winui3_migration.md
Labels: documentation, team-Controls

#6382 Make ContentDialog's title respect ContentControlThemeFontFamily
  dev/CommonStyles/ContentDialog_themeresources.xaml
  dev/CommonStyles/ContentDialog_themeresources_v1.xaml
Labels: area-Dialogs, team-Controls

#6644 TabView gap between active tab and active content fix
  dev/TabView/TabViewItem.cpp
  dev/TabView/TestUI/TabViewPage.xaml
  dev/TabView/TestUI/TabViewPage.xaml.cs
Labels: area-TabView, team-Controls
