Repository microsoft/microsoft-ui-xaml, pull requests merged in 2022-08, with the labels that each got.

#7530 Remove unused browser argument when creating WebView2 CompositionController
  dev/WebView2/WebView2.cpp
Labels: area-WebView

#7555 Fix bugs in WebView2 cursor updating
  dev/WebView2/InteractionTests/WebView2Tests.cs
  dev/WebView2/TestUI/WebView2BasicPage.xaml
  dev/WebView2/TestUI/WebView2BasicPage.xaml.cs
  dev/WebView2/WebView2.cpp
  dev/WebView2/WebView2.h
Labels: area-WebView, needs-triage

#7566 1.2-exp & 0.8.12 bug template update
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: needs-triage

#7574 Ensure correct .props and .targets order in nuget package
  build/NuSpecs/MUXControls-Nuget-Common.targets
  build/NuSpecs/MUXControls-Nuget-FrameworkPackage-Native.props
  build/NuSpecs/MUXControls-Nuget-FrameworkPackage.targets
  build/NuSpecs/MUXControls-Nuget-Native.props
  build/NuSpecs/MUXControls.nuspec
  build/NuSpecs/MUXControlsFrameworkPackage.nuspec
Labels: needs-triage

#7575 WebView2 should cache input state
  dev/WebView2/WebView2.cpp
  dev/WebView2/WebView2.h
Labels: needs-triage

#7597 Import WinUI .props to NugetPackageTestAppCX
  test/MUXControlsReleaseTest/NugetPackageTestAppCX/NugetPackageTestAppCX.vcxproj
Labels: needs-triage

#7598 Update bug template tag to 1.1.4
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation

#7599 Fix building with Visual Studio 2022
  Directory.Build.props
  dev/TabView/TabView.cpp
  test/IXMPTestApp/MSTest/IXMPTestApp.csproj
  test/MUXControls.Test/MUXControls.Test.Shared.targets
  test/MUXControlsTestApp/MSTest/MUXControlsTestApp.csproj
Labels: needs-triage

#7592 Cherry-picking a NavigationView crash fix to 2.7
  dev/NavigationView/NavigationView.cpp
  dev/NavigationView/NavigationView.h
  test/testinfra/AppTestAutomationHelpers/AppTestAutomationHelpers.vcxproj
Labels: needs-triage

#7591 Update areaPath in tsaoptions.json. Add token to PkgESVPack
  .config/tsaoptions.json
  build/AzurePipelinesTemplates/MUX-PushCBSVpack-Job.yml
Labels: needs-triage

#7643 Update tsaoptions.json to fix ADO path (DXP -> ADEPT)
  .config/tsaoptions.json
Labels: area-DevInternal

#7197 Keyboard text alignment
  dev/CommandBarFlyout/CommandBarFlyout_themeresources.xaml
  dev/CommandBarFlyout/CommandBarFlyout_themeresources_v1.xaml
  dev/CommonStyles/AppBarButton_themeresources.xaml
  dev/CommonStyles/AppBarButton_themeresources_v1.xaml
  dev/CommonStyles/AppBarToggleButton_themeresources.xaml
  dev/CommonStyles/AppBarToggleButton_themeresources_v1.xaml
  dev/CommonStyles/MediaTransportControls_themeresources_v1.xaml
  dev/CommonStyles/MenuFlyout_themeresources.xaml
  dev/CommonStyles/MenuFlyout_themeresources_v1.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs4_themeresources_v1.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_rs5_themeresources_v1.xaml
  dev/RadioMenuFlyoutItem/RadioMenuFlyoutItem_themeresources.xaml
Labels: area-Menus, area-Commanding, team-Controls, area-CommandBarFlyout

#7642 Add an apiset fallback for user32 dependencies in WebView2
  dev/WebView2/WebView2.cpp
Labels: needs-triage

#7634 Capture weak ref to this in AnimatedVisualPlayer::DestroyAnimations lambda
  dev/AnimatedVisualPlayer/AnimatedVisualPlayer.cpp
Labels: area-AnimatedVisualPlayer, team-Controls

#7669 Disable unreliable test RatingControlTests.MaxRatingTest
  dev/RatingControl/InteractionTests/RatingControlTests.cs
Labels: needs-triage
