Repository microsoft/microsoft-ui-xaml, pull requests merged in 2023-05, with the labels that each got.

#8403 Fix horizontal scrolling on trackpad
  dev/WebView2/WebView2.cpp
Labels: area-WebView, needs-triage, team-Rendering

#8139 Xaml Backdrop API spec
  specs/xaml-backdrop-api.md
Labels: SpecInReview

#8471 Update bug_report.yaml to 1.3.1
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: needs-triage

#8485 Fix pgo pipeline
  build/AzurePipelinesTemplates/MUX-MergePGD-Job.yml
  build/MUX-PGOInstrument.yml
Labels: needs-triage

#8510 Update bug_report.yaml for 1.4 experimental 1
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: needs-triage
