Repository microsoft/microsoft-ui-xaml, pull requests merged in 2023-04, with the labels that each got.

#8372 Update Microsoft.Internal.WinUI.Helix to 0.0.2.6
  build/AzurePipelinesTemplates/MUX-ProcessTestResults-Job.yml
  build/Helix/packages.config
  dev/WebView2/InteractionTests/WebView2Tests.cs
Labels: needs-triage

#8363 WebView2: Ensure safe access to owner across coroutines
  dev/WebView2/WebView2.cpp
Labels: needs-triage

#8430 TabView TabGeometry Animation Loop & Under Tab Line Fix
  dev/TabView/TabView.cpp
  dev/TabView/TabView.xaml
  dev/TabView/TabViewItem.cpp
Labels: needs-triage

#8386 Repo updates for 1.3.0 release
  .github/ISSUE_TEMPLATE/bug_report.yaml
  README.md
  docs/roadmap.md
Labels: documentation

#8420 TabView.ItemChanged Event Fix
  dev/TabView/InteractionTests/TabViewTests.cs
  dev/TabView/TabView.cpp
  dev/TabView/TestUI/TabViewPage.xaml
  dev/TabView/TestUI/TabViewPage.xaml.cs
Labels: needs-triage

#8439 Execute tests directly on Pipeline
  PGO.runtime.props
  build/AzurePipelinesTemplates/MUX-BuildAndPublishPGONuGet-Job.yml
  build/AzurePipelinesTemplates/MUX-BuildDevProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-BuildProject-Steps.yml
  build/AzurePipelinesTemplates/MUX-CreateHelixProjFile-Steps.yml
  build/AzurePipelinesTemplates/MUX-CreateNugetPackage-Job.yml
  build/AzurePipelinesTemplates/MUX-MergePGD-Job.yml
  build/AzurePipelinesTemplates/MUX-NugetReleaseTest-Job.yml
  build/AzurePipelinesTemplates/MUX-ProcessTestResults-Job.yml
  build/AzurePipelinesTemplates/MUX-RestorePgo-Steps.yml
  build/AzurePipelinesTemplates/MUX-RunHelixTests-Job.yml
  build/AzurePipelinesTemplates/MUX-RunTestsOnPipeline-Job.yml
  build/AzurePipelinesTemplates/MUX-WACKTests-Job.yml
  build/CopyFilesToStagingDir.ps1
  build/Helix/CopyPGOFiles.ps1
  build/Helix/PrepareHelixPayload.ps1
  build/Helix/packages.config
  build/Helix/scripts/TestPass-OneTimeMachineSetup.ps1
  build/MUX-CI.yml
  build/MUX-PGOInstrument.yml
  build/MUX-PR.yml
  build/WinUI-Official-Validation.yml
  environment.props
  test/IXMPTestApp/Tests/MetadataProviderTests.cs
Labels: needs-triage

#8443 Fix logic to skip build stage in PR pipeline for markdown only changes
  build/MUX-PR.yml
Labels: needs-triage

#7245 Adding API review docs for ScrollPresenter and ScrollView controls
  specs/ScrollingControls/ScrollPresenter.md
  specs/ScrollingControls/ScrollView.md
  specs/ScrollingControls/images/BothScrollBars.png
  specs/ScrollingControls/images/FonteApp.png
  specs/ScrollingControls/images/HScrollInsidePivot.png
  specs/ScrollingControls/images/HStackPanelSnapPoints.png
  specs/ScrollingControls/images/MicrosoftStore.jpg
  specs/ScrollingControls/images/RepeatedSnapPoints.png
  specs/ScrollingControls/images/ScrollView.png
  specs/ScrollingControls/images/ScrollViewProps.png
  specs/ScrollingControls/images/ScrollView_ScrollPresenter_overlap.png
  specs/ScrollingControls/images/ScrollingObjects.png
  specs/ScrollingControls/images/SnapPoint_Type_Hierarchy.png
  specs/ScrollingControls/images/SnapPoints.png
  specs/ScrollingControls/images/SnapPointsAlignment.png
  specs/ScrollingControls/images/SnapPointsCustomActiveRange.png
  specs/ScrollingControls/images/VStackPanelSnapPoints.png
  specs/ScrollingControls/images/VerticalScrollBar.png
  specs/ScrollingControls/images/VerticalScrollSnapPoints.png
  specs/ScrollingControls/images/VerticalTimelineScrubber.png
  specs/ScrollingControls/images/ViewportAndExtent.png
  specs/ScrollingControls/images/scroll-controls.jpg
Labels: documentation, area-Scrolling, team-Controls, SpecInReview

#4859 CaldendarView property additions for rendering updates
  specs/CalendarView/CalendarViewSpec1.md
  specs/CalendarView/images/BlackoutStrikethroughBrush.png
  specs/CalendarView/images/BlackoutTodayBackgroundAndForeground.png
  specs/CalendarView/images/CalendarItemCornerRadiusSetToFour.png
  specs/CalendarView/images/DefaultCalendarItemCornerRadius.png
  specs/CalendarView/images/DisabledCalendarView.png
  specs/CalendarView/images/HoverItemBackground.png
  specs/CalendarView/images/HoverOutOfScopeForeground.png
  specs/CalendarView/images/HoverTodayBackground.png
  specs/CalendarView/images/MonthViewWithVisibleGroupLabels.png
  specs/CalendarView/images/PressedItemBackground.png
  specs/CalendarView/images/PressedOutOfScopeForeground.png
  specs/CalendarView/images/PressedTodayBackground.png
  specs/CalendarView/images/SelectedTodayBorder.png
  specs/CalendarView/images/TodayDecadeBackground.png
  specs/CalendarView/images/TodayMonthBackground.png
  specs/CalendarView/images/TodayYearBackground.png
  specs/CalendarView/images/YearViewWithVisibleGroupLabels.png
Labels: area-DateTimePickers, team-Controls, SpecInReview

#8184 API review: Allow developers to provide a custom MRT Core `IResourceManager` implementation
  specs/custom-iresourcemanager-spec.md
Labels: SpecInReview
