Repository microsoft/microsoft-ui-xaml, pull requests merged in 2023-02, with the labels that each got.

#8156 Add WinAppSDK 1.3-exp1 to bug template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: documentation

#8170 Update Package Versions
  build/Helix/packages.config
  test/MUXControls.Test/MSTest/MUXControls.Test.csproj
  test/MUXControls.Test/TAEF/MUXControls.Test.TAEF.csproj
Labels: area-DevInternal

#8180 Update repo docs to latest info
  README.md
  docs/communitycalls/WinUICommunityCall.ics
  docs/roadmap.md
Labels: needs-triage
